"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from poktroll_clients.proto.pocket.application import types_pb2 as _types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _ApplicationUnbondingReason:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ApplicationUnbondingReasonEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ApplicationUnbondingReason.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    APPLICATION_UNBONDING_REASON_ELECTIVE: _ApplicationUnbondingReason.ValueType  # 0
    APPLICATION_UNBONDING_REASON_BELOW_MIN_STAKE: _ApplicationUnbondingReason.ValueType  # 1
    APPLICATION_UNBONDING_REASON_MIGRATION: _ApplicationUnbondingReason.ValueType  # 2

class ApplicationUnbondingReason(_ApplicationUnbondingReason, metaclass=_ApplicationUnbondingReasonEnumTypeWrapper): ...

APPLICATION_UNBONDING_REASON_ELECTIVE: ApplicationUnbondingReason.ValueType  # 0
APPLICATION_UNBONDING_REASON_BELOW_MIN_STAKE: ApplicationUnbondingReason.ValueType  # 1
APPLICATION_UNBONDING_REASON_MIGRATION: ApplicationUnbondingReason.ValueType  # 2
Global___ApplicationUnbondingReason: _TypeAlias = ApplicationUnbondingReason  # noqa: Y015

@_typing.final
class EventApplicationStaked(_message.Message):
    """EventApplicationStaked is emitted when an application is staked or up-staked."""

    DESCRIPTOR: _descriptor.Descriptor

    APPLICATION_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    session_end_height: _builtins.int
    """The end height of the session in which the application was staked."""
    @_builtins.property
    def application(self) -> _types_pb2.Application: ...
    def __init__(
        self,
        *,
        application: _types_pb2.Application | None = ...,
        session_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["application", b"application"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application", b"application", "session_end_height", b"session_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventApplicationStaked: _TypeAlias = EventApplicationStaked  # noqa: Y015

@_typing.final
class EventRedelegation(_message.Message):
    """EventRedelegation is an event emitted whenever an application changes its
    delegatee gateways on chain. This is in response to both a DelegateToGateway
    and UndelegateFromGateway message.
    """

    DESCRIPTOR: _descriptor.Descriptor

    APPLICATION_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    session_end_height: _builtins.int
    """The end height of the session in which the redelegation was committed."""
    @_builtins.property
    def application(self) -> _types_pb2.Application:
        """The application which was redelegated."""

    def __init__(
        self,
        *,
        application: _types_pb2.Application | None = ...,
        session_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["application", b"application"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application", b"application", "session_end_height", b"session_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventRedelegation: _TypeAlias = EventRedelegation  # noqa: Y015

@_typing.final
class EventTransferBegin(_message.Message):
    """EventTransferBegin is emitted whenever an application begins a transfer. It
    includes the source application state immediately after the transfer began.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SOURCE_ADDRESS_FIELD_NUMBER: _builtins.int
    DESTINATION_ADDRESS_FIELD_NUMBER: _builtins.int
    SOURCE_APPLICATION_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    TRANSFER_END_HEIGHT_FIELD_NUMBER: _builtins.int
    source_address: _builtins.str
    destination_address: _builtins.str
    session_end_height: _builtins.int
    """The end height of the session in which the transfer began."""
    transfer_end_height: _builtins.int
    """The height at which the transfer will complete."""
    @_builtins.property
    def source_application(self) -> _types_pb2.Application: ...
    def __init__(
        self,
        *,
        source_address: _builtins.str = ...,
        destination_address: _builtins.str = ...,
        source_application: _types_pb2.Application | None = ...,
        session_end_height: _builtins.int = ...,
        transfer_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["source_application", b"source_application"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["destination_address", b"destination_address", "session_end_height", b"session_end_height", "source_address", b"source_address", "source_application", b"source_application", "transfer_end_height", b"transfer_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventTransferBegin: _TypeAlias = EventTransferBegin  # noqa: Y015

@_typing.final
class EventTransferEnd(_message.Message):
    """EventTransferEnd is emitted whenever an application transfer is completed. It
    includes the destination application state at the time the transfer completed.
    Either EventTransferEnd or EventTransferError will be emitted corresponding to
    any given EventTransferBegin event.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SOURCE_ADDRESS_FIELD_NUMBER: _builtins.int
    DESTINATION_ADDRESS_FIELD_NUMBER: _builtins.int
    DESTINATION_APPLICATION_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    TRANSFER_END_HEIGHT_FIELD_NUMBER: _builtins.int
    source_address: _builtins.str
    destination_address: _builtins.str
    session_end_height: _builtins.int
    """The end height of the session in which the transfer ended."""
    transfer_end_height: _builtins.int
    """The height at which the transfer completed."""
    @_builtins.property
    def destination_application(self) -> _types_pb2.Application: ...
    def __init__(
        self,
        *,
        source_address: _builtins.str = ...,
        destination_address: _builtins.str = ...,
        destination_application: _types_pb2.Application | None = ...,
        session_end_height: _builtins.int = ...,
        transfer_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["destination_application", b"destination_application"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["destination_address", b"destination_address", "destination_application", b"destination_application", "session_end_height", b"session_end_height", "source_address", b"source_address", "transfer_end_height", b"transfer_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventTransferEnd: _TypeAlias = EventTransferEnd  # noqa: Y015

@_typing.final
class EventTransferError(_message.Message):
    """EventTransferError is emitted whenever an application transfer fails. It
    includes the source application state at the time the transfer failed and
    the error message.
    Either EventTransferEnd or EventTransferError will be emitted corresponding to
    any given EventTransferBegin event.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SOURCE_ADDRESS_FIELD_NUMBER: _builtins.int
    DESTINATION_ADDRESS_FIELD_NUMBER: _builtins.int
    SOURCE_APPLICATION_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    source_address: _builtins.str
    destination_address: _builtins.str
    session_end_height: _builtins.int
    """The end height of the session in which the transfer failed."""
    error: _builtins.str
    @_builtins.property
    def source_application(self) -> _types_pb2.Application: ...
    def __init__(
        self,
        *,
        source_address: _builtins.str = ...,
        destination_address: _builtins.str = ...,
        source_application: _types_pb2.Application | None = ...,
        session_end_height: _builtins.int = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["source_application", b"source_application"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["destination_address", b"destination_address", "error", b"error", "session_end_height", b"session_end_height", "source_address", b"source_address", "source_application", b"source_application"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventTransferError: _TypeAlias = EventTransferError  # noqa: Y015

@_typing.final
class EventApplicationUnbondingBegin(_message.Message):
    """EventApplicationUnbondingBegin is emitted when an application begins unbonding.
    This can be triggered by the commitment of an unstake message or by the application's
    stake dropping below the minimum. This event signals that an application has begun
    unbonding. The unbonding period is determined by the shared param,
    application_unbonding_period_sessions.
    """

    DESCRIPTOR: _descriptor.Descriptor

    APPLICATION_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    UNBONDING_END_HEIGHT_FIELD_NUMBER: _builtins.int
    reason: Global___ApplicationUnbondingReason.ValueType
    session_end_height: _builtins.int
    """The end height of the session in which the unbonding began."""
    unbonding_end_height: _builtins.int
    """The height at which application unbonding will end."""
    @_builtins.property
    def application(self) -> _types_pb2.Application: ...
    def __init__(
        self,
        *,
        application: _types_pb2.Application | None = ...,
        reason: Global___ApplicationUnbondingReason.ValueType = ...,
        session_end_height: _builtins.int = ...,
        unbonding_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["application", b"application"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application", b"application", "reason", b"reason", "session_end_height", b"session_end_height", "unbonding_end_height", b"unbonding_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventApplicationUnbondingBegin: _TypeAlias = EventApplicationUnbondingBegin  # noqa: Y015

@_typing.final
class EventApplicationUnbondingEnd(_message.Message):
    """EventApplicationUnbondingEnd is emitted when an application has completed
    unbonding. The unbonding period is determined by the shared param,
    application_unbonding_period_sessions.
    """

    DESCRIPTOR: _descriptor.Descriptor

    APPLICATION_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    UNBONDING_END_HEIGHT_FIELD_NUMBER: _builtins.int
    reason: Global___ApplicationUnbondingReason.ValueType
    session_end_height: _builtins.int
    """The end height of the session in which the unbonding ended."""
    unbonding_end_height: _builtins.int
    """The height at which application unbonding ended."""
    @_builtins.property
    def application(self) -> _types_pb2.Application: ...
    def __init__(
        self,
        *,
        application: _types_pb2.Application | None = ...,
        reason: Global___ApplicationUnbondingReason.ValueType = ...,
        session_end_height: _builtins.int = ...,
        unbonding_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["application", b"application"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application", b"application", "reason", b"reason", "session_end_height", b"session_end_height", "unbonding_end_height", b"unbonding_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventApplicationUnbondingEnd: _TypeAlias = EventApplicationUnbondingEnd  # noqa: Y015

@_typing.final
class EventApplicationUnbondingCanceled(_message.Message):
    """EventApplicationUnbondingCanceled is emitted when an application which was unbonding
    successfully (re-)stakes before the unbonding period has elapsed. An EventApplicationStaked
    event will also be emitted immediately after this event.
    """

    DESCRIPTOR: _descriptor.Descriptor

    APPLICATION_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    session_end_height: _builtins.int
    """The end height of the session in which the unbonding was canceled."""
    @_builtins.property
    def application(self) -> _types_pb2.Application: ...
    def __init__(
        self,
        *,
        application: _types_pb2.Application | None = ...,
        session_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["application", b"application"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application", b"application", "session_end_height", b"session_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventApplicationUnbondingCanceled: _TypeAlias = EventApplicationUnbondingCanceled  # noqa: Y015
