"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from poktroll_clients.proto.pocket.application import params_pb2 as _params_pb2
from poktroll_clients.proto.pocket.application import types_pb2 as _types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GenesisState(_message.Message):
    """GenesisState defines the application module's genesis state."""

    DESCRIPTOR: _descriptor.Descriptor

    PARAMS_FIELD_NUMBER: _builtins.int
    APPLICATION_LIST_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def params(self) -> _params_pb2.Params:
        """params defines all the parameters of the module."""

    @_builtins.property
    def application_list(self) -> _containers.RepeatedCompositeFieldContainer[_types_pb2.Application]: ...
    def __init__(
        self,
        *,
        params: _params_pb2.Params | None = ...,
        application_list: _abc.Iterable[_types_pb2.Application] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application_list", b"application_list", "params", b"params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GenesisState: _TypeAlias = GenesisState  # noqa: Y015
