"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from poktroll_clients.proto.cosmos.base.v1beta1 import coin_pb2 as _coin_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from poktroll_clients.proto.pocket.application import params_pb2 as _params_pb2
from poktroll_clients.proto.pocket.shared import service_pb2 as _service_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MsgUpdateParams(_message.Message):
    """MsgUpdateParams is the Msg/UpdateParams request type."""

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    PARAMS_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """authority is the address that controls the module (defaults to x/gov unless overwritten)."""
    @_builtins.property
    def params(self) -> _params_pb2.Params:
        """TODO_IMPROVE(#322): The requirement to provide all params is adopted from the
        latest Cosmos SDK version. We should look into either improving this ourselves
        or seeing if it is on their roadmap.

        params defines the x/application parameters to update.
        NOTE: All parameters must be supplied.
        """

    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        params: _params_pb2.Params | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authority", b"authority", "params", b"params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgUpdateParams: _TypeAlias = MsgUpdateParams  # noqa: Y015

@_typing.final
class MsgUpdateParamsResponse(_message.Message):
    """MsgUpdateParamsResponse defines the response structure for executing a
    MsgUpdateParams message.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUpdateParamsResponse: _TypeAlias = MsgUpdateParamsResponse  # noqa: Y015

@_typing.final
class MsgStakeApplication(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    STAKE_FIELD_NUMBER: _builtins.int
    SERVICES_FIELD_NUMBER: _builtins.int
    address: _builtins.str
    """The Bech32 address of the application."""
    @_builtins.property
    def stake(self) -> _coin_pb2.Coin:
        """The total amount of uPOKT the application has staked. Must be ≥ to the current amount that the application has staked (if any)"""

    @_builtins.property
    def services(self) -> _containers.RepeatedCompositeFieldContainer[_service_pb2.ApplicationServiceConfig]:
        """The list of services this application is staked to request service for"""

    def __init__(
        self,
        *,
        address: _builtins.str = ...,
        stake: _coin_pb2.Coin | None = ...,
        services: _abc.Iterable[_service_pb2.ApplicationServiceConfig] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stake", b"stake"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "services", b"services", "stake", b"stake"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgStakeApplication: _TypeAlias = MsgStakeApplication  # noqa: Y015

@_typing.final
class MsgStakeApplicationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgStakeApplicationResponse: _TypeAlias = MsgStakeApplicationResponse  # noqa: Y015

@_typing.final
class MsgUnstakeApplication(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    address: _builtins.str
    def __init__(
        self,
        *,
        address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgUnstakeApplication: _TypeAlias = MsgUnstakeApplication  # noqa: Y015

@_typing.final
class MsgUnstakeApplicationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUnstakeApplicationResponse: _TypeAlias = MsgUnstakeApplicationResponse  # noqa: Y015

@_typing.final
class MsgDelegateToGateway(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    APP_ADDRESS_FIELD_NUMBER: _builtins.int
    GATEWAY_ADDRESS_FIELD_NUMBER: _builtins.int
    app_address: _builtins.str
    """The Bech32 address of the application."""
    gateway_address: _builtins.str
    """The Bech32 address of the gateway the application wants to delegate to."""
    def __init__(
        self,
        *,
        app_address: _builtins.str = ...,
        gateway_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_address", b"app_address", "gateway_address", b"gateway_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgDelegateToGateway: _TypeAlias = MsgDelegateToGateway  # noqa: Y015

@_typing.final
class MsgDelegateToGatewayResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgDelegateToGatewayResponse: _TypeAlias = MsgDelegateToGatewayResponse  # noqa: Y015

@_typing.final
class MsgUndelegateFromGateway(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    APP_ADDRESS_FIELD_NUMBER: _builtins.int
    GATEWAY_ADDRESS_FIELD_NUMBER: _builtins.int
    app_address: _builtins.str
    """The Bech32 address of the application."""
    gateway_address: _builtins.str
    """The Bech32 address of the gateway the application wants to undelegate from."""
    def __init__(
        self,
        *,
        app_address: _builtins.str = ...,
        gateway_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_address", b"app_address", "gateway_address", b"gateway_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgUndelegateFromGateway: _TypeAlias = MsgUndelegateFromGateway  # noqa: Y015

@_typing.final
class MsgUndelegateFromGatewayResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUndelegateFromGatewayResponse: _TypeAlias = MsgUndelegateFromGatewayResponse  # noqa: Y015

@_typing.final
class MsgTransferApplication(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SOURCE_ADDRESS_FIELD_NUMBER: _builtins.int
    DESTINATION_ADDRESS_FIELD_NUMBER: _builtins.int
    source_address: _builtins.str
    destination_address: _builtins.str
    def __init__(
        self,
        *,
        source_address: _builtins.str = ...,
        destination_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["destination_address", b"destination_address", "source_address", b"source_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgTransferApplication: _TypeAlias = MsgTransferApplication  # noqa: Y015

@_typing.final
class MsgTransferApplicationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgTransferApplicationResponse: _TypeAlias = MsgTransferApplicationResponse  # noqa: Y015

@_typing.final
class MsgUpdateParam(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    AS_UINT64_FIELD_NUMBER: _builtins.int
    AS_COIN_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """authority is the address that controls the module (defaults to x/gov unless overwritten)."""
    name: _builtins.str
    as_uint64: _builtins.int
    @_builtins.property
    def as_coin(self) -> _coin_pb2.Coin: ...
    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        name: _builtins.str = ...,
        as_uint64: _builtins.int = ...,
        as_coin: _coin_pb2.Coin | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["asType", b"asType", "as_coin", b"as_coin", "as_uint64", b"as_uint64"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asType", b"asType", "as_coin", b"as_coin", "as_uint64", b"as_uint64", "authority", b"authority", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_asType: _TypeAlias = _typing.Literal["as_uint64", "as_coin"]  # noqa: Y015
    _WhichOneofArgType_asType: _TypeAlias = _typing.Literal["asType", b"asType"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_asType) -> _WhichOneofReturnType_asType | None: ...

Global___MsgUpdateParam: _TypeAlias = MsgUpdateParam  # noqa: Y015

@_typing.final
class MsgUpdateParamResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUpdateParamResponse: _TypeAlias = MsgUpdateParamResponse  # noqa: Y015
