"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from poktroll_clients.proto.cosmos.base.v1beta1 import coin_pb2 as _coin_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from poktroll_clients.proto.pocket.shared import service_pb2 as _service_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Application(_message.Message):
    """Application represents the onchain definition and state of an application"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class PendingUndelegationsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___UndelegatingGatewayList: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___UndelegatingGatewayList | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ADDRESS_FIELD_NUMBER: _builtins.int
    STAKE_FIELD_NUMBER: _builtins.int
    SERVICE_CONFIGS_FIELD_NUMBER: _builtins.int
    DELEGATEE_GATEWAY_ADDRESSES_FIELD_NUMBER: _builtins.int
    PENDING_UNDELEGATIONS_FIELD_NUMBER: _builtins.int
    UNSTAKE_SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    PENDING_TRANSFER_FIELD_NUMBER: _builtins.int
    address: _builtins.str
    """Bech32 address of the application"""
    unstake_session_end_height: _builtins.int
    """Session end height when application initiated unstaking (0 if not unstaking)"""
    @_builtins.property
    def stake(self) -> _coin_pb2.Coin:
        """Total amount of staked uPOKT"""

    @_builtins.property
    def service_configs(self) -> _containers.RepeatedCompositeFieldContainer[_service_pb2.ApplicationServiceConfig]:
        """CRITICAL: Must contain EXACTLY ONE service config
        - Enforces a single service configuration per application to prevent over-servicing.
        - Field is repeated for legacy reasons and potential future compatibility.
        - References for rationale:
          - https://github.com/pokt-network/poktroll/pull/750#discussion_r1735025033
          - https://www.notion.so/buildwithgrove/Off-chain-Application-Stake-Tracking-6a8bebb107db4f7f9dc62cbe7ba555f7
        """

    @_builtins.property
    def delegatee_gateway_addresses(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """TODO_MAINNET_MIGRATION(@bryanchriswhite): Rename `delegatee_gateway_addresses` to `gateway_addresses_delegated_to` for better clarity and consistency.
        - Update all related configs, comments, variables, and function names throughout the codebase to reflect this change.
        - This field is a non-nullable list of Bech32-encoded delegatee Gateway addresses.
        """

    @_builtins.property
    def pending_undelegations(self) -> _containers.MessageMap[_builtins.int, Global___UndelegatingGatewayList]:
        """Mapping of session end heights to gateways being undelegated from
        - Key: Height of the last block of the session when the undelegation transaction was committed
        - Value: List of gateways being undelegated from at that session end height
        TODO_DOCUMENT(@red-0ne): Document the complete flow and rationale behind this mapping.
        - Ensure the documentation explains why tracking pending undelegations by session end height is necessary.
        - See: https://github.com/pokt-network/poktroll/issues/476#issuecomment-2052639906 for context and examples.
        """

    @_builtins.property
    def pending_transfer(self) -> Global___PendingApplicationTransfer:
        """Information about pending application transfers"""

    def __init__(
        self,
        *,
        address: _builtins.str = ...,
        stake: _coin_pb2.Coin | None = ...,
        service_configs: _abc.Iterable[_service_pb2.ApplicationServiceConfig] | None = ...,
        delegatee_gateway_addresses: _abc.Iterable[_builtins.str] | None = ...,
        pending_undelegations: _abc.Mapping[_builtins.int, Global___UndelegatingGatewayList] | None = ...,
        unstake_session_end_height: _builtins.int = ...,
        pending_transfer: Global___PendingApplicationTransfer | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pending_transfer", b"pending_transfer", "stake", b"stake"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "delegatee_gateway_addresses", b"delegatee_gateway_addresses", "pending_transfer", b"pending_transfer", "pending_undelegations", b"pending_undelegations", "service_configs", b"service_configs", "stake", b"stake", "unstake_session_end_height", b"unstake_session_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Application: _TypeAlias = Application  # noqa: Y015

@_typing.final
class UndelegatingGatewayList(_message.Message):
    """UndelegatingGatewayList is used as the Value of `pending_undelegations`.
    It is required to store a repeated list of strings as a map value.
    """

    DESCRIPTOR: _descriptor.Descriptor

    GATEWAY_ADDRESSES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def gateway_addresses(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        gateway_addresses: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gateway_addresses", b"gateway_addresses"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UndelegatingGatewayList: _TypeAlias = UndelegatingGatewayList  # noqa: Y015

@_typing.final
class PendingApplicationTransfer(_message.Message):
    """PendingTransfer is used to store the details of a pending transfer.
    It is only intended to be used inside of an Application object.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DESTINATION_ADDRESS_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    destination_address: _builtins.str
    session_end_height: _builtins.int
    def __init__(
        self,
        *,
        destination_address: _builtins.str = ...,
        session_end_height: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["destination_address", b"destination_address", "session_end_height", b"session_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PendingApplicationTransfer: _TypeAlias = PendingApplicationTransfer  # noqa: Y015

@_typing.final
class PendingUndelegation(_message.Message):
    """Undelegation represents a connection between an application and a gateway that
    is in the process of being removed.

    This record is stored in the undelegation index
    and used to track and process pending undelegations after the unbonding period has elapsed.
    """

    DESCRIPTOR: _descriptor.Descriptor

    APPLICATION_ADDRESS_FIELD_NUMBER: _builtins.int
    GATEWAY_ADDRESS_FIELD_NUMBER: _builtins.int
    application_address: _builtins.str
    """Address of the application that is undelegating from the gateway."""
    gateway_address: _builtins.str
    """Address of the gateway that the application is undelegating from."""
    def __init__(
        self,
        *,
        application_address: _builtins.str = ...,
        gateway_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application_address", b"application_address", "gateway_address", b"gateway_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PendingUndelegation: _TypeAlias = PendingUndelegation  # noqa: Y015
