"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class EventRelayMiningDifficultyUpdated(_message.Message):
    """EventRelayMiningDifficultyUpdated is an event emitted whenever the relay mining difficulty is updated
    for a given service.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SERVICE_ID_FIELD_NUMBER: _builtins.int
    PREV_TARGET_HASH_HEX_ENCODED_FIELD_NUMBER: _builtins.int
    NEW_TARGET_HASH_HEX_ENCODED_FIELD_NUMBER: _builtins.int
    PREV_NUM_RELAYS_EMA_FIELD_NUMBER: _builtins.int
    NEW_NUM_RELAYS_EMA_FIELD_NUMBER: _builtins.int
    service_id: _builtins.str
    prev_target_hash_hex_encoded: _builtins.str
    new_target_hash_hex_encoded: _builtins.str
    prev_num_relays_ema: _builtins.int
    new_num_relays_ema: _builtins.int
    def __init__(
        self,
        *,
        service_id: _builtins.str = ...,
        prev_target_hash_hex_encoded: _builtins.str = ...,
        new_target_hash_hex_encoded: _builtins.str = ...,
        prev_num_relays_ema: _builtins.int = ...,
        new_num_relays_ema: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["new_num_relays_ema", b"new_num_relays_ema", "new_target_hash_hex_encoded", b"new_target_hash_hex_encoded", "prev_num_relays_ema", b"prev_num_relays_ema", "prev_target_hash_hex_encoded", b"prev_target_hash_hex_encoded", "service_id", b"service_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventRelayMiningDifficultyUpdated: _TypeAlias = EventRelayMiningDifficultyUpdated  # noqa: Y015
