"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from poktroll_clients.proto.cosmos.base.v1beta1 import coin_pb2 as _coin_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Params(_message.Message):
    """Params defines the parameters for the module."""

    DESCRIPTOR: _descriptor.Descriptor

    ADD_SERVICE_FEE_FIELD_NUMBER: _builtins.int
    TARGET_NUM_RELAYS_FIELD_NUMBER: _builtins.int
    target_num_relays: _builtins.int
    """target_num_relays is the target for the EMA of the number of relays per session.
    Per service, onchain relay mining difficulty will be adjusted to maintain this target.
    """
    @_builtins.property
    def add_service_fee(self) -> _coin_pb2.Coin:
        """The amount of uPOKT required to add a new service.
        This will be deducted from the signer's account balance,
        and transferred to the pocket network foundation.
        """

    def __init__(
        self,
        *,
        add_service_fee: _coin_pb2.Coin | None = ...,
        target_num_relays: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["add_service_fee", b"add_service_fee"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["add_service_fee", b"add_service_fee", "target_num_relays", b"target_num_relays"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Params: _TypeAlias = Params  # noqa: Y015
