"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from poktroll_clients.proto.cosmos.base.query.v1beta1 import pagination_pb2 as _pagination_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from poktroll_clients.proto.pocket.service import params_pb2 as _params_pb2
from poktroll_clients.proto.pocket.service import relay_mining_difficulty_pb2 as _relay_mining_difficulty_pb2
from poktroll_clients.proto.pocket.shared import service_pb2 as _service_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class QueryParamsRequest(_message.Message):
    """QueryParamsRequest is request type for the Query/Params RPC method."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___QueryParamsRequest: _TypeAlias = QueryParamsRequest  # noqa: Y015

@_typing.final
class QueryParamsResponse(_message.Message):
    """QueryParamsResponse is response type for the Query/Params RPC method."""

    DESCRIPTOR: _descriptor.Descriptor

    PARAMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def params(self) -> _params_pb2.Params:
        """params holds all the parameters of this module."""

    def __init__(
        self,
        *,
        params: _params_pb2.Params | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryParamsResponse: _TypeAlias = QueryParamsResponse  # noqa: Y015

@_typing.final
class QueryGetServiceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    DEHYDRATED_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """TODO_IMPROVE: We could support getting services by name."""
    dehydrated: _builtins.bool
    """if false (default), include full service data including metadata.
    if true, exclude metadata to reduce payload size.
    For backwards compatibility and typical use cases, the default is false.
    """
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        dehydrated: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dehydrated", b"dehydrated", "id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryGetServiceRequest: _TypeAlias = QueryGetServiceRequest  # noqa: Y015

@_typing.final
class QueryGetServiceResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVICE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def service(self) -> _service_pb2.Service: ...
    def __init__(
        self,
        *,
        service: _service_pb2.Service | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["service", b"service"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["service", b"service"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryGetServiceResponse: _TypeAlias = QueryGetServiceResponse  # noqa: Y015

@_typing.final
class QueryAllServicesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PAGINATION_FIELD_NUMBER: _builtins.int
    DEHYDRATED_FIELD_NUMBER: _builtins.int
    dehydrated: _builtins.bool
    """if false, include full service data including metadata.
    if true (default behavior), exclude metadata to reduce payload size.
    For backwards compatibility and performance, the default is true.
    """
    @_builtins.property
    def pagination(self) -> _pagination_pb2.PageRequest: ...
    def __init__(
        self,
        *,
        pagination: _pagination_pb2.PageRequest | None = ...,
        dehydrated: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dehydrated", b"dehydrated", "pagination", b"pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryAllServicesRequest: _TypeAlias = QueryAllServicesRequest  # noqa: Y015

@_typing.final
class QueryAllServicesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVICE_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def service(self) -> _containers.RepeatedCompositeFieldContainer[_service_pb2.Service]: ...
    @_builtins.property
    def pagination(self) -> _pagination_pb2.PageResponse: ...
    def __init__(
        self,
        *,
        service: _abc.Iterable[_service_pb2.Service] | None = ...,
        pagination: _pagination_pb2.PageResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "service", b"service"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryAllServicesResponse: _TypeAlias = QueryAllServicesResponse  # noqa: Y015

@_typing.final
class QueryGetRelayMiningDifficultyRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVICEID_FIELD_NUMBER: _builtins.int
    serviceId: _builtins.str
    def __init__(
        self,
        *,
        serviceId: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["serviceId", b"serviceId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryGetRelayMiningDifficultyRequest: _TypeAlias = QueryGetRelayMiningDifficultyRequest  # noqa: Y015

@_typing.final
class QueryGetRelayMiningDifficultyResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RELAYMININGDIFFICULTY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def relayMiningDifficulty(self) -> _relay_mining_difficulty_pb2.RelayMiningDifficulty: ...
    def __init__(
        self,
        *,
        relayMiningDifficulty: _relay_mining_difficulty_pb2.RelayMiningDifficulty | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["relayMiningDifficulty", b"relayMiningDifficulty"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["relayMiningDifficulty", b"relayMiningDifficulty"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryGetRelayMiningDifficultyResponse: _TypeAlias = QueryGetRelayMiningDifficultyResponse  # noqa: Y015

@_typing.final
class QueryAllRelayMiningDifficultyRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pagination(self) -> _pagination_pb2.PageRequest: ...
    def __init__(
        self,
        *,
        pagination: _pagination_pb2.PageRequest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryAllRelayMiningDifficultyRequest: _TypeAlias = QueryAllRelayMiningDifficultyRequest  # noqa: Y015

@_typing.final
class QueryAllRelayMiningDifficultyResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RELAYMININGDIFFICULTY_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def relayMiningDifficulty(self) -> _containers.RepeatedCompositeFieldContainer[_relay_mining_difficulty_pb2.RelayMiningDifficulty]: ...
    @_builtins.property
    def pagination(self) -> _pagination_pb2.PageResponse: ...
    def __init__(
        self,
        *,
        relayMiningDifficulty: _abc.Iterable[_relay_mining_difficulty_pb2.RelayMiningDifficulty] | None = ...,
        pagination: _pagination_pb2.PageResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "relayMiningDifficulty", b"relayMiningDifficulty"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryAllRelayMiningDifficultyResponse: _TypeAlias = QueryAllRelayMiningDifficultyResponse  # noqa: Y015

@_typing.final
class QueryGetRelayMiningDifficultyAtHeightRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVICEID_FIELD_NUMBER: _builtins.int
    BLOCKHEIGHT_FIELD_NUMBER: _builtins.int
    serviceId: _builtins.str
    blockHeight: _builtins.int
    def __init__(
        self,
        *,
        serviceId: _builtins.str = ...,
        blockHeight: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blockHeight", b"blockHeight", "serviceId", b"serviceId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryGetRelayMiningDifficultyAtHeightRequest: _TypeAlias = QueryGetRelayMiningDifficultyAtHeightRequest  # noqa: Y015

@_typing.final
class QueryGetRelayMiningDifficultyAtHeightResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RELAYMININGDIFFICULTY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def relayMiningDifficulty(self) -> _relay_mining_difficulty_pb2.RelayMiningDifficulty: ...
    def __init__(
        self,
        *,
        relayMiningDifficulty: _relay_mining_difficulty_pb2.RelayMiningDifficulty | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["relayMiningDifficulty", b"relayMiningDifficulty"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["relayMiningDifficulty", b"relayMiningDifficulty"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryGetRelayMiningDifficultyAtHeightResponse: _TypeAlias = QueryGetRelayMiningDifficultyAtHeightResponse  # noqa: Y015

@_typing.final
class QueryRelayMiningDifficultyHistoryRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERVICEID_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    serviceId: _builtins.str
    @_builtins.property
    def pagination(self) -> _pagination_pb2.PageRequest: ...
    def __init__(
        self,
        *,
        serviceId: _builtins.str = ...,
        pagination: _pagination_pb2.PageRequest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "serviceId", b"serviceId"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryRelayMiningDifficultyHistoryRequest: _TypeAlias = QueryRelayMiningDifficultyHistoryRequest  # noqa: Y015

@_typing.final
class QueryRelayMiningDifficultyHistoryResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RELAYMININGDIFFICULTYHISTORY_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def relayMiningDifficultyHistory(self) -> _containers.RepeatedCompositeFieldContainer[_relay_mining_difficulty_pb2.RelayMiningDifficultyUpdate]: ...
    @_builtins.property
    def pagination(self) -> _pagination_pb2.PageResponse: ...
    def __init__(
        self,
        *,
        relayMiningDifficultyHistory: _abc.Iterable[_relay_mining_difficulty_pb2.RelayMiningDifficultyUpdate] | None = ...,
        pagination: _pagination_pb2.PageResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "relayMiningDifficultyHistory", b"relayMiningDifficultyHistory"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryRelayMiningDifficultyHistoryResponse: _TypeAlias = QueryRelayMiningDifficultyHistoryResponse  # noqa: Y015
