"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from poktroll_clients.proto.pocket.session import types_pb2 as _types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Relay(_message.Message):
    """Relay message

    - Contains both the RelayRequest (signed by the Application) and RelayResponse (signed by the Supplier).
    - The serialized tuple is stored in SMST leaves as values during the Claim/Proof lifecycle.
    """

    DESCRIPTOR: _descriptor.Descriptor

    REQ_FIELD_NUMBER: _builtins.int
    RES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def req(self) -> Global___RelayRequest: ...
    @_builtins.property
    def res(self) -> Global___RelayResponse: ...
    def __init__(
        self,
        *,
        req: Global___RelayRequest | None = ...,
        res: Global___RelayResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["req", b"req", "res", b"res"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["req", b"req", "res", b"res"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Relay: _TypeAlias = Relay  # noqa: Y015

@_typing.final
class RelayRequestMetadata(_message.Message):
    """RelayRequestMetadata

    Contains metadata for a RelayRequest.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_HEADER_FIELD_NUMBER: _builtins.int
    SIGNATURE_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    signature: _builtins.bytes
    """Signature for the request:
    - Serialized ring signature, created by either the application itself or a delegated gateway.
    - Always uses the application's ring.
    """
    supplier_operator_address: _builtins.str
    """TODO_MAINNET: Ensure this address is checked/verified onchain if needed.
    See: https://github.com/pokt-network/poktroll/pull/567#discussion_r1628722168

    Supplier operator address:
    - The Bech32 address of the supplier operator the relay is sent to.
    - Used by the RelayMiner to route to the correct supplier.
    """
    @_builtins.property
    def session_header(self) -> _types_pb2.SessionHeader:
        """Session header associated with the relay."""

    def __init__(
        self,
        *,
        session_header: _types_pb2.SessionHeader | None = ...,
        signature: _builtins.bytes = ...,
        supplier_operator_address: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["session_header", b"session_header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["session_header", b"session_header", "signature", b"signature", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RelayRequestMetadata: _TypeAlias = RelayRequestMetadata  # noqa: Y015

@_typing.final
class RelayRequest(_message.Message):
    """RelayRequest

    Holds the request details for a relay.
    """

    DESCRIPTOR: _descriptor.Descriptor

    META_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    payload: _builtins.bytes
    """Serialized request payload:
    - Passed directly to the service.
    - Can be any supported format: JSON-RPC, REST, gRPC, etc.
    """
    @_builtins.property
    def meta(self) -> Global___RelayRequestMetadata: ...
    def __init__(
        self,
        *,
        meta: Global___RelayRequestMetadata | None = ...,
        payload: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["meta", b"meta"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["meta", b"meta", "payload", b"payload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RelayRequest: _TypeAlias = RelayRequest  # noqa: Y015

@_typing.final
class RelayResponse(_message.Message):
    """RelayResponse

    Contains the response details for a RelayRequest.
    Next index: 5
    """

    DESCRIPTOR: _descriptor.Descriptor

    META_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    PAYLOAD_HASH_FIELD_NUMBER: _builtins.int
    RELAY_MINER_ERROR_FIELD_NUMBER: _builtins.int
    payload: _builtins.bytes
    """Serialized response payload:
    - Passed directly from the service.
    - Can be any supported format: JSON-RPC, REST, gRPC, etc.
    - Used when communicating between applications, gatewways, and relayminers
    - Omitted when inserting relays into the SMST, and therefore in onchain proofs,
      in order to minimize onchain proof size.
    """
    payload_hash: _builtins.bytes
    """SHA256 hash of the response payload.
    This field is used for proof verification without requiring the full payload.
    The hash ensures response integrity while reducing on-chain storage requirements.
    """
    @_builtins.property
    def meta(self) -> Global___RelayResponseMetadata: ...
    @_builtins.property
    def relay_miner_error(self) -> Global___RelayMinerError:
        """Error returned by the RelayMiner, if applicable.
        - If no error occurred, this field is empty.
        """

    def __init__(
        self,
        *,
        meta: Global___RelayResponseMetadata | None = ...,
        payload: _builtins.bytes = ...,
        payload_hash: _builtins.bytes = ...,
        relay_miner_error: Global___RelayMinerError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["meta", b"meta", "relay_miner_error", b"relay_miner_error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["meta", b"meta", "payload", b"payload", "payload_hash", b"payload_hash", "relay_miner_error", b"relay_miner_error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RelayResponse: _TypeAlias = RelayResponse  # noqa: Y015

@_typing.final
class RelayResponseMetadata(_message.Message):
    """RelayResponseMetadata

    Contains metadata for a RelayResponse.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_HEADER_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_SIGNATURE_FIELD_NUMBER: _builtins.int
    supplier_operator_signature: _builtins.bytes
    """Signature of the supplier's operator on the response."""
    @_builtins.property
    def session_header(self) -> _types_pb2.SessionHeader:
        """Session header associated with the relay."""

    def __init__(
        self,
        *,
        session_header: _types_pb2.SessionHeader | None = ...,
        supplier_operator_signature: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["session_header", b"session_header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["session_header", b"session_header", "supplier_operator_signature", b"supplier_operator_signature"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RelayResponseMetadata: _TypeAlias = RelayResponseMetadata  # noqa: Y015

@_typing.final
class RelayMinerError(_message.Message):
    """RelayMinerError

    Contains error details returned by the RelayMiner.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CODESPACE_FIELD_NUMBER: _builtins.int
    CODE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    codespace: _builtins.str
    """Registered codespace for the error (groups errors by source/module, e.g. `relayer_proxy`).
    See: https://github.com/pokt-network/poktroll/blob/main/pkg/relayer/proxy/errors.go#L8
    """
    code: _builtins.int
    """Specific registered error code (e.g. `1` for `ErrRelayerProxyInvalidSession`)
    See: https://github.com/pokt-network/poktroll/blob/main/pkg/relayer/proxy/errors.go#L9
    """
    description: _builtins.str
    """Human-readable, concise error description.
    Example `invalid session in relayer request` for `ErrRelayerProxyInvalidSession`.
    """
    message: _builtins.str
    """Detailed error message (may include additional context).
    Example: ErrRelayerProxyInvalidSession.Wrapf("application %q has %d service configs", ...)
    """
    def __init__(
        self,
        *,
        codespace: _builtins.str = ...,
        code: _builtins.int = ...,
        description: _builtins.str = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "codespace", b"codespace", "description", b"description", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RelayMinerError: _TypeAlias = RelayMinerError  # noqa: Y015
