"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RelayMiningDifficulty(_message.Message):
    """RelayMiningDifficulty is a message used to store the onchain Relay Mining
    difficulty associated with a specific service ID.
    TODO_TECHDEBT: Embed this message in the Service message.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SERVICE_ID_FIELD_NUMBER: _builtins.int
    BLOCK_HEIGHT_FIELD_NUMBER: _builtins.int
    NUM_RELAYS_EMA_FIELD_NUMBER: _builtins.int
    TARGET_HASH_FIELD_NUMBER: _builtins.int
    service_id: _builtins.str
    """The service ID the relay mining difficulty is associated with."""
    block_height: _builtins.int
    """The block height at which this relay mining difficulty was computed.
    This is needed to determine how much time has passed since the last time
    the exponential moving average was computed.
    """
    num_relays_ema: _builtins.int
    """The exponential moving average of the number of relays for this service."""
    target_hash: _builtins.bytes
    """The target hash determining the difficulty to mine relays for this service.
    For example, if we use sha256 to hash the (RelayRequest,ReqlayResponse) tuple,
    and the difficulty has 4 leading zero bits, then the target hash would be:
    0b0000111... (until 32 bytes are filled up).
    """
    def __init__(
        self,
        *,
        service_id: _builtins.str = ...,
        block_height: _builtins.int = ...,
        num_relays_ema: _builtins.int = ...,
        target_hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["block_height", b"block_height", "num_relays_ema", b"num_relays_ema", "service_id", b"service_id", "target_hash", b"target_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RelayMiningDifficulty: _TypeAlias = RelayMiningDifficulty  # noqa: Y015

@_typing.final
class RelayMiningDifficultyUpdate(_message.Message):
    """RelayMiningDifficultyUpdate stores a snapshot of relay mining difficulty
    along with the height at which it became effective.
    This enables historical lookups of difficulty that was active during a session.
    """

    DESCRIPTOR: _descriptor.Descriptor

    EFFECTIVE_HEIGHT_FIELD_NUMBER: _builtins.int
    DIFFICULTY_FIELD_NUMBER: _builtins.int
    effective_height: _builtins.int
    """effective_height is the block height at which this difficulty became effective.
    Difficulty changes are activated at session boundaries, not immediately.
    """
    @_builtins.property
    def difficulty(self) -> Global___RelayMiningDifficulty:
        """difficulty is the snapshot of relay mining difficulty effective at this height."""

    def __init__(
        self,
        *,
        effective_height: _builtins.int = ...,
        difficulty: Global___RelayMiningDifficulty | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["difficulty", b"difficulty"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["difficulty", b"difficulty", "effective_height", b"effective_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RelayMiningDifficultyUpdate: _TypeAlias = RelayMiningDifficultyUpdate  # noqa: Y015
