"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from poktroll_clients.proto.cosmos.base.v1beta1 import coin_pb2 as _coin_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from poktroll_clients.proto.pocket.service import params_pb2 as _params_pb2
from poktroll_clients.proto.pocket.shared import service_pb2 as _service_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MsgUpdateParams(_message.Message):
    """MsgUpdateParams is the Msg/UpdateParams request type."""

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    PARAMS_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """authority is the address that controls the module (defaults to x/gov unless overwritten)."""
    @_builtins.property
    def params(self) -> _params_pb2.Params:
        """params defines the x/service parameters to update.
        NOTE: All parameters must be supplied.
        """

    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        params: _params_pb2.Params | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authority", b"authority", "params", b"params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgUpdateParams: _TypeAlias = MsgUpdateParams  # noqa: Y015

@_typing.final
class MsgUpdateParamsResponse(_message.Message):
    """MsgUpdateParamsResponse defines the response structure for executing a
    MsgUpdateParams message.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUpdateParamsResponse: _TypeAlias = MsgUpdateParamsResponse  # noqa: Y015

@_typing.final
class MsgUpdateParam(_message.Message):
    """MsgUpdateParam is the Msg/UpdateParam request type to update a single param."""

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    AS_COIN_FIELD_NUMBER: _builtins.int
    AS_UINT64_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """authority is the address that controls the module (defaults to x/gov unless overwritten)."""
    name: _builtins.str
    """The (name, as_type) tuple must match the corresponding name and type as
    specified in the `Params` message in `proof/params.proto.`
    """
    as_uint64: _builtins.int
    @_builtins.property
    def as_coin(self) -> _coin_pb2.Coin: ...
    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        name: _builtins.str = ...,
        as_coin: _coin_pb2.Coin | None = ...,
        as_uint64: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["as_coin", b"as_coin", "as_type", b"as_type", "as_uint64", b"as_uint64"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["as_coin", b"as_coin", "as_type", b"as_type", "as_uint64", b"as_uint64", "authority", b"authority", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_as_type: _TypeAlias = _typing.Literal["as_coin", "as_uint64"]  # noqa: Y015
    _WhichOneofArgType_as_type: _TypeAlias = _typing.Literal["as_type", b"as_type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_as_type) -> _WhichOneofReturnType_as_type | None: ...

Global___MsgUpdateParam: _TypeAlias = MsgUpdateParam  # noqa: Y015

@_typing.final
class MsgUpdateParamResponse(_message.Message):
    """MsgUpdateParamResponse defines the response structure for executing a
    MsgUpdateParam message after a single param update.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUpdateParamResponse: _TypeAlias = MsgUpdateParamResponse  # noqa: Y015

@_typing.final
class MsgAddService(_message.Message):
    """MsgAddService defines a message for adding a new message to the network.
    Services can be added by any actor in the network making them truly
    permissionless.
    """

    DESCRIPTOR: _descriptor.Descriptor

    OWNER_ADDRESS_FIELD_NUMBER: _builtins.int
    SERVICE_FIELD_NUMBER: _builtins.int
    owner_address: _builtins.str
    """The Bech32 address of the service owner."""
    @_builtins.property
    def service(self) -> _service_pb2.Service:
        """The Service being added to the network, including optional experimental metadata"""

    def __init__(
        self,
        *,
        owner_address: _builtins.str = ...,
        service: _service_pb2.Service | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["service", b"service"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["owner_address", b"owner_address", "service", b"service"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgAddService: _TypeAlias = MsgAddService  # noqa: Y015

@_typing.final
class MsgAddServiceResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgAddServiceResponse: _TypeAlias = MsgAddServiceResponse  # noqa: Y015
