"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class EventClaimCreated(_message.Message):
    """Next index: 13"""

    DESCRIPTOR: _descriptor.Descriptor

    NUM_RELAYS_FIELD_NUMBER: _builtins.int
    NUM_CLAIMED_COMPUTE_UNITS_FIELD_NUMBER: _builtins.int
    NUM_ESTIMATED_COMPUTE_UNITS_FIELD_NUMBER: _builtins.int
    CLAIMED_UPOKT_FIELD_NUMBER: _builtins.int
    SERVICE_ID_FIELD_NUMBER: _builtins.int
    APPLICATION_ADDRESS_FIELD_NUMBER: _builtins.int
    SESSION_END_BLOCK_HEIGHT_FIELD_NUMBER: _builtins.int
    CLAIM_PROOF_STATUS_INT_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    num_relays: _builtins.int
    num_claimed_compute_units: _builtins.int
    num_estimated_compute_units: _builtins.int
    claimed_upokt: _builtins.str
    service_id: _builtins.str
    """The Service ID to which the claim corresponds."""
    application_address: _builtins.str
    """The address of the application which participated in the claimed session."""
    session_end_block_height: _builtins.int
    """The end block height of the session to which the claim corresponds."""
    claim_proof_status_int: _builtins.int
    """The validation status of the claim.
    DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
    enum to minimize onchain disk utilization. This is necessary because event
    data is not always protobuf-encoded in the various places and formats that it
    appears in onchain leveldb databases.
    Enum values:
      PENDING_VALIDATION = 0;
      VALIDATED = 1;
      INVALID = 2;
    """
    supplier_operator_address: _builtins.str
    """The operator address of the supplier which submitted the claim."""
    def __init__(
        self,
        *,
        num_relays: _builtins.int = ...,
        num_claimed_compute_units: _builtins.int = ...,
        num_estimated_compute_units: _builtins.int = ...,
        claimed_upokt: _builtins.str = ...,
        service_id: _builtins.str = ...,
        application_address: _builtins.str = ...,
        session_end_block_height: _builtins.int = ...,
        claim_proof_status_int: _builtins.int = ...,
        supplier_operator_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application_address", b"application_address", "claim_proof_status_int", b"claim_proof_status_int", "claimed_upokt", b"claimed_upokt", "num_claimed_compute_units", b"num_claimed_compute_units", "num_estimated_compute_units", b"num_estimated_compute_units", "num_relays", b"num_relays", "service_id", b"service_id", "session_end_block_height", b"session_end_block_height", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventClaimCreated: _TypeAlias = EventClaimCreated  # noqa: Y015

@_typing.final
class EventClaimUpdated(_message.Message):
    """TODO_TEST: Add coverage for claim updates.
    Next index: 13
    """

    DESCRIPTOR: _descriptor.Descriptor

    NUM_RELAYS_FIELD_NUMBER: _builtins.int
    NUM_CLAIMED_COMPUTE_UNITS_FIELD_NUMBER: _builtins.int
    NUM_ESTIMATED_COMPUTE_UNITS_FIELD_NUMBER: _builtins.int
    CLAIMED_UPOKT_FIELD_NUMBER: _builtins.int
    SERVICE_ID_FIELD_NUMBER: _builtins.int
    APPLICATION_ADDRESS_FIELD_NUMBER: _builtins.int
    SESSION_END_BLOCK_HEIGHT_FIELD_NUMBER: _builtins.int
    CLAIM_PROOF_STATUS_INT_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    num_relays: _builtins.int
    num_claimed_compute_units: _builtins.int
    num_estimated_compute_units: _builtins.int
    claimed_upokt: _builtins.str
    service_id: _builtins.str
    """The Service ID to which the claim corresponds."""
    application_address: _builtins.str
    """The address of the application which participated in the claimed session."""
    session_end_block_height: _builtins.int
    """The end block height of the session to which the claim corresponds."""
    claim_proof_status_int: _builtins.int
    """The validation status of the claim.
    DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
    enum to minimize onchain disk utilization. This is necessary because event
    data is not always protobuf-encoded in the various places and formats that it
    appears in onchain leveldb databases.
    Enum values:
      PENDING_VALIDATION = 0;
      VALIDATED = 1;
      INVALID = 2;
    """
    supplier_operator_address: _builtins.str
    """The operator address of the supplier which updated the claim."""
    def __init__(
        self,
        *,
        num_relays: _builtins.int = ...,
        num_claimed_compute_units: _builtins.int = ...,
        num_estimated_compute_units: _builtins.int = ...,
        claimed_upokt: _builtins.str = ...,
        service_id: _builtins.str = ...,
        application_address: _builtins.str = ...,
        session_end_block_height: _builtins.int = ...,
        claim_proof_status_int: _builtins.int = ...,
        supplier_operator_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application_address", b"application_address", "claim_proof_status_int", b"claim_proof_status_int", "claimed_upokt", b"claimed_upokt", "num_claimed_compute_units", b"num_claimed_compute_units", "num_estimated_compute_units", b"num_estimated_compute_units", "num_relays", b"num_relays", "service_id", b"service_id", "session_end_block_height", b"session_end_block_height", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventClaimUpdated: _TypeAlias = EventClaimUpdated  # noqa: Y015

@_typing.final
class EventProofSubmitted(_message.Message):
    """Next index: 13"""

    DESCRIPTOR: _descriptor.Descriptor

    NUM_RELAYS_FIELD_NUMBER: _builtins.int
    NUM_CLAIMED_COMPUTE_UNITS_FIELD_NUMBER: _builtins.int
    NUM_ESTIMATED_COMPUTE_UNITS_FIELD_NUMBER: _builtins.int
    CLAIMED_UPOKT_FIELD_NUMBER: _builtins.int
    SERVICE_ID_FIELD_NUMBER: _builtins.int
    APPLICATION_ADDRESS_FIELD_NUMBER: _builtins.int
    SESSION_END_BLOCK_HEIGHT_FIELD_NUMBER: _builtins.int
    CLAIM_PROOF_STATUS_INT_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    num_relays: _builtins.int
    num_claimed_compute_units: _builtins.int
    num_estimated_compute_units: _builtins.int
    claimed_upokt: _builtins.str
    service_id: _builtins.str
    """The Service ID to which the claim corresponds."""
    application_address: _builtins.str
    """The address of the application which participated in the claimed session."""
    session_end_block_height: _builtins.int
    """The end block height of the session to which the claim corresponds."""
    claim_proof_status_int: _builtins.int
    """The validation status of the claim.
    DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
    enum to minimize onchain disk utilization. This is necessary because event
    data is not always protobuf-encoded in the various places and formats that it
    appears in onchain leveldb databases.
    Enum values:
      PENDING_VALIDATION = 0;
      VALIDATED = 1;
      INVALID = 2;
    """
    supplier_operator_address: _builtins.str
    """The operator address of the supplier which submitted the proof."""
    def __init__(
        self,
        *,
        num_relays: _builtins.int = ...,
        num_claimed_compute_units: _builtins.int = ...,
        num_estimated_compute_units: _builtins.int = ...,
        claimed_upokt: _builtins.str = ...,
        service_id: _builtins.str = ...,
        application_address: _builtins.str = ...,
        session_end_block_height: _builtins.int = ...,
        claim_proof_status_int: _builtins.int = ...,
        supplier_operator_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application_address", b"application_address", "claim_proof_status_int", b"claim_proof_status_int", "claimed_upokt", b"claimed_upokt", "num_claimed_compute_units", b"num_claimed_compute_units", "num_estimated_compute_units", b"num_estimated_compute_units", "num_relays", b"num_relays", "service_id", b"service_id", "session_end_block_height", b"session_end_block_height", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventProofSubmitted: _TypeAlias = EventProofSubmitted  # noqa: Y015

@_typing.final
class EventProofUpdated(_message.Message):
    """TODO_TEST: Add coverage for proof updates.
    Next index: 13
    """

    DESCRIPTOR: _descriptor.Descriptor

    NUM_RELAYS_FIELD_NUMBER: _builtins.int
    NUM_CLAIMED_COMPUTE_UNITS_FIELD_NUMBER: _builtins.int
    NUM_ESTIMATED_COMPUTE_UNITS_FIELD_NUMBER: _builtins.int
    CLAIMED_UPOKT_FIELD_NUMBER: _builtins.int
    SERVICE_ID_FIELD_NUMBER: _builtins.int
    APPLICATION_ADDRESS_FIELD_NUMBER: _builtins.int
    SESSION_END_BLOCK_HEIGHT_FIELD_NUMBER: _builtins.int
    CLAIM_PROOF_STATUS_INT_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    num_relays: _builtins.int
    num_claimed_compute_units: _builtins.int
    num_estimated_compute_units: _builtins.int
    claimed_upokt: _builtins.str
    service_id: _builtins.str
    """The Service ID to which the claim corresponds."""
    application_address: _builtins.str
    """The address of the application which participated in the claimed session."""
    session_end_block_height: _builtins.int
    """The end block height of the session to which the claim corresponds."""
    claim_proof_status_int: _builtins.int
    """The validation status of the claim.
    DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
    enum to minimize onchain disk utilization. This is necessary because event
    data is not always protobuf-encoded in the various places and formats that it
    appears in onchain leveldb databases.
    Enum values:
      PENDING_VALIDATION = 0;
      VALIDATED = 1;
      INVALID = 2;
    """
    supplier_operator_address: _builtins.str
    """The operator address of the supplier which updated the proof."""
    def __init__(
        self,
        *,
        num_relays: _builtins.int = ...,
        num_claimed_compute_units: _builtins.int = ...,
        num_estimated_compute_units: _builtins.int = ...,
        claimed_upokt: _builtins.str = ...,
        service_id: _builtins.str = ...,
        application_address: _builtins.str = ...,
        session_end_block_height: _builtins.int = ...,
        claim_proof_status_int: _builtins.int = ...,
        supplier_operator_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application_address", b"application_address", "claim_proof_status_int", b"claim_proof_status_int", "claimed_upokt", b"claimed_upokt", "num_claimed_compute_units", b"num_claimed_compute_units", "num_estimated_compute_units", b"num_estimated_compute_units", "num_relays", b"num_relays", "service_id", b"service_id", "session_end_block_height", b"session_end_block_height", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventProofUpdated: _TypeAlias = EventProofUpdated  # noqa: Y015

@_typing.final
class EventProofValidityChecked(_message.Message):
    """Event emitted after a proof has been checked for validity in the proof module's
    EndBlocker.
    Next index: 12
    """

    DESCRIPTOR: _descriptor.Descriptor

    BLOCK_HEIGHT_FIELD_NUMBER: _builtins.int
    FAILURE_REASON_FIELD_NUMBER: _builtins.int
    SERVICE_ID_FIELD_NUMBER: _builtins.int
    APPLICATION_ADDRESS_FIELD_NUMBER: _builtins.int
    SESSION_END_BLOCK_HEIGHT_FIELD_NUMBER: _builtins.int
    CLAIM_PROOF_STATUS_INT_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    block_height: _builtins.int
    failure_reason: _builtins.str
    """reason is the string representation of the error that led to the proof being
    marked as invalid (e.g. "invalid closest merkle proof", "invalid relay request signature")
    """
    service_id: _builtins.str
    """The Service ID to which the claim corresponds."""
    application_address: _builtins.str
    """The address of the application which participated in the claimed session."""
    session_end_block_height: _builtins.int
    """The end block height of the session to which the claim corresponds."""
    claim_proof_status_int: _builtins.int
    """The validation status of the claim.
    DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
    enum to minimize onchain disk utilization. This is necessary because event
    data is not always protobuf-encoded in the various places and formats that it
    appears in onchain leveldb databases.
    Enum values:
      PENDING_VALIDATION = 0;
      VALIDATED = 1;
      INVALID = 2;
    """
    supplier_operator_address: _builtins.str
    """The operator address of the supplier whose proof was checked."""
    def __init__(
        self,
        *,
        block_height: _builtins.int = ...,
        failure_reason: _builtins.str = ...,
        service_id: _builtins.str = ...,
        application_address: _builtins.str = ...,
        session_end_block_height: _builtins.int = ...,
        claim_proof_status_int: _builtins.int = ...,
        supplier_operator_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application_address", b"application_address", "block_height", b"block_height", "claim_proof_status_int", b"claim_proof_status_int", "failure_reason", b"failure_reason", "service_id", b"service_id", "session_end_block_height", b"session_end_block_height", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventProofValidityChecked: _TypeAlias = EventProofValidityChecked  # noqa: Y015
