"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from poktroll_clients.proto.cosmos.base.query.v1beta1 import pagination_pb2 as _pagination_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from poktroll_clients.proto.pocket.proof import params_pb2 as _params_pb2
from poktroll_clients.proto.pocket.proof import types_pb2 as _types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class QueryParamsRequest(_message.Message):
    """QueryParamsRequest is request type for the Query/Params RPC method."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___QueryParamsRequest: _TypeAlias = QueryParamsRequest  # noqa: Y015

@_typing.final
class QueryParamsResponse(_message.Message):
    """QueryParamsResponse is response type for the Query/Params RPC method."""

    DESCRIPTOR: _descriptor.Descriptor

    PARAMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def params(self) -> _params_pb2.Params:
        """params holds all the parameters of this module."""

    def __init__(
        self,
        *,
        params: _params_pb2.Params | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryParamsResponse: _TypeAlias = QueryParamsResponse  # noqa: Y015

@_typing.final
class QueryGetClaimRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    supplier_operator_address: _builtins.str
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        supplier_operator_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["session_id", b"session_id", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryGetClaimRequest: _TypeAlias = QueryGetClaimRequest  # noqa: Y015

@_typing.final
class QueryGetClaimResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLAIM_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def claim(self) -> _types_pb2.Claim: ...
    def __init__(
        self,
        *,
        claim: _types_pb2.Claim | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["claim", b"claim"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["claim", b"claim"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryGetClaimResponse: _TypeAlias = QueryGetClaimResponse  # noqa: Y015

@_typing.final
class QueryAllClaimsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PAGINATION_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    supplier_operator_address: _builtins.str
    session_id: _builtins.str
    session_end_height: _builtins.int
    @_builtins.property
    def pagination(self) -> _pagination_pb2.PageRequest: ...
    def __init__(
        self,
        *,
        pagination: _pagination_pb2.PageRequest | None = ...,
        supplier_operator_address: _builtins.str = ...,
        session_id: _builtins.str = ...,
        session_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["filter", b"filter", "pagination", b"pagination", "session_end_height", b"session_end_height", "session_id", b"session_id", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filter", b"filter", "pagination", b"pagination", "session_end_height", b"session_end_height", "session_id", b"session_id", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_filter: _TypeAlias = _typing.Literal["supplier_operator_address", "session_id", "session_end_height"]  # noqa: Y015
    _WhichOneofArgType_filter: _TypeAlias = _typing.Literal["filter", b"filter"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_filter) -> _WhichOneofReturnType_filter | None: ...

Global___QueryAllClaimsRequest: _TypeAlias = QueryAllClaimsRequest  # noqa: Y015

@_typing.final
class QueryAllClaimsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLAIMS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def claims(self) -> _containers.RepeatedCompositeFieldContainer[_types_pb2.Claim]: ...
    @_builtins.property
    def pagination(self) -> _pagination_pb2.PageResponse: ...
    def __init__(
        self,
        *,
        claims: _abc.Iterable[_types_pb2.Claim] | None = ...,
        pagination: _pagination_pb2.PageResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["claims", b"claims", "pagination", b"pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryAllClaimsResponse: _TypeAlias = QueryAllClaimsResponse  # noqa: Y015

@_typing.final
class QueryGetProofRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    supplier_operator_address: _builtins.str
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        supplier_operator_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["session_id", b"session_id", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryGetProofRequest: _TypeAlias = QueryGetProofRequest  # noqa: Y015

@_typing.final
class QueryGetProofResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROOF_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def proof(self) -> _types_pb2.Proof: ...
    def __init__(
        self,
        *,
        proof: _types_pb2.Proof | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["proof", b"proof"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["proof", b"proof"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryGetProofResponse: _TypeAlias = QueryGetProofResponse  # noqa: Y015

@_typing.final
class QueryAllProofsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PAGINATION_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    supplier_operator_address: _builtins.str
    session_id: _builtins.str
    session_end_height: _builtins.int
    @_builtins.property
    def pagination(self) -> _pagination_pb2.PageRequest: ...
    def __init__(
        self,
        *,
        pagination: _pagination_pb2.PageRequest | None = ...,
        supplier_operator_address: _builtins.str = ...,
        session_id: _builtins.str = ...,
        session_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["filter", b"filter", "pagination", b"pagination", "session_end_height", b"session_end_height", "session_id", b"session_id", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filter", b"filter", "pagination", b"pagination", "session_end_height", b"session_end_height", "session_id", b"session_id", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_filter: _TypeAlias = _typing.Literal["supplier_operator_address", "session_id", "session_end_height"]  # noqa: Y015
    _WhichOneofArgType_filter: _TypeAlias = _typing.Literal["filter", b"filter"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_filter) -> _WhichOneofReturnType_filter | None: ...

Global___QueryAllProofsRequest: _TypeAlias = QueryAllProofsRequest  # noqa: Y015

@_typing.final
class QueryAllProofsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROOFS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def proofs(self) -> _containers.RepeatedCompositeFieldContainer[_types_pb2.Proof]: ...
    @_builtins.property
    def pagination(self) -> _pagination_pb2.PageResponse: ...
    def __init__(
        self,
        *,
        proofs: _abc.Iterable[_types_pb2.Proof] | None = ...,
        pagination: _pagination_pb2.PageResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "proofs", b"proofs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryAllProofsResponse: _TypeAlias = QueryAllProofsResponse  # noqa: Y015
