"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from poktroll_clients.proto.cosmos.base.v1beta1 import coin_pb2 as _coin_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from poktroll_clients.proto.pocket.proof import params_pb2 as _params_pb2
from poktroll_clients.proto.pocket.session import types_pb2 as _types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MsgUpdateParams(_message.Message):
    """MsgUpdateParams is the Msg/UpdateParams request type to update all params at once."""

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    PARAMS_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """authority is the address that controls the module (defaults to x/gov unless overwritten)."""
    @_builtins.property
    def params(self) -> _params_pb2.Params:
        """TODO_IMPROVE(#322): The requirement to provide all params is adopted from the
        latest Cosmos SDK version. We should look into either improving this ourselves
        or seeing if it is on their roadmap.

        params defines the x/proof parameters to update.
        NOTE: All parameters must be supplied.
        """

    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        params: _params_pb2.Params | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authority", b"authority", "params", b"params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgUpdateParams: _TypeAlias = MsgUpdateParams  # noqa: Y015

@_typing.final
class MsgUpdateParamsResponse(_message.Message):
    """MsgUpdateParamsResponse defines the response structure for executing a
    MsgUpdateParams message.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUpdateParamsResponse: _TypeAlias = MsgUpdateParamsResponse  # noqa: Y015

@_typing.final
class MsgUpdateParam(_message.Message):
    """MsgUpdateParam is the Msg/UpdateParam request type to update a single param."""

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    AS_BYTES_FIELD_NUMBER: _builtins.int
    AS_FLOAT_FIELD_NUMBER: _builtins.int
    AS_COIN_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """authority is the address that controls the module (defaults to x/gov unless overwritten)."""
    name: _builtins.str
    """The (name, as_type) tuple must match the corresponding name and type as
    specified in the `Params`` message in `proof/params.proto.`
    """
    as_bytes: _builtins.bytes
    as_float: _builtins.float
    @_builtins.property
    def as_coin(self) -> _coin_pb2.Coin: ...
    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        name: _builtins.str = ...,
        as_bytes: _builtins.bytes = ...,
        as_float: _builtins.float = ...,
        as_coin: _coin_pb2.Coin | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["as_bytes", b"as_bytes", "as_coin", b"as_coin", "as_float", b"as_float", "as_type", b"as_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["as_bytes", b"as_bytes", "as_coin", b"as_coin", "as_float", b"as_float", "as_type", b"as_type", "authority", b"authority", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_as_type: _TypeAlias = _typing.Literal["as_bytes", "as_float", "as_coin"]  # noqa: Y015
    _WhichOneofArgType_as_type: _TypeAlias = _typing.Literal["as_type", b"as_type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_as_type) -> _WhichOneofReturnType_as_type | None: ...

Global___MsgUpdateParam: _TypeAlias = MsgUpdateParam  # noqa: Y015

@_typing.final
class MsgUpdateParamResponse(_message.Message):
    """MsgUpdateParamResponse defines the response structure for executing a
    MsgUpdateParam message after a single param update.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUpdateParamResponse: _TypeAlias = MsgUpdateParamResponse  # noqa: Y015

@_typing.final
class MsgCreateClaim(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    SESSION_HEADER_FIELD_NUMBER: _builtins.int
    ROOT_HASH_FIELD_NUMBER: _builtins.int
    supplier_operator_address: _builtins.str
    root_hash: _builtins.bytes
    """root returned from smt.SMST#Root()"""
    @_builtins.property
    def session_header(self) -> _types_pb2.SessionHeader: ...
    def __init__(
        self,
        *,
        supplier_operator_address: _builtins.str = ...,
        session_header: _types_pb2.SessionHeader | None = ...,
        root_hash: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["session_header", b"session_header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["root_hash", b"root_hash", "session_header", b"session_header", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgCreateClaim: _TypeAlias = MsgCreateClaim  # noqa: Y015

@_typing.final
class MsgCreateClaimResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgCreateClaimResponse: _TypeAlias = MsgCreateClaimResponse  # noqa: Y015

@_typing.final
class MsgSubmitProof(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    SESSION_HEADER_FIELD_NUMBER: _builtins.int
    PROOF_FIELD_NUMBER: _builtins.int
    supplier_operator_address: _builtins.str
    proof: _builtins.bytes
    """serialized version of *smt.SparseCompactMerkleClosestProof"""
    @_builtins.property
    def session_header(self) -> _types_pb2.SessionHeader: ...
    def __init__(
        self,
        *,
        supplier_operator_address: _builtins.str = ...,
        session_header: _types_pb2.SessionHeader | None = ...,
        proof: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["session_header", b"session_header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["proof", b"proof", "session_header", b"session_header", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgSubmitProof: _TypeAlias = MsgSubmitProof  # noqa: Y015

@_typing.final
class MsgSubmitProofResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgSubmitProofResponse: _TypeAlias = MsgSubmitProofResponse  # noqa: Y015
