"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from poktroll_clients.proto.pocket.session import types_pb2 as _types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _ProofRequirementReason:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ProofRequirementReasonEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ProofRequirementReason.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NOT_REQUIRED: _ProofRequirementReason.ValueType  # 0
    PROBABILISTIC: _ProofRequirementReason.ValueType  # 1
    THRESHOLD: _ProofRequirementReason.ValueType  # 2

class ProofRequirementReason(_ProofRequirementReason, metaclass=_ProofRequirementReasonEnumTypeWrapper): ...

NOT_REQUIRED: ProofRequirementReason.ValueType  # 0
PROBABILISTIC: ProofRequirementReason.ValueType  # 1
THRESHOLD: ProofRequirementReason.ValueType  # 2
Global___ProofRequirementReason: _TypeAlias = ProofRequirementReason  # noqa: Y015

class _ClaimProofStage:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ClaimProofStageEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ClaimProofStage.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CLAIMED: _ClaimProofStage.ValueType  # 0
    PROVEN: _ClaimProofStage.ValueType  # 1
    SETTLED: _ClaimProofStage.ValueType  # 2
    EXPIRED: _ClaimProofStage.ValueType  # 3

class ClaimProofStage(_ClaimProofStage, metaclass=_ClaimProofStageEnumTypeWrapper): ...

CLAIMED: ClaimProofStage.ValueType  # 0
PROVEN: ClaimProofStage.ValueType  # 1
SETTLED: ClaimProofStage.ValueType  # 2
EXPIRED: ClaimProofStage.ValueType  # 3
Global___ClaimProofStage: _TypeAlias = ClaimProofStage  # noqa: Y015

class _ClaimProofStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ClaimProofStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ClaimProofStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PENDING_VALIDATION: _ClaimProofStatus.ValueType  # 0
    VALIDATED: _ClaimProofStatus.ValueType  # 1
    INVALID: _ClaimProofStatus.ValueType  # 2

class ClaimProofStatus(_ClaimProofStatus, metaclass=_ClaimProofStatusEnumTypeWrapper):
    """Status of proof validation for a claim
    Default is PENDING_VALIDATION regardless of proof requirement
    """

PENDING_VALIDATION: ClaimProofStatus.ValueType  # 0
VALIDATED: ClaimProofStatus.ValueType  # 1
INVALID: ClaimProofStatus.ValueType  # 2
Global___ClaimProofStatus: _TypeAlias = ClaimProofStatus  # noqa: Y015

@_typing.final
class Proof(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    SESSION_HEADER_FIELD_NUMBER: _builtins.int
    CLOSEST_MERKLE_PROOF_FIELD_NUMBER: _builtins.int
    supplier_operator_address: _builtins.str
    """Address of the supplier's operator that submitted this proof."""
    closest_merkle_proof: _builtins.bytes
    """The serialized SMST compacted proof from the `#ClosestProof()` method."""
    @_builtins.property
    def session_header(self) -> _types_pb2.SessionHeader:
        """The session header of the session that this claim is for."""

    def __init__(
        self,
        *,
        supplier_operator_address: _builtins.str = ...,
        session_header: _types_pb2.SessionHeader | None = ...,
        closest_merkle_proof: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["session_header", b"session_header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["closest_merkle_proof", b"closest_merkle_proof", "session_header", b"session_header", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Proof: _TypeAlias = Proof  # noqa: Y015

@_typing.final
class Claim(_message.Message):
    """Claim is the serialized object stored onchain for claims pending to be proven"""

    DESCRIPTOR: _descriptor.Descriptor

    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    SESSION_HEADER_FIELD_NUMBER: _builtins.int
    ROOT_HASH_FIELD_NUMBER: _builtins.int
    PROOF_VALIDATION_STATUS_FIELD_NUMBER: _builtins.int
    supplier_operator_address: _builtins.str
    """Address of the supplier's operator that submitted this claim.
    the address of the supplier's operator that submitted this claim
    """
    root_hash: _builtins.bytes
    """Root hash from smt.SMST#Root().
    TODO_UP_NEXT(@bryanchriswhite, #1497): Dehydrate the claim's root hash from onchain events.
    """
    proof_validation_status: Global___ClaimProofStatus.ValueType
    """Important: This field MUST only be set by proofKeeper#EnsureValidProofSignaturesAndClosestPath"""
    @_builtins.property
    def session_header(self) -> _types_pb2.SessionHeader:
        """Session header this claim is for."""

    def __init__(
        self,
        *,
        supplier_operator_address: _builtins.str = ...,
        session_header: _types_pb2.SessionHeader | None = ...,
        root_hash: _builtins.bytes = ...,
        proof_validation_status: Global___ClaimProofStatus.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["session_header", b"session_header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["proof_validation_status", b"proof_validation_status", "root_hash", b"root_hash", "session_header", b"session_header", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Claim: _TypeAlias = Claim  # noqa: Y015

@_typing.final
class SessionSMT(_message.Message):
    """**************
    OFFCHAIN TYPES
    The messages defined below are used for offchain logic and should not be used for any onchain logic.
    They are defined in the same file as the onchain types for convenience.
    **************

    SessionSMT is the serializable session's SMST used to persist the session's
    state offchain by the RelayMiner.
    It is not used for any onchain logic.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_HEADER_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    SMT_ROOT_FIELD_NUMBER: _builtins.int
    supplier_operator_address: _builtins.str
    smt_root: _builtins.bytes
    @_builtins.property
    def session_header(self) -> _types_pb2.SessionHeader: ...
    def __init__(
        self,
        *,
        session_header: _types_pb2.SessionHeader | None = ...,
        supplier_operator_address: _builtins.str = ...,
        smt_root: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["session_header", b"session_header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["session_header", b"session_header", "smt_root", b"smt_root", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SessionSMT: _TypeAlias = SessionSMT  # noqa: Y015
