"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pb2 as _descriptor_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import extension_dict as _extension_dict
import builtins as _builtins

DESCRIPTOR: _descriptor.FileDescriptor

SERVICE_FIELD_NUMBER: _builtins.int
SIGNER_FIELD_NUMBER: _builtins.int
service: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.ServiceOptions, _builtins.bool]
"""service indicates that the service is a Msg service and that requests
must be transported via blockchain transactions rather than gRPC.
Tooling can use this annotation to distinguish between Msg services and
other types of services via reflection.
"""
signer: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _containers.RepeatedScalarFieldContainer[_builtins.str]]
"""signer must be used in cosmos messages in order
to signal to external clients which fields in a
given cosmos message must be filled with signer
information (address).
The field must be the protobuf name of the message
field extended with this MessageOption.
The field must either be of string kind, or of message
kind in case the signer information is contained within
a message inside the cosmos message.
"""
