"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Params(_message.Message):
    """Params defines the parameters for the module."""

    DESCRIPTOR: _descriptor.Descriptor

    NUM_SUPPLIERS_PER_SESSION_FIELD_NUMBER: _builtins.int
    num_suppliers_per_session: _builtins.int
    """num_suppliers_per_session is the maximum number of suppliers per session
    (application:supplier pair for a given session number).
    """
    def __init__(
        self,
        *,
        num_suppliers_per_session: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["num_suppliers_per_session", b"num_suppliers_per_session"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Params: _TypeAlias = Params  # noqa: Y015

@_typing.final
class ParamsUpdate(_message.Message):
    """ParamsUpdate stores a snapshot of session parameters
    along with the height at which they became effective.
    This enables historical parameter lookups for session calculations.
    """

    DESCRIPTOR: _descriptor.Descriptor

    EFFECTIVE_HEIGHT_FIELD_NUMBER: _builtins.int
    PARAMS_FIELD_NUMBER: _builtins.int
    effective_height: _builtins.int
    """effective_height is the block height at which these params became effective.
    Parameters are activated at session boundaries, not immediately upon governance change.
    """
    @_builtins.property
    def params(self) -> Global___Params:
        """params is the snapshot of session params that were effective starting at effective_height."""

    def __init__(
        self,
        *,
        effective_height: _builtins.int = ...,
        params: Global___Params | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["effective_height", b"effective_height", "params", b"params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ParamsUpdate: _TypeAlias = ParamsUpdate  # noqa: Y015
