"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from poktroll_clients.proto.pocket.session import params_pb2 as _params_pb2
from poktroll_clients.proto.pocket.session import types_pb2 as _types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class QueryParamsRequest(_message.Message):
    """QueryParamsRequest is request type for the Query/Params RPC method."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___QueryParamsRequest: _TypeAlias = QueryParamsRequest  # noqa: Y015

@_typing.final
class QueryParamsResponse(_message.Message):
    """QueryParamsResponse is response type for the Query/Params RPC method."""

    DESCRIPTOR: _descriptor.Descriptor

    PARAMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def params(self) -> _params_pb2.Params:
        """params holds all the parameters of this module."""

    def __init__(
        self,
        *,
        params: _params_pb2.Params | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryParamsResponse: _TypeAlias = QueryParamsResponse  # noqa: Y015

@_typing.final
class QueryGetSessionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    APPLICATION_ADDRESS_FIELD_NUMBER: _builtins.int
    SERVICE_ID_FIELD_NUMBER: _builtins.int
    BLOCK_HEIGHT_FIELD_NUMBER: _builtins.int
    application_address: _builtins.str
    """The Bech32 address of the application."""
    service_id: _builtins.str
    """The service ID to query the session for"""
    block_height: _builtins.int
    """The block height to query the session for"""
    def __init__(
        self,
        *,
        application_address: _builtins.str = ...,
        service_id: _builtins.str = ...,
        block_height: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application_address", b"application_address", "block_height", b"block_height", "service_id", b"service_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryGetSessionRequest: _TypeAlias = QueryGetSessionRequest  # noqa: Y015

@_typing.final
class QueryGetSessionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def session(self) -> _types_pb2.Session: ...
    def __init__(
        self,
        *,
        session: _types_pb2.Session | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["session", b"session"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["session", b"session"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryGetSessionResponse: _TypeAlias = QueryGetSessionResponse  # noqa: Y015
