"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from poktroll_clients.proto.pocket.application import types_pb2 as _types_pb2
from poktroll_clients.proto.pocket.shared import supplier_pb2 as _supplier_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SessionHeader(_message.Message):
    """NOTE: Using signed integers for consistency with the cosmos SDK

    SessionHeader is a lightweight header for a session that can be passed around.
    It is the minimal amount of data required to hydrate & retrieve all data relevant to the session.
    """

    DESCRIPTOR: _descriptor.Descriptor

    APPLICATION_ADDRESS_FIELD_NUMBER: _builtins.int
    SERVICE_ID_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    SESSION_START_BLOCK_HEIGHT_FIELD_NUMBER: _builtins.int
    SESSION_END_BLOCK_HEIGHT_FIELD_NUMBER: _builtins.int
    application_address: _builtins.str
    """The Bech32 address of the application."""
    service_id: _builtins.str
    """The service id this session is for"""
    session_id: _builtins.str
    """NOTE: session_id can be derived from the above values using onchain but is included in the header for convenience
    A unique pseudorandom ID for this session
    """
    session_start_block_height: _builtins.int
    """The height at which this session started"""
    session_end_block_height: _builtins.int
    """Note that`session_end_block_height` is a derivative of (`start` + `num_blocks_per_session`)
    as governed by onchain params at the time of the session start.
    It is stored as an additional field to simplify business logic in case
    the number of blocks_per_session changes during the session.
    The height at which this session ended, this is the last block of the session
    """
    def __init__(
        self,
        *,
        application_address: _builtins.str = ...,
        service_id: _builtins.str = ...,
        session_id: _builtins.str = ...,
        session_start_block_height: _builtins.int = ...,
        session_end_block_height: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application_address", b"application_address", "service_id", b"service_id", "session_end_block_height", b"session_end_block_height", "session_id", b"session_id", "session_start_block_height", b"session_start_block_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SessionHeader: _TypeAlias = SessionHeader  # noqa: Y015

@_typing.final
class Session(_message.Message):
    """Session is a fully hydrated session object that contains all the information for the Session
    and its participants.
    """

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    SESSION_NUMBER_FIELD_NUMBER: _builtins.int
    NUM_BLOCKS_PER_SESSION_FIELD_NUMBER: _builtins.int
    APPLICATION_FIELD_NUMBER: _builtins.int
    SUPPLIERS_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    """A unique pseudorandom ID for this session"""
    session_number: _builtins.int
    """The session number since genesis"""
    num_blocks_per_session: _builtins.int
    """The number of blocks per session when this session started"""
    @_builtins.property
    def header(self) -> Global___SessionHeader:
        """The header of the session containing lightweight data"""

    @_builtins.property
    def application(self) -> _types_pb2.Application:
        """A fully hydrated application object this session is for"""

    @_builtins.property
    def suppliers(self) -> _containers.RepeatedCompositeFieldContainer[_supplier_pb2.Supplier]:
        """A fully hydrated set of servicers that are serving the application"""

    def __init__(
        self,
        *,
        header: Global___SessionHeader | None = ...,
        session_id: _builtins.str = ...,
        session_number: _builtins.int = ...,
        num_blocks_per_session: _builtins.int = ...,
        application: _types_pb2.Application | None = ...,
        suppliers: _abc.Iterable[_supplier_pb2.Supplier] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["application", b"application", "header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application", b"application", "header", b"header", "num_blocks_per_session", b"num_blocks_per_session", "session_id", b"session_id", "session_number", b"session_number", "suppliers", b"suppliers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Session: _TypeAlias = Session  # noqa: Y015
