"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PageRequest(_message.Message):
    """PageRequest is to be embedded in gRPC request messages for efficient
    pagination. Ex:

     message SomeRequest {
             Foo some_parameter = 1;
             PageRequest pagination = 2;
     }
    """

    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    COUNT_TOTAL_FIELD_NUMBER: _builtins.int
    REVERSE_FIELD_NUMBER: _builtins.int
    key: _builtins.bytes
    """key is a value returned in PageResponse.next_key to begin
    querying the next page most efficiently. Only one of offset or key
    should be set.
    """
    offset: _builtins.int
    """offset is a numeric offset that can be used when key is unavailable.
    It is less efficient than using key. Only one of offset or key should
    be set.
    """
    limit: _builtins.int
    """limit is the total number of results to be returned in the result page.
    If left empty it will default to a value to be set by each app.
    """
    count_total: _builtins.bool
    """count_total is set to true  to indicate that the result set should include
    a count of the total number of items available for pagination in UIs.
    count_total is only respected when offset is used. It is ignored when key
    is set.
    """
    reverse: _builtins.bool
    """reverse is set to true if results are to be returned in the descending order."""
    def __init__(
        self,
        *,
        key: _builtins.bytes = ...,
        offset: _builtins.int = ...,
        limit: _builtins.int = ...,
        count_total: _builtins.bool = ...,
        reverse: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count_total", b"count_total", "key", b"key", "limit", b"limit", "offset", b"offset", "reverse", b"reverse"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PageRequest: _TypeAlias = PageRequest  # noqa: Y015

@_typing.final
class PageResponse(_message.Message):
    """PageResponse is to be embedded in gRPC response messages where the
    corresponding request message has used PageRequest.

     message SomeResponse {
             repeated Bar results = 1;
             PageResponse page = 2;
     }
    """

    DESCRIPTOR: _descriptor.Descriptor

    NEXT_KEY_FIELD_NUMBER: _builtins.int
    TOTAL_FIELD_NUMBER: _builtins.int
    next_key: _builtins.bytes
    """next_key is the key to be passed to PageRequest.key to
    query the next page most efficiently. It will be empty if
    there are no more results.
    """
    total: _builtins.int
    """total is total number of results available if PageRequest.count_total
    was set, its value is undefined otherwise
    """
    def __init__(
        self,
        *,
        next_key: _builtins.bytes = ...,
        total: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["next_key", b"next_key", "total", b"total"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PageResponse: _TypeAlias = PageResponse  # noqa: Y015
