"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from poktroll_clients.proto.pocket.gateway import types_pb2 as _types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class EventGatewayStaked(_message.Message):
    """EventGatewayStaked is emitted when a gateway is staked or up-staked."""

    DESCRIPTOR: _descriptor.Descriptor

    GATEWAY_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    session_end_height: _builtins.int
    """The end height of the session in which gateway was staked."""
    @_builtins.property
    def gateway(self) -> _types_pb2.Gateway:
        """The gateway that has been staked."""

    def __init__(
        self,
        *,
        gateway: _types_pb2.Gateway | None = ...,
        session_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["gateway", b"gateway"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gateway", b"gateway", "session_end_height", b"session_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventGatewayStaked: _TypeAlias = EventGatewayStaked  # noqa: Y015

@_typing.final
class EventGatewayUnbondingBegin(_message.Message):
    """EventGatewayUnbondingBegin is emitted when a gateway begins unbonding.
    It is triggered by the commitment of an unstake gateway message.
    This event signals that a gateway has begun unbonding.
    The unbonding period is determined by the shared param gateway_unbonding_period_sessions.
    """

    DESCRIPTOR: _descriptor.Descriptor

    GATEWAY_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    UNBONDING_END_HEIGHT_FIELD_NUMBER: _builtins.int
    session_end_height: _builtins.int
    """The end height of the session in which the unbonding began."""
    unbonding_end_height: _builtins.int
    """The height at which gateway unbonding will end."""
    @_builtins.property
    def gateway(self) -> _types_pb2.Gateway: ...
    def __init__(
        self,
        *,
        gateway: _types_pb2.Gateway | None = ...,
        session_end_height: _builtins.int = ...,
        unbonding_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["gateway", b"gateway"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gateway", b"gateway", "session_end_height", b"session_end_height", "unbonding_end_height", b"unbonding_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventGatewayUnbondingBegin: _TypeAlias = EventGatewayUnbondingBegin  # noqa: Y015

@_typing.final
class EventGatewayUnbondingEnd(_message.Message):
    """EventGatewayUnbondingEnd is emitted when a gateway has completed unbonding.
    The unbonding period is determined by the shared param gateway_unbonding_period_sessions.
    """

    DESCRIPTOR: _descriptor.Descriptor

    GATEWAY_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    UNBONDING_END_HEIGHT_FIELD_NUMBER: _builtins.int
    session_end_height: _builtins.int
    """The end height of the session in which the unbonding began."""
    unbonding_end_height: _builtins.int
    """The height at which gateway unbonding will end."""
    @_builtins.property
    def gateway(self) -> _types_pb2.Gateway:
        """The gateway that has completed unbonding."""

    def __init__(
        self,
        *,
        gateway: _types_pb2.Gateway | None = ...,
        session_end_height: _builtins.int = ...,
        unbonding_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["gateway", b"gateway"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gateway", b"gateway", "session_end_height", b"session_end_height", "unbonding_end_height", b"unbonding_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventGatewayUnbondingEnd: _TypeAlias = EventGatewayUnbondingEnd  # noqa: Y015

@_typing.final
class EventGatewayUnbondingCanceled(_message.Message):
    """EventGatewayUnbondingCanceled is emitted when a gateway which was unbonding
    successfully (re-)stakes before the unbonding period has elapsed.
    An EventGatewayStaked event will also be emitted immediately after this event.
    """

    DESCRIPTOR: _descriptor.Descriptor

    GATEWAY_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    session_end_height: _builtins.int
    """The end height of the session in which the unbonding was canceled."""
    @_builtins.property
    def gateway(self) -> _types_pb2.Gateway: ...
    def __init__(
        self,
        *,
        gateway: _types_pb2.Gateway | None = ...,
        session_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["gateway", b"gateway"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gateway", b"gateway", "session_end_height", b"session_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventGatewayUnbondingCanceled: _TypeAlias = EventGatewayUnbondingCanceled  # noqa: Y015
