"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from poktroll_clients.proto.cosmos.base.v1beta1 import coin_pb2 as _coin_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Params(_message.Message):
    """Params defines the parameters for the module."""

    DESCRIPTOR: _descriptor.Descriptor

    MIN_STAKE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def min_stake(self) -> _coin_pb2.Coin:
        """min_stake is the minimum amount of uPOKT that a gateway must stake."""

    def __init__(
        self,
        *,
        min_stake: _coin_pb2.Coin | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["min_stake", b"min_stake"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["min_stake", b"min_stake"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Params: _TypeAlias = Params  # noqa: Y015
