"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from poktroll_clients.proto.cosmos.base.v1beta1 import coin_pb2 as _coin_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from poktroll_clients.proto.pocket.gateway import params_pb2 as _params_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MsgUpdateParams(_message.Message):
    """MsgUpdateParams is the Msg/UpdateParams request type."""

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    PARAMS_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """authority is the address that controls the module (defaults to x/gov unless overwritten)."""
    @_builtins.property
    def params(self) -> _params_pb2.Params:
        """TODO_IMPROVE(#322): The requirement to provide all params is adopted from the
        latest Cosmos SDK version. We should look into either improving this ourselves
        or seeing if it is on their roadmap.

        params defines the x/gateway parameters to update.
        NOTE: All parameters must be supplied.
        """

    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        params: _params_pb2.Params | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authority", b"authority", "params", b"params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgUpdateParams: _TypeAlias = MsgUpdateParams  # noqa: Y015

@_typing.final
class MsgUpdateParamsResponse(_message.Message):
    """MsgUpdateParamsResponse defines the response structure for executing a
    MsgUpdateParams message.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUpdateParamsResponse: _TypeAlias = MsgUpdateParamsResponse  # noqa: Y015

@_typing.final
class MsgStakeGateway(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    STAKE_FIELD_NUMBER: _builtins.int
    address: _builtins.str
    """The Bech32 address of the gateway"""
    @_builtins.property
    def stake(self) -> _coin_pb2.Coin:
        """The total amount of uPOKT the gateway is staking. Must be ≥ to the current amount that the gateway has staked (if any)"""

    def __init__(
        self,
        *,
        address: _builtins.str = ...,
        stake: _coin_pb2.Coin | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stake", b"stake"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "stake", b"stake"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgStakeGateway: _TypeAlias = MsgStakeGateway  # noqa: Y015

@_typing.final
class MsgStakeGatewayResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgStakeGatewayResponse: _TypeAlias = MsgStakeGatewayResponse  # noqa: Y015

@_typing.final
class MsgUnstakeGateway(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    address: _builtins.str
    """The Bech32 address of the gateway"""
    def __init__(
        self,
        *,
        address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgUnstakeGateway: _TypeAlias = MsgUnstakeGateway  # noqa: Y015

@_typing.final
class MsgUnstakeGatewayResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUnstakeGatewayResponse: _TypeAlias = MsgUnstakeGatewayResponse  # noqa: Y015

@_typing.final
class MsgUpdateParam(_message.Message):
    """MsgUpdateParam is the Msg/UpdateParam request type to update a single param."""

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    AS_COIN_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """authority is the address that controls the module (defaults to x/gov unless overwritten)."""
    name: _builtins.str
    @_builtins.property
    def as_coin(self) -> _coin_pb2.Coin: ...
    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        name: _builtins.str = ...,
        as_coin: _coin_pb2.Coin | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["as_coin", b"as_coin", "as_type", b"as_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["as_coin", b"as_coin", "as_type", b"as_type", "authority", b"authority", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_as_type: _TypeAlias = _typing.Literal["as_coin"]  # noqa: Y015
    _WhichOneofArgType_as_type: _TypeAlias = _typing.Literal["as_type", b"as_type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_as_type) -> _WhichOneofReturnType_as_type | None: ...

Global___MsgUpdateParam: _TypeAlias = MsgUpdateParam  # noqa: Y015

@_typing.final
class MsgUpdateParamResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUpdateParamResponse: _TypeAlias = MsgUpdateParamResponse  # noqa: Y015
