"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from poktroll_clients.proto.cosmos.base.v1beta1 import coin_pb2 as _coin_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Gateway(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    STAKE_FIELD_NUMBER: _builtins.int
    UNSTAKE_SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    address: _builtins.str
    """The Bech32 address of the gateway"""
    unstake_session_end_height: _builtins.int
    """Session end height at which the gateway initiated unstaking (0 if not unstaking)"""
    @_builtins.property
    def stake(self) -> _coin_pb2.Coin:
        """The total amount of uPOKT the gateway has staked"""

    def __init__(
        self,
        *,
        address: _builtins.str = ...,
        stake: _coin_pb2.Coin | None = ...,
        unstake_session_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stake", b"stake"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "stake", b"stake", "unstake_session_end_height", b"unstake_session_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Gateway: _TypeAlias = Gateway  # noqa: Y015
