"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from poktroll_clients.proto.pocket.shared import supplier_pb2 as _supplier_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _SupplierUnbondingReason:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SupplierUnbondingReasonEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SupplierUnbondingReason.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SUPPLIER_UNBONDING_REASON_UNSPECIFIED: _SupplierUnbondingReason.ValueType  # 0
    SUPPLIER_UNBONDING_REASON_VOLUNTARY: _SupplierUnbondingReason.ValueType  # 1
    SUPPLIER_UNBONDING_REASON_BELOW_MIN_STAKE: _SupplierUnbondingReason.ValueType  # 2
    SUPPLIER_UNBONDING_REASON_MIGRATION: _SupplierUnbondingReason.ValueType  # 3

class SupplierUnbondingReason(_SupplierUnbondingReason, metaclass=_SupplierUnbondingReasonEnumTypeWrapper): ...

SUPPLIER_UNBONDING_REASON_UNSPECIFIED: SupplierUnbondingReason.ValueType  # 0
SUPPLIER_UNBONDING_REASON_VOLUNTARY: SupplierUnbondingReason.ValueType  # 1
SUPPLIER_UNBONDING_REASON_BELOW_MIN_STAKE: SupplierUnbondingReason.ValueType  # 2
SUPPLIER_UNBONDING_REASON_MIGRATION: SupplierUnbondingReason.ValueType  # 3
Global___SupplierUnbondingReason: _TypeAlias = SupplierUnbondingReason  # noqa: Y015

@_typing.final
class EventSupplierStaked(_message.Message):
    """EventSupplierStaked is emitted when a supplier stake message is committed onchain.
    Next index: 4
    """

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    session_end_height: _builtins.int
    """The session end height of the last session in which the supplier was staked."""
    operator_address: _builtins.str
    def __init__(
        self,
        *,
        session_end_height: _builtins.int = ...,
        operator_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["operator_address", b"operator_address", "session_end_height", b"session_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventSupplierStaked: _TypeAlias = EventSupplierStaked  # noqa: Y015

@_typing.final
class EventSupplierUnbondingBegin(_message.Message):
    """EventSupplierUnbondingBegin is emitted when an application unstake message
    is committed onchain, indicating that the supplier will now begin unbonding.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SUPPLIER_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    UNBONDING_END_HEIGHT_FIELD_NUMBER: _builtins.int
    reason: Global___SupplierUnbondingReason.ValueType
    session_end_height: _builtins.int
    """The session end height of the last session in which the supplier unbonding began."""
    unbonding_end_height: _builtins.int
    """The height at which supplier unbonding will end."""
    @_builtins.property
    def supplier(self) -> _supplier_pb2.Supplier: ...
    def __init__(
        self,
        *,
        supplier: _supplier_pb2.Supplier | None = ...,
        reason: Global___SupplierUnbondingReason.ValueType = ...,
        session_end_height: _builtins.int = ...,
        unbonding_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["supplier", b"supplier"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reason", b"reason", "session_end_height", b"session_end_height", "supplier", b"supplier", "unbonding_end_height", b"unbonding_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventSupplierUnbondingBegin: _TypeAlias = EventSupplierUnbondingBegin  # noqa: Y015

@_typing.final
class EventSupplierUnbondingEnd(_message.Message):
    """EventSupplierUnbondingEnd is emitted when an supplier has completed
    unbonding. The unbonding period is determined by the shared param,
    supplier_unbonding_period_sessions.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SUPPLIER_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    UNBONDING_END_HEIGHT_FIELD_NUMBER: _builtins.int
    reason: Global___SupplierUnbondingReason.ValueType
    session_end_height: _builtins.int
    """The session end height of the session in which the supplier unbonding endeded."""
    unbonding_end_height: _builtins.int
    """The height at which supplier unbonding will end."""
    @_builtins.property
    def supplier(self) -> _supplier_pb2.Supplier: ...
    def __init__(
        self,
        *,
        supplier: _supplier_pb2.Supplier | None = ...,
        reason: Global___SupplierUnbondingReason.ValueType = ...,
        session_end_height: _builtins.int = ...,
        unbonding_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["supplier", b"supplier"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reason", b"reason", "session_end_height", b"session_end_height", "supplier", b"supplier", "unbonding_end_height", b"unbonding_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventSupplierUnbondingEnd: _TypeAlias = EventSupplierUnbondingEnd  # noqa: Y015

@_typing.final
class EventSupplierUnbondingCanceled(_message.Message):
    """EventSupplierUnbondingCanceled is emitted when an supplier which was unbonding
    successfully (re-)stakes before the unbonding period has elapsed. An EventSupplierStaked
    event will also be emitted immediately after this event.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SUPPLIER_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    height: _builtins.int
    """The exact height at which the supplier unbonding was canceled."""
    session_end_height: _builtins.int
    """The session end height of the session in which the supplier unbonding was canceled."""
    @_builtins.property
    def supplier(self) -> _supplier_pb2.Supplier: ...
    def __init__(
        self,
        *,
        supplier: _supplier_pb2.Supplier | None = ...,
        height: _builtins.int = ...,
        session_end_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["supplier", b"supplier"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["height", b"height", "session_end_height", b"session_end_height", "supplier", b"supplier"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventSupplierUnbondingCanceled: _TypeAlias = EventSupplierUnbondingCanceled  # noqa: Y015

@_typing.final
class EventSupplierServiceConfigActivated(_message.Message):
    """EventSupplierServiceConfigActivated is emitted when a supplier service configuration
    becomes effective at a specific block height.
    Next index: 5
    """

    DESCRIPTOR: _descriptor.Descriptor

    ACTIVATION_HEIGHT_FIELD_NUMBER: _builtins.int
    OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    SERVICE_ID_FIELD_NUMBER: _builtins.int
    activation_height: _builtins.int
    """activation_height indicates the block height at which the new service
    configurations became active.
    """
    operator_address: _builtins.str
    service_id: _builtins.str
    """The Service ID for which the supplier is configured"""
    def __init__(
        self,
        *,
        activation_height: _builtins.int = ...,
        operator_address: _builtins.str = ...,
        service_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activation_height", b"activation_height", "operator_address", b"operator_address", "service_id", b"service_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventSupplierServiceConfigActivated: _TypeAlias = EventSupplierServiceConfigActivated  # noqa: Y015
