"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from poktroll_clients.proto.cosmos.base.query.v1beta1 import pagination_pb2 as _pagination_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from poktroll_clients.proto.pocket.shared import supplier_pb2 as _supplier_pb2
from poktroll_clients.proto.pocket.supplier import params_pb2 as _params_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class QueryParamsRequest(_message.Message):
    """QueryParamsRequest is request type for the Query/Params RPC method."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___QueryParamsRequest: _TypeAlias = QueryParamsRequest  # noqa: Y015

@_typing.final
class QueryParamsResponse(_message.Message):
    """QueryParamsResponse is response type for the Query/Params RPC method."""

    DESCRIPTOR: _descriptor.Descriptor

    PARAMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def params(self) -> _params_pb2.Params:
        """params holds all the parameters of this module."""

    def __init__(
        self,
        *,
        params: _params_pb2.Params | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryParamsResponse: _TypeAlias = QueryParamsResponse  # noqa: Y015

@_typing.final
class QueryGetSupplierRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    DEHYDRATED_FIELD_NUMBER: _builtins.int
    operator_address: _builtins.str
    """TODO_TECHDEBT: Add the ability to query for a supplier by owner_id"""
    dehydrated: _builtins.bool
    """if true, return a dehydrated version of the supplier.
    Why? This enables smaller response payloads to reduce payload size.
    Example: Removes service_config_history and rev_share details from the response. See the implementation for more details.
    """
    def __init__(
        self,
        *,
        operator_address: _builtins.str = ...,
        dehydrated: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dehydrated", b"dehydrated", "operator_address", b"operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryGetSupplierRequest: _TypeAlias = QueryGetSupplierRequest  # noqa: Y015

@_typing.final
class QueryGetSupplierResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUPPLIER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def supplier(self) -> _supplier_pb2.Supplier: ...
    def __init__(
        self,
        *,
        supplier: _supplier_pb2.Supplier | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["supplier", b"supplier"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["supplier", b"supplier"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryGetSupplierResponse: _TypeAlias = QueryGetSupplierResponse  # noqa: Y015

@_typing.final
class QueryAllSuppliersRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PAGINATION_FIELD_NUMBER: _builtins.int
    SERVICE_ID_FIELD_NUMBER: _builtins.int
    OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    OWNER_ADDRESS_FIELD_NUMBER: _builtins.int
    DEHYDRATED_FIELD_NUMBER: _builtins.int
    service_id: _builtins.str
    """Optional filters that can be combined (AND logic)
    unique service identifier to filter by
    """
    operator_address: _builtins.str
    """supplier operator address to filter by"""
    owner_address: _builtins.str
    """supplier owner address to filter by"""
    dehydrated: _builtins.bool
    """if true, return a dehydrated version of the supplier.
    Why? This enables smaller response payloads to reduce pagination of the supplier list.
    Example: Removes service_config_history and rev_share details from the response. See the implementation for more details.
    """
    @_builtins.property
    def pagination(self) -> _pagination_pb2.PageRequest: ...
    def __init__(
        self,
        *,
        pagination: _pagination_pb2.PageRequest | None = ...,
        service_id: _builtins.str = ...,
        operator_address: _builtins.str = ...,
        owner_address: _builtins.str = ...,
        dehydrated: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dehydrated", b"dehydrated", "operator_address", b"operator_address", "owner_address", b"owner_address", "pagination", b"pagination", "service_id", b"service_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryAllSuppliersRequest: _TypeAlias = QueryAllSuppliersRequest  # noqa: Y015

@_typing.final
class QueryAllSuppliersResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUPPLIER_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def supplier(self) -> _containers.RepeatedCompositeFieldContainer[_supplier_pb2.Supplier]: ...
    @_builtins.property
    def pagination(self) -> _pagination_pb2.PageResponse: ...
    def __init__(
        self,
        *,
        supplier: _abc.Iterable[_supplier_pb2.Supplier] | None = ...,
        pagination: _pagination_pb2.PageResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "supplier", b"supplier"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryAllSuppliersResponse: _TypeAlias = QueryAllSuppliersResponse  # noqa: Y015
