"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from poktroll_clients.proto.cosmos.base.v1beta1 import coin_pb2 as _coin_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from poktroll_clients.proto.pocket.shared import service_pb2 as _service_pb2
from poktroll_clients.proto.pocket.supplier import params_pb2 as _params_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MsgUpdateParams(_message.Message):
    """MsgUpdateParams is the Msg/UpdateParams request type."""

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    PARAMS_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """authority is the address that controls the module (defaults to x/gov unless overwritten)."""
    @_builtins.property
    def params(self) -> _params_pb2.Params:
        """params defines the x/supplier parameters to update.
        NOTE: All parameters must be supplied.
        """

    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        params: _params_pb2.Params | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authority", b"authority", "params", b"params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgUpdateParams: _TypeAlias = MsgUpdateParams  # noqa: Y015

@_typing.final
class MsgUpdateParamsResponse(_message.Message):
    """MsgUpdateParamsResponse defines the response structure for executing a
    MsgUpdateParams message.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUpdateParamsResponse: _TypeAlias = MsgUpdateParamsResponse  # noqa: Y015

@_typing.final
class MsgStakeSupplier(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SIGNER_FIELD_NUMBER: _builtins.int
    OWNER_ADDRESS_FIELD_NUMBER: _builtins.int
    OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    STAKE_FIELD_NUMBER: _builtins.int
    SERVICES_FIELD_NUMBER: _builtins.int
    signer: _builtins.str
    """The Bech32 address of the message signer (i.e. owner or operator)"""
    owner_address: _builtins.str
    """The Bech32 address of the owner (i.e. custodial, staker)"""
    operator_address: _builtins.str
    """The Bech32 address of the operator (i.e. provider, non-custodial)"""
    @_builtins.property
    def stake(self) -> _coin_pb2.Coin:
        """The total amount of uPOKT the supplier has staked. Must be ≥ to the current amount that the supplier has staked (if any)"""

    @_builtins.property
    def services(self) -> _containers.RepeatedCompositeFieldContainer[_service_pb2.SupplierServiceConfig]:
        """The list of services this supplier is staked to provide service for"""

    def __init__(
        self,
        *,
        signer: _builtins.str = ...,
        owner_address: _builtins.str = ...,
        operator_address: _builtins.str = ...,
        stake: _coin_pb2.Coin | None = ...,
        services: _abc.Iterable[_service_pb2.SupplierServiceConfig] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stake", b"stake"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["operator_address", b"operator_address", "owner_address", b"owner_address", "services", b"services", "signer", b"signer", "stake", b"stake"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgStakeSupplier: _TypeAlias = MsgStakeSupplier  # noqa: Y015

@_typing.final
class MsgStakeSupplierResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgStakeSupplierResponse: _TypeAlias = MsgStakeSupplierResponse  # noqa: Y015

@_typing.final
class MsgUnstakeSupplier(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SIGNER_FIELD_NUMBER: _builtins.int
    OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    signer: _builtins.str
    """The Bech32 address of the message signer (i.e. owner or operator)"""
    operator_address: _builtins.str
    """The Bech32 address of the operator (i.e. provider, non-custodial)"""
    def __init__(
        self,
        *,
        signer: _builtins.str = ...,
        operator_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["operator_address", b"operator_address", "signer", b"signer"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgUnstakeSupplier: _TypeAlias = MsgUnstakeSupplier  # noqa: Y015

@_typing.final
class MsgUnstakeSupplierResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUnstakeSupplierResponse: _TypeAlias = MsgUnstakeSupplierResponse  # noqa: Y015

@_typing.final
class MsgUpdateParam(_message.Message):
    """MsgUpdateParam is the Msg/UpdateParam request type to update a single param."""

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    AS_COIN_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """authority is the address that controls the module (defaults to x/gov unless overwritten)."""
    name: _builtins.str
    @_builtins.property
    def as_coin(self) -> _coin_pb2.Coin: ...
    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        name: _builtins.str = ...,
        as_coin: _coin_pb2.Coin | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["asType", b"asType", "as_coin", b"as_coin"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asType", b"asType", "as_coin", b"as_coin", "authority", b"authority", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_asType: _TypeAlias = _typing.Literal["as_coin"]  # noqa: Y015
    _WhichOneofArgType_asType: _TypeAlias = _typing.Literal["asType", b"asType"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_asType) -> _WhichOneofReturnType_asType | None: ...

Global___MsgUpdateParam: _TypeAlias = MsgUpdateParam  # noqa: Y015

@_typing.final
class MsgUpdateParamResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUpdateParamResponse: _TypeAlias = MsgUpdateParamResponse  # noqa: Y015
