"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _ClaimExpirationReason:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ClaimExpirationReasonEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ClaimExpirationReason.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    EXPIRATION_REASON_UNSPECIFIED: _ClaimExpirationReason.ValueType  # 0
    """Default value, means may be valid"""
    PROOF_MISSING: _ClaimExpirationReason.ValueType  # 1
    """A proof was required but not submitted"""
    PROOF_INVALID: _ClaimExpirationReason.ValueType  # 2
    """A proof was submitted but was invalid"""

class ClaimExpirationReason(_ClaimExpirationReason, metaclass=_ClaimExpirationReasonEnumTypeWrapper):
    """TODO_CONSIDERATION: Consider prefixing these enums with CLAIM_EXPIRATION_REASON_"""

EXPIRATION_REASON_UNSPECIFIED: ClaimExpirationReason.ValueType  # 0
"""Default value, means may be valid"""
PROOF_MISSING: ClaimExpirationReason.ValueType  # 1
"""A proof was required but not submitted"""
PROOF_INVALID: ClaimExpirationReason.ValueType  # 2
"""A proof was submitted but was invalid"""
Global___ClaimExpirationReason: _TypeAlias = ClaimExpirationReason  # noqa: Y015

@_typing.final
class EventClaimExpired(_message.Message):
    """EventClaimExpired is emitted during settlement when a claim expires.
    This is likely the result of a claim requiring an onchain proof not being submitted.
    The claim cannot be settled, leading to that work never being rewarded.
    Next index: 13
    """

    DESCRIPTOR: _descriptor.Descriptor

    EXPIRATION_REASON_FIELD_NUMBER: _builtins.int
    NUM_RELAYS_FIELD_NUMBER: _builtins.int
    NUM_CLAIMED_COMPUTE_UNITS_FIELD_NUMBER: _builtins.int
    NUM_ESTIMATED_COMPUTE_UNITS_FIELD_NUMBER: _builtins.int
    CLAIMED_UPOKT_FIELD_NUMBER: _builtins.int
    SERVICE_ID_FIELD_NUMBER: _builtins.int
    APPLICATION_ADDRESS_FIELD_NUMBER: _builtins.int
    SESSION_END_BLOCK_HEIGHT_FIELD_NUMBER: _builtins.int
    CLAIM_PROOF_STATUS_INT_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    expiration_reason: Global___ClaimExpirationReason.ValueType
    """The reason why the claim expired, leading to a Supplier being penalized (i.e. burn)."""
    num_relays: _builtins.int
    """Number of relays claimed to be in the session tree."""
    num_claimed_compute_units: _builtins.int
    """Number of compute units claimed in the session tree.
    It is a function of the number of relays in the session tree and onchain parameters.
    """
    num_estimated_compute_units: _builtins.int
    """Number of total estimated compute units of work done.
    It is a function of the number of claimed compute units and the relay difficulty multiplier.
    """
    claimed_upokt: _builtins.str
    """The amount of uPOKT claimed for the work done.
    It is a function of the number of estimated compute units and the compute units to token multiplier.
    """
    service_id: _builtins.str
    """The Service ID to which the claim corresponds."""
    application_address: _builtins.str
    """The address of the application which participated in the claimed session."""
    session_end_block_height: _builtins.int
    """The end block height of the session to which the claim corresponds."""
    claim_proof_status_int: _builtins.int
    """The validation status of the claim.
    DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
    enum to minimize onchain disk utilization. This is necessary because event
    data is not always protobuf-encoded in the various places and formats that it
    appears in onchain leveldb databases.
    Enum values:
      PENDING_VALIDATION = 0;
      VALIDATED = 1;
      INVALID = 2;
    """
    supplier_operator_address: _builtins.str
    """The operator address of the supplier whose claim expired."""
    def __init__(
        self,
        *,
        expiration_reason: Global___ClaimExpirationReason.ValueType = ...,
        num_relays: _builtins.int = ...,
        num_claimed_compute_units: _builtins.int = ...,
        num_estimated_compute_units: _builtins.int = ...,
        claimed_upokt: _builtins.str = ...,
        service_id: _builtins.str = ...,
        application_address: _builtins.str = ...,
        session_end_block_height: _builtins.int = ...,
        claim_proof_status_int: _builtins.int = ...,
        supplier_operator_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application_address", b"application_address", "claim_proof_status_int", b"claim_proof_status_int", "claimed_upokt", b"claimed_upokt", "expiration_reason", b"expiration_reason", "num_claimed_compute_units", b"num_claimed_compute_units", "num_estimated_compute_units", b"num_estimated_compute_units", "num_relays", b"num_relays", "service_id", b"service_id", "session_end_block_height", b"session_end_block_height", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventClaimExpired: _TypeAlias = EventClaimExpired  # noqa: Y015

@_typing.final
class EventClaimSettled(_message.Message):
    """EventClaimSettled is emitted during settlement whenever a claim is successfully settled.
    It may or may not require a proof depending on various on-chain parameters and other factors.
    Next index: 15
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class RewardDistributionEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PROOF_REQUIREMENT_INT_FIELD_NUMBER: _builtins.int
    NUM_RELAYS_FIELD_NUMBER: _builtins.int
    NUM_CLAIMED_COMPUTE_UNITS_FIELD_NUMBER: _builtins.int
    NUM_ESTIMATED_COMPUTE_UNITS_FIELD_NUMBER: _builtins.int
    CLAIMED_UPOKT_FIELD_NUMBER: _builtins.int
    SERVICE_ID_FIELD_NUMBER: _builtins.int
    APPLICATION_ADDRESS_FIELD_NUMBER: _builtins.int
    SESSION_END_BLOCK_HEIGHT_FIELD_NUMBER: _builtins.int
    CLAIM_PROOF_STATUS_INT_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    REWARD_DISTRIBUTION_FIELD_NUMBER: _builtins.int
    proof_requirement_int: _builtins.int
    """Whether a proof was required for the claim to be settled.
    DEV_NOTE: This field uses the integer representation of the ProofRequirementReason
    enum to minimize onchain disk utilization. This is necessary because event
    data is not always protobuf-encoded in the various places and formats that it
    appears in onchain leveldb databases.
    Enum values:
      NOT_REQUIRED = 0;
      PROBABILISTIC = 1;
      THRESHOLD = 2;
    """
    num_relays: _builtins.int
    """Number of relays claimed to be in the session tree."""
    num_claimed_compute_units: _builtins.int
    """Number of compute units claimed in the session tree.
    It is a function of the number of relays in the session tree and onchain parameters.
    """
    num_estimated_compute_units: _builtins.int
    """Number of estimated compute units claimed in the session tree.
    It is a function of the number of claimed compute units and the relay difficulty multiplier for the particular service.
    """
    claimed_upokt: _builtins.str
    """The uPOKT coin claimed to be rewarded for the work done as a function of
    the number of estimated compute units and the compute units to token multiplier.
    """
    service_id: _builtins.str
    """The Service ID to which the claim corresponds."""
    application_address: _builtins.str
    """The address of the application which participated in the claimed session."""
    session_end_block_height: _builtins.int
    """The end block height of the session to which the claim corresponds."""
    claim_proof_status_int: _builtins.int
    """The validation status of the claim.
    DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
    enum to minimize onchain disk utilization. This is necessary because event
    data is not always protobuf-encoded in the various places and formats that it
    appears in onchain leveldb databases.
    Enum values:
      PENDING_VALIDATION = 0;
      VALIDATED = 1;
      INVALID = 2;
    """
    supplier_operator_address: _builtins.str
    """The operator address of the supplier who submitted the claim."""
    @_builtins.property
    def reward_distribution(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """A map of addresses to token amounts corresponding to the distribution of the reward tokens."""

    def __init__(
        self,
        *,
        proof_requirement_int: _builtins.int = ...,
        num_relays: _builtins.int = ...,
        num_claimed_compute_units: _builtins.int = ...,
        num_estimated_compute_units: _builtins.int = ...,
        claimed_upokt: _builtins.str = ...,
        service_id: _builtins.str = ...,
        application_address: _builtins.str = ...,
        session_end_block_height: _builtins.int = ...,
        claim_proof_status_int: _builtins.int = ...,
        supplier_operator_address: _builtins.str = ...,
        reward_distribution: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application_address", b"application_address", "claim_proof_status_int", b"claim_proof_status_int", "claimed_upokt", b"claimed_upokt", "num_claimed_compute_units", b"num_claimed_compute_units", "num_estimated_compute_units", b"num_estimated_compute_units", "num_relays", b"num_relays", "proof_requirement_int", b"proof_requirement_int", "reward_distribution", b"reward_distribution", "service_id", b"service_id", "session_end_block_height", b"session_end_block_height", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventClaimSettled: _TypeAlias = EventClaimSettled  # noqa: Y015

@_typing.final
class EventApplicationOverserviced(_message.Message):
    """EventApplicationOverserviced is emitted when an Application's stake cannot cover the Supplier's claim.
    This means the following will ALWAYS be strictly true:  effective_burn < expected_burn
    - Number of tokens burnt from app stake < Number of tokens burnt from supplier stake
    Next index: 7
    """

    DESCRIPTOR: _descriptor.Descriptor

    APPLICATION_ADDR_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDR_FIELD_NUMBER: _builtins.int
    EXPECTED_BURN_FIELD_NUMBER: _builtins.int
    EFFECTIVE_BURN_FIELD_NUMBER: _builtins.int
    application_addr: _builtins.str
    """The application address consuming onchain services"""
    supplier_operator_addr: _builtins.str
    """The supplier operator address providing onchain services"""
    expected_burn: _builtins.str
    """Expected number of tokens to be burnt from the application's stake.
    A function of the actual amount of work claimed to be done.
    """
    effective_burn: _builtins.str
    """Actual number of tokens burnt from the application's stake.
    A function of the amount that could be covered (less than) relative to the amount of work claimed to be done.
    """
    def __init__(
        self,
        *,
        application_addr: _builtins.str = ...,
        supplier_operator_addr: _builtins.str = ...,
        expected_burn: _builtins.str = ...,
        effective_burn: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application_addr", b"application_addr", "effective_burn", b"effective_burn", "expected_burn", b"expected_burn", "supplier_operator_addr", b"supplier_operator_addr"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventApplicationOverserviced: _TypeAlias = EventApplicationOverserviced  # noqa: Y015

@_typing.final
class EventSupplierSlashed(_message.Message):
    """EventSupplierSlashed is emitted when a supplier is slashed.
    This can happen for in cases such as missing or invalid proofs for submitted claims.
    Next index: 9
    """

    DESCRIPTOR: _descriptor.Descriptor

    PROOF_MISSING_PENALTY_FIELD_NUMBER: _builtins.int
    SERVICE_ID_FIELD_NUMBER: _builtins.int
    APPLICATION_ADDRESS_FIELD_NUMBER: _builtins.int
    SESSION_END_BLOCK_HEIGHT_FIELD_NUMBER: _builtins.int
    CLAIM_PROOF_STATUS_INT_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    proof_missing_penalty: _builtins.str
    """Amount slashed from the supplier's stake.
    A function of the claim size, supplier stake, and various onchain parameters.
    """
    service_id: _builtins.str
    """The Service ID to which the claim corresponds."""
    application_address: _builtins.str
    """The address of the application which participated in the claimed session."""
    session_end_block_height: _builtins.int
    """The end block height of the session to which the claim corresponds."""
    claim_proof_status_int: _builtins.int
    """The validation status of the claim.
    DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
    enum to minimize onchain disk utilization. This is necessary because event
    data is not always protobuf-encoded in the various places and formats that it
    appears in onchain leveldb databases.
    Enum values:
      PENDING_VALIDATION = 0;
      VALIDATED = 1;
      INVALID = 2;
    """
    supplier_operator_address: _builtins.str
    """The operator address of the supplier that was slashed."""
    def __init__(
        self,
        *,
        proof_missing_penalty: _builtins.str = ...,
        service_id: _builtins.str = ...,
        application_address: _builtins.str = ...,
        session_end_block_height: _builtins.int = ...,
        claim_proof_status_int: _builtins.int = ...,
        supplier_operator_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application_address", b"application_address", "claim_proof_status_int", b"claim_proof_status_int", "proof_missing_penalty", b"proof_missing_penalty", "service_id", b"service_id", "session_end_block_height", b"session_end_block_height", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventSupplierSlashed: _TypeAlias = EventSupplierSlashed  # noqa: Y015

@_typing.final
class EventClaimDiscarded(_message.Message):
    """EventClaimDiscarded is emitted when a claim is discarded due to unexpected situations.
    It is used to prevent chain halts in favor of some missing claims.
    Next index: 8
    """

    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    SERVICE_ID_FIELD_NUMBER: _builtins.int
    APPLICATION_ADDRESS_FIELD_NUMBER: _builtins.int
    SESSION_END_BLOCK_HEIGHT_FIELD_NUMBER: _builtins.int
    CLAIM_PROOF_STATUS_INT_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    error: _builtins.str
    """The error that caused the claim to be discarded."""
    service_id: _builtins.str
    """The Service ID to which the claim corresponds."""
    application_address: _builtins.str
    """The address of the application which participated in the claimed session."""
    session_end_block_height: _builtins.int
    """The end block height of the session to which the claim corresponds."""
    claim_proof_status_int: _builtins.int
    """The validation status of the claim.
    DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
    enum to minimize onchain disk utilization. This is necessary because event
    data is not always protobuf-encoded in the various places and formats that it
    appears in onchain leveldb databases.
    Enum values:
      PENDING_VALIDATION = 0;
      VALIDATED = 1;
      INVALID = 2;
    """
    supplier_operator_address: _builtins.str
    """The operator address of the supplier whose claim was discarded."""
    def __init__(
        self,
        *,
        error: _builtins.str = ...,
        service_id: _builtins.str = ...,
        application_address: _builtins.str = ...,
        session_end_block_height: _builtins.int = ...,
        claim_proof_status_int: _builtins.int = ...,
        supplier_operator_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application_address", b"application_address", "claim_proof_status_int", b"claim_proof_status_int", "error", b"error", "service_id", b"service_id", "session_end_block_height", b"session_end_block_height", "supplier_operator_address", b"supplier_operator_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventClaimDiscarded: _TypeAlias = EventClaimDiscarded  # noqa: Y015

@_typing.final
class EventApplicationReimbursementRequest(_message.Message):
    """EventApplicationReimbursementRequest is emitted when an application requests a reimbursement from the DAO.
    It is intended to prevent self dealing attacks when global inflation is enabled.
    TODO_DISTANT_FUTURE: Remove this once global inflation is disabled in perpetuity.
    Next index: 8
    """

    DESCRIPTOR: _descriptor.Descriptor

    APPLICATION_ADDR_FIELD_NUMBER: _builtins.int
    SUPPLIER_OPERATOR_ADDR_FIELD_NUMBER: _builtins.int
    SUPPLIER_OWNER_ADDR_FIELD_NUMBER: _builtins.int
    SERVICE_ID_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    application_addr: _builtins.str
    """The application address consuming onchain services requesting reimbursement."""
    supplier_operator_addr: _builtins.str
    """The supplier operator address providing onchain services"""
    supplier_owner_addr: _builtins.str
    """The supplier owner address providing onchain services"""
    service_id: _builtins.str
    """The service ID associated with the session where a claim was submitted."""
    session_id: _builtins.str
    """The session ID associated with the session where a claim was submitted."""
    amount: _builtins.str
    """The amount of uPOKT to be reimbursed to the application."""
    def __init__(
        self,
        *,
        application_addr: _builtins.str = ...,
        supplier_operator_addr: _builtins.str = ...,
        supplier_owner_addr: _builtins.str = ...,
        service_id: _builtins.str = ...,
        session_id: _builtins.str = ...,
        amount: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "application_addr", b"application_addr", "service_id", b"service_id", "session_id", b"session_id", "supplier_operator_addr", b"supplier_operator_addr", "supplier_owner_addr", b"supplier_owner_addr"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventApplicationReimbursementRequest: _TypeAlias = EventApplicationReimbursementRequest  # noqa: Y015
