"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Params(_message.Message):
    """Params defines the parameters for the tokenomics module."""

    DESCRIPTOR: _descriptor.Descriptor

    DAO_REWARD_ADDRESS_FIELD_NUMBER: _builtins.int
    MINT_ALLOCATION_PERCENTAGES_FIELD_NUMBER: _builtins.int
    GLOBAL_INFLATION_PER_CLAIM_FIELD_NUMBER: _builtins.int
    MINT_EQUALS_BURN_CLAIM_DISTRIBUTION_FIELD_NUMBER: _builtins.int
    MINT_RATIO_FIELD_NUMBER: _builtins.int
    dao_reward_address: _builtins.str
    """Next free index: 10

    dao_reward_address is where the DAO's portion of claims submitted are distributed.
    Bech32 cosmos address
    """
    global_inflation_per_claim: _builtins.float
    """global_inflation_per_claim is the percentage of a claim's claimable uPOKT amount to be minted on settlement.
    GlobalMintTLM: Only used by the GlobalMintTLM at the end of claim settlement.
    """
    mint_ratio: _builtins.float
    """mint_ratio is the proportion of burned tokens to mint (0.0 < mint_ratio <= 1.0).
    PIP-41: A value of 0.975 means 97.5% of burned tokens are minted, 2.5% permanently removed.
    MintEqualsBurnTLM: Only used by the MintEqualsBurnTLM at the end of claim settlement.
    Default: 1.0 (no deflation - mint equals burn for backward compatibility)
    """
    @_builtins.property
    def mint_allocation_percentages(self) -> Global___MintAllocationPercentages:
        """mint_allocation_percentages represents the distribution of newly minted tokens.
        GlobalMintTLM: Only used by the GlobalMintTLM at the end of claim settlement.
        """

    @_builtins.property
    def mint_equals_burn_claim_distribution(self) -> Global___MintEqualsBurnClaimDistribution:
        """mint_equals_burn_claim_distribution controls how the settlement amount is distributed
        when global inflation is disabled (global_inflation_per_claim = 0).
        MintEqualsBurnTLM: Only used by the MintEqualsBurnTLM at the end of claim settlement.
        """

    def __init__(
        self,
        *,
        dao_reward_address: _builtins.str = ...,
        mint_allocation_percentages: Global___MintAllocationPercentages | None = ...,
        global_inflation_per_claim: _builtins.float = ...,
        mint_equals_burn_claim_distribution: Global___MintEqualsBurnClaimDistribution | None = ...,
        mint_ratio: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["mint_allocation_percentages", b"mint_allocation_percentages", "mint_equals_burn_claim_distribution", b"mint_equals_burn_claim_distribution"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dao_reward_address", b"dao_reward_address", "global_inflation_per_claim", b"global_inflation_per_claim", "mint_allocation_percentages", b"mint_allocation_percentages", "mint_equals_burn_claim_distribution", b"mint_equals_burn_claim_distribution", "mint_ratio", b"mint_ratio"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Params: _TypeAlias = Params  # noqa: Y015

@_typing.final
class MintAllocationPercentages(_message.Message):
    """MintAllocationPercentages captures the distribution of newly minted tokens.
    The sum of all new tokens minted must equal 1.
    GlobalMintTLM: Only used by the GlobalMintTLM at the end of claim settlement.
    TODO_DISTANT_FUTURE: Remove this once global inflation is disabled in perpetuity.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DAO_FIELD_NUMBER: _builtins.int
    PROPOSER_FIELD_NUMBER: _builtins.int
    SUPPLIER_FIELD_NUMBER: _builtins.int
    SOURCE_OWNER_FIELD_NUMBER: _builtins.int
    APPLICATION_FIELD_NUMBER: _builtins.int
    dao: _builtins.float
    """dao - % of newley minted tokens sent to the DAO reward address."""
    proposer: _builtins.float
    """proposer - % of newley minted tokens sent to the block proposer (i.e. validator0 account address."""
    supplier: _builtins.float
    """supplier - % of newley minted tokens sent to the block supplier account address."""
    source_owner: _builtins.float
    """source_owner - % of newley minted tokens sent to the service source owner account address."""
    application: _builtins.float
    """application - % of newley minted tokens sent to the application account address."""
    def __init__(
        self,
        *,
        dao: _builtins.float = ...,
        proposer: _builtins.float = ...,
        supplier: _builtins.float = ...,
        source_owner: _builtins.float = ...,
        application: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application", b"application", "dao", b"dao", "proposer", b"proposer", "source_owner", b"source_owner", "supplier", b"supplier"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MintAllocationPercentages: _TypeAlias = MintAllocationPercentages  # noqa: Y015

@_typing.final
class MintEqualsBurnClaimDistribution(_message.Message):
    """MintEqualsBurnClaimDistribution captures the distribution of claimable tokens.
    The sum of all tokens being burnt from the application's stake must equal 1.
    GlobalMintEqualsBurnTLM: Only used by the GlobalMintEqualsBurnTLM at the end of claim settlement.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DAO_FIELD_NUMBER: _builtins.int
    PROPOSER_FIELD_NUMBER: _builtins.int
    SUPPLIER_FIELD_NUMBER: _builtins.int
    SOURCE_OWNER_FIELD_NUMBER: _builtins.int
    APPLICATION_FIELD_NUMBER: _builtins.int
    dao: _builtins.float
    """dao - % of claimable tokens sent to the DAO reward address."""
    proposer: _builtins.float
    """TODO_TECHDEBT: Rename "proposer" to "validators" to reflect the work done in #1753.
    This will span all references to the term "proposer" across documentation, functions, protobufs, variables, tooling, etc..

    proposer - % of claimable tokens sent to the block proposer (i.e. validator0) account address.
    """
    supplier: _builtins.float
    """supplier - % of claimable tokens sent to the block supplier account address."""
    source_owner: _builtins.float
    """source_owner - % of claimable tokens sent to the service source owner account address."""
    application: _builtins.float
    """application - % of claimable tokens sent to the application account address."""
    def __init__(
        self,
        *,
        dao: _builtins.float = ...,
        proposer: _builtins.float = ...,
        supplier: _builtins.float = ...,
        source_owner: _builtins.float = ...,
        application: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application", b"application", "dao", b"dao", "proposer", b"proposer", "source_owner", b"source_owner", "supplier", b"supplier"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MintEqualsBurnClaimDistribution: _TypeAlias = MintEqualsBurnClaimDistribution  # noqa: Y015
