"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from poktroll_clients.proto.pocket.tokenomics import params_pb2 as _params_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MsgUpdateParams(_message.Message):
    """MsgUpdateParams is the Msg/UpdateParams request type to update all params at once."""

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    PARAMS_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """authority is the address that controls the module (defaults to x/gov unless overwritten)."""
    @_builtins.property
    def params(self) -> _params_pb2.Params:
        """params defines the tokenomics parameters to update."""

    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        params: _params_pb2.Params | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authority", b"authority", "params", b"params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgUpdateParams: _TypeAlias = MsgUpdateParams  # noqa: Y015

@_typing.final
class MsgUpdateParamsResponse(_message.Message):
    """MsgUpdateParamsResponse defines the response structure for executing a MsgUpdateParams message."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUpdateParamsResponse: _TypeAlias = MsgUpdateParamsResponse  # noqa: Y015

@_typing.final
class MsgUpdateParam(_message.Message):
    """MsgUpdateParam is the Msg/UpdateParam request type to update a single param."""

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    AS_MINT_ALLOCATION_PERCENTAGES_FIELD_NUMBER: _builtins.int
    AS_STRING_FIELD_NUMBER: _builtins.int
    AS_FLOAT_FIELD_NUMBER: _builtins.int
    AS_MINT_EQUALS_BURN_CLAIM_DISTRIBUTION_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """authority is the address that controls the module (defaults to x/gov unless overwritten)."""
    name: _builtins.str
    """The (name, as_type) tuple must match the corresponding name and type as specified in the `Params` message in `proof/params.proto.`"""
    as_string: _builtins.str
    as_float: _builtins.float
    @_builtins.property
    def as_mint_allocation_percentages(self) -> _params_pb2.MintAllocationPercentages: ...
    @_builtins.property
    def as_mint_equals_burn_claim_distribution(self) -> _params_pb2.MintEqualsBurnClaimDistribution: ...
    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        name: _builtins.str = ...,
        as_mint_allocation_percentages: _params_pb2.MintAllocationPercentages | None = ...,
        as_string: _builtins.str = ...,
        as_float: _builtins.float = ...,
        as_mint_equals_burn_claim_distribution: _params_pb2.MintEqualsBurnClaimDistribution | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["as_float", b"as_float", "as_mint_allocation_percentages", b"as_mint_allocation_percentages", "as_mint_equals_burn_claim_distribution", b"as_mint_equals_burn_claim_distribution", "as_string", b"as_string", "as_type", b"as_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["as_float", b"as_float", "as_mint_allocation_percentages", b"as_mint_allocation_percentages", "as_mint_equals_burn_claim_distribution", b"as_mint_equals_burn_claim_distribution", "as_string", b"as_string", "as_type", b"as_type", "authority", b"authority", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_as_type: _TypeAlias = _typing.Literal["as_mint_allocation_percentages", "as_string", "as_float", "as_mint_equals_burn_claim_distribution"]  # noqa: Y015
    _WhichOneofArgType_as_type: _TypeAlias = _typing.Literal["as_type", b"as_type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_as_type) -> _WhichOneofReturnType_as_type | None: ...

Global___MsgUpdateParam: _TypeAlias = MsgUpdateParam  # noqa: Y015

@_typing.final
class MsgUpdateParamResponse(_message.Message):
    """MsgUpdateParamResponse defines the response structure for executing a MsgUpdateParam message after a single param update."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUpdateParamResponse: _TypeAlias = MsgUpdateParamResponse  # noqa: Y015
