"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from poktroll_clients.proto.cosmos.base.v1beta1 import coin_pb2 as _coin_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from poktroll_clients.proto.pocket.proof import types_pb2 as _types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _SettlementOpReason:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SettlementOpReasonEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SettlementOpReason.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    UNSPECIFIED: _SettlementOpReason.ValueType  # 0
    """*** All TLMs ***

    UNSPECIFIED is the default value for SettlementOpReason
    It is used as a field type for objects which need to distinguish whether a SettlementOpReason has been specified it or not.
    """
    UNSPECIFIED_TLM_SUPPLIER_SLASH_MODULE_TRANSFER: _SettlementOpReason.ValueType  # 11
    """All TLMs: Penalization: Slash, burn, etc..."""
    UNSPECIFIED_TLM_SUPPLIER_SLASH_STAKE_BURN: _SettlementOpReason.ValueType  # 12
    TLM_RELAY_BURN_EQUALS_MINT_SUPPLIER_STAKE_MINT: _SettlementOpReason.ValueType  # 1
    """*** MintEqualsBurnTlm ***

    MintEqualsBurnTlm: Value transfer (credit/debit aka mint/burn)
    """
    TLM_RELAY_BURN_EQUALS_MINT_APPLICATION_STAKE_BURN: _SettlementOpReason.ValueType  # 2
    TLM_RELAY_BURN_EQUALS_MINT_TOKENOMICS_CLAIM_DISTRIBUTION_MINT: _SettlementOpReason.ValueType  # 19
    TLM_RELAY_BURN_EQUALS_MINT_SUPPLIER_SHAREHOLDER_REWARD_DISTRIBUTION: _SettlementOpReason.ValueType  # 4
    """MintEqualsBurnTlm: Reward distribution"""
    TLM_RELAY_BURN_EQUALS_MINT_DAO_REWARD_DISTRIBUTION: _SettlementOpReason.ValueType  # 15
    TLM_RELAY_BURN_EQUALS_MINT_SOURCE_OWNER_REWARD_DISTRIBUTION: _SettlementOpReason.ValueType  # 17
    TLM_RELAY_BURN_EQUALS_MINT_APPLICATION_REWARD_DISTRIBUTION: _SettlementOpReason.ValueType  # 18
    TLM_RELAY_BURN_EQUALS_MINT_VALIDATOR_REWARD_DISTRIBUTION: _SettlementOpReason.ValueType  # 20
    TLM_RELAY_BURN_EQUALS_MINT_DELEGATOR_REWARD_DISTRIBUTION: _SettlementOpReason.ValueType  # 23
    TLM_GLOBAL_MINT_INFLATION: _SettlementOpReason.ValueType  # 3
    """*** GlobalMintTLM ***

    GlobalMintTLM: Inflation
    """
    TLM_GLOBAL_MINT_DAO_REWARD_DISTRIBUTION: _SettlementOpReason.ValueType  # 5
    """GlobalMintTLM: Reward distribution"""
    TLM_GLOBAL_MINT_SUPPLIER_SHAREHOLDER_REWARD_DISTRIBUTION: _SettlementOpReason.ValueType  # 7
    TLM_GLOBAL_MINT_SOURCE_OWNER_REWARD_DISTRIBUTION: _SettlementOpReason.ValueType  # 8
    TLM_GLOBAL_MINT_APPLICATION_REWARD_DISTRIBUTION: _SettlementOpReason.ValueType  # 9
    TLM_GLOBAL_MINT_VALIDATOR_REWARD_DISTRIBUTION: _SettlementOpReason.ValueType  # 21
    TLM_GLOBAL_MINT_DELEGATOR_REWARD_DISTRIBUTION: _SettlementOpReason.ValueType  # 24
    TLM_GLOBAL_MINT_REIMBURSEMENT_REQUEST_ESCROW_DAO_TRANSFER: _SettlementOpReason.ValueType  # 10
    """GlobalMintTLM: Self-servicing mitigation"""
    TLM_GLOBAL_MINT_SUPPLIER_SHAREHOLDER_REWARD_MODULE_TRANSFER: _SettlementOpReason.ValueType  # 13
    """GlobalMintTLM: Module accounting"""
    TLM_GLOBAL_MINT_REIMBURSEMENT_REQUEST_ESCROW_MODULE_TRANSFER: _SettlementOpReason.ValueType  # 14

class SettlementOpReason(_SettlementOpReason, metaclass=_SettlementOpReasonEnumTypeWrapper):
    """SettlementOpReason is a distinct, tlm-specific causal reason for a given operation.
    Next free index: 25
    """

UNSPECIFIED: SettlementOpReason.ValueType  # 0
"""*** All TLMs ***

UNSPECIFIED is the default value for SettlementOpReason
It is used as a field type for objects which need to distinguish whether a SettlementOpReason has been specified it or not.
"""
UNSPECIFIED_TLM_SUPPLIER_SLASH_MODULE_TRANSFER: SettlementOpReason.ValueType  # 11
"""All TLMs: Penalization: Slash, burn, etc..."""
UNSPECIFIED_TLM_SUPPLIER_SLASH_STAKE_BURN: SettlementOpReason.ValueType  # 12
TLM_RELAY_BURN_EQUALS_MINT_SUPPLIER_STAKE_MINT: SettlementOpReason.ValueType  # 1
"""*** MintEqualsBurnTlm ***

MintEqualsBurnTlm: Value transfer (credit/debit aka mint/burn)
"""
TLM_RELAY_BURN_EQUALS_MINT_APPLICATION_STAKE_BURN: SettlementOpReason.ValueType  # 2
TLM_RELAY_BURN_EQUALS_MINT_TOKENOMICS_CLAIM_DISTRIBUTION_MINT: SettlementOpReason.ValueType  # 19
TLM_RELAY_BURN_EQUALS_MINT_SUPPLIER_SHAREHOLDER_REWARD_DISTRIBUTION: SettlementOpReason.ValueType  # 4
"""MintEqualsBurnTlm: Reward distribution"""
TLM_RELAY_BURN_EQUALS_MINT_DAO_REWARD_DISTRIBUTION: SettlementOpReason.ValueType  # 15
TLM_RELAY_BURN_EQUALS_MINT_SOURCE_OWNER_REWARD_DISTRIBUTION: SettlementOpReason.ValueType  # 17
TLM_RELAY_BURN_EQUALS_MINT_APPLICATION_REWARD_DISTRIBUTION: SettlementOpReason.ValueType  # 18
TLM_RELAY_BURN_EQUALS_MINT_VALIDATOR_REWARD_DISTRIBUTION: SettlementOpReason.ValueType  # 20
TLM_RELAY_BURN_EQUALS_MINT_DELEGATOR_REWARD_DISTRIBUTION: SettlementOpReason.ValueType  # 23
TLM_GLOBAL_MINT_INFLATION: SettlementOpReason.ValueType  # 3
"""*** GlobalMintTLM ***

GlobalMintTLM: Inflation
"""
TLM_GLOBAL_MINT_DAO_REWARD_DISTRIBUTION: SettlementOpReason.ValueType  # 5
"""GlobalMintTLM: Reward distribution"""
TLM_GLOBAL_MINT_SUPPLIER_SHAREHOLDER_REWARD_DISTRIBUTION: SettlementOpReason.ValueType  # 7
TLM_GLOBAL_MINT_SOURCE_OWNER_REWARD_DISTRIBUTION: SettlementOpReason.ValueType  # 8
TLM_GLOBAL_MINT_APPLICATION_REWARD_DISTRIBUTION: SettlementOpReason.ValueType  # 9
TLM_GLOBAL_MINT_VALIDATOR_REWARD_DISTRIBUTION: SettlementOpReason.ValueType  # 21
TLM_GLOBAL_MINT_DELEGATOR_REWARD_DISTRIBUTION: SettlementOpReason.ValueType  # 24
TLM_GLOBAL_MINT_REIMBURSEMENT_REQUEST_ESCROW_DAO_TRANSFER: SettlementOpReason.ValueType  # 10
"""GlobalMintTLM: Self-servicing mitigation"""
TLM_GLOBAL_MINT_SUPPLIER_SHAREHOLDER_REWARD_MODULE_TRANSFER: SettlementOpReason.ValueType  # 13
"""GlobalMintTLM: Module accounting"""
TLM_GLOBAL_MINT_REIMBURSEMENT_REQUEST_ESCROW_MODULE_TRANSFER: SettlementOpReason.ValueType  # 14
Global___SettlementOpReason: _TypeAlias = SettlementOpReason  # noqa: Y015

@_typing.final
class ClaimSettlementResult(_message.Message):
    """ClaimSettlementResult holds the result of a single claim settlement: mint, burn, and transfer operations."""

    DESCRIPTOR: _descriptor.Descriptor

    CLAIM_FIELD_NUMBER: _builtins.int
    MINTS_FIELD_NUMBER: _builtins.int
    BURNS_FIELD_NUMBER: _builtins.int
    MOD_TO_MOD_TRANSFERS_FIELD_NUMBER: _builtins.int
    MOD_TO_ACCT_TRANSFERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def claim(self) -> _types_pb2.Claim: ...
    @_builtins.property
    def mints(self) -> _containers.RepeatedCompositeFieldContainer[Global___MintBurnOp]: ...
    @_builtins.property
    def burns(self) -> _containers.RepeatedCompositeFieldContainer[Global___MintBurnOp]: ...
    @_builtins.property
    def mod_to_mod_transfers(self) -> _containers.RepeatedCompositeFieldContainer[Global___ModToModTransfer]: ...
    @_builtins.property
    def mod_to_acct_transfers(self) -> _containers.RepeatedCompositeFieldContainer[Global___ModToAcctTransfer]: ...
    def __init__(
        self,
        *,
        claim: _types_pb2.Claim | None = ...,
        mints: _abc.Iterable[Global___MintBurnOp] | None = ...,
        burns: _abc.Iterable[Global___MintBurnOp] | None = ...,
        mod_to_mod_transfers: _abc.Iterable[Global___ModToModTransfer] | None = ...,
        mod_to_acct_transfers: _abc.Iterable[Global___ModToAcctTransfer] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["claim", b"claim"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["burns", b"burns", "claim", b"claim", "mints", b"mints", "mod_to_acct_transfers", b"mod_to_acct_transfers", "mod_to_mod_transfers", b"mod_to_mod_transfers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ClaimSettlementResult: _TypeAlias = ClaimSettlementResult  # noqa: Y015

@_typing.final
class MintBurnOp(_message.Message):
    """MintBurnOp holds the parameters of a single mint or burn operation."""

    DESCRIPTOR: _descriptor.Descriptor

    OP_REASON_FIELD_NUMBER: _builtins.int
    DESTINATIONMODULE_FIELD_NUMBER: _builtins.int
    COIN_FIELD_NUMBER: _builtins.int
    op_reason: Global___SettlementOpReason.ValueType
    DestinationModule: _builtins.str
    @_builtins.property
    def coin(self) -> _coin_pb2.Coin: ...
    def __init__(
        self,
        *,
        op_reason: Global___SettlementOpReason.ValueType = ...,
        DestinationModule: _builtins.str = ...,
        coin: _coin_pb2.Coin | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["coin", b"coin"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["DestinationModule", b"DestinationModule", "coin", b"coin", "op_reason", b"op_reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MintBurnOp: _TypeAlias = MintBurnOp  # noqa: Y015

@_typing.final
class ModToAcctTransfer(_message.Message):
    """ModToAcctTransfer holds the parameters of a single module to account transfer operation."""

    DESCRIPTOR: _descriptor.Descriptor

    OP_REASON_FIELD_NUMBER: _builtins.int
    SENDERMODULE_FIELD_NUMBER: _builtins.int
    RECIPIENTADDRESS_FIELD_NUMBER: _builtins.int
    COIN_FIELD_NUMBER: _builtins.int
    op_reason: Global___SettlementOpReason.ValueType
    SenderModule: _builtins.str
    RecipientAddress: _builtins.str
    """bech32 address"""
    @_builtins.property
    def coin(self) -> _coin_pb2.Coin: ...
    def __init__(
        self,
        *,
        op_reason: Global___SettlementOpReason.ValueType = ...,
        SenderModule: _builtins.str = ...,
        RecipientAddress: _builtins.str = ...,
        coin: _coin_pb2.Coin | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["coin", b"coin"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["RecipientAddress", b"RecipientAddress", "SenderModule", b"SenderModule", "coin", b"coin", "op_reason", b"op_reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ModToAcctTransfer: _TypeAlias = ModToAcctTransfer  # noqa: Y015

@_typing.final
class ModToModTransfer(_message.Message):
    """ModToModTransfer holds the parameters of a single module to module transfer operation."""

    DESCRIPTOR: _descriptor.Descriptor

    OP_REASON_FIELD_NUMBER: _builtins.int
    SENDERMODULE_FIELD_NUMBER: _builtins.int
    RECIPIENTMODULE_FIELD_NUMBER: _builtins.int
    COIN_FIELD_NUMBER: _builtins.int
    op_reason: Global___SettlementOpReason.ValueType
    SenderModule: _builtins.str
    RecipientModule: _builtins.str
    """This the semantic module named that can be found by searching for "ModuleName =" in the codebase"""
    @_builtins.property
    def coin(self) -> _coin_pb2.Coin: ...
    def __init__(
        self,
        *,
        op_reason: Global___SettlementOpReason.ValueType = ...,
        SenderModule: _builtins.str = ...,
        RecipientModule: _builtins.str = ...,
        coin: _coin_pb2.Coin | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["coin", b"coin"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["RecipientModule", b"RecipientModule", "SenderModule", b"SenderModule", "coin", b"coin", "op_reason", b"op_reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ModToModTransfer: _TypeAlias = ModToModTransfer  # noqa: Y015
