"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Params(_message.Message):
    """Params defines the parameters for the module."""

    DESCRIPTOR: _descriptor.Descriptor

    NUM_BLOCKS_PER_SESSION_FIELD_NUMBER: _builtins.int
    GRACE_PERIOD_END_OFFSET_BLOCKS_FIELD_NUMBER: _builtins.int
    CLAIM_WINDOW_OPEN_OFFSET_BLOCKS_FIELD_NUMBER: _builtins.int
    CLAIM_WINDOW_CLOSE_OFFSET_BLOCKS_FIELD_NUMBER: _builtins.int
    PROOF_WINDOW_OPEN_OFFSET_BLOCKS_FIELD_NUMBER: _builtins.int
    PROOF_WINDOW_CLOSE_OFFSET_BLOCKS_FIELD_NUMBER: _builtins.int
    SUPPLIER_UNBONDING_PERIOD_SESSIONS_FIELD_NUMBER: _builtins.int
    APPLICATION_UNBONDING_PERIOD_SESSIONS_FIELD_NUMBER: _builtins.int
    COMPUTE_UNITS_TO_TOKENS_MULTIPLIER_FIELD_NUMBER: _builtins.int
    GATEWAY_UNBONDING_PERIOD_SESSIONS_FIELD_NUMBER: _builtins.int
    COMPUTE_UNIT_COST_GRANULARITY_FIELD_NUMBER: _builtins.int
    num_blocks_per_session: _builtins.int
    """num_blocks_per_session is the number of blocks between the session start & end heights."""
    grace_period_end_offset_blocks: _builtins.int
    """grace_period_end_offset_blocks is the number of blocks, after the session end height,
    during which the supplier can still service payable relays.
    Suppliers will need to recreate a claim for the previous session (if already created) to
    get paid for the additional relays.
    """
    claim_window_open_offset_blocks: _builtins.int
    """claim_window_open_offset_blocks is the number of blocks after the session grace
    period height, at which the claim window opens.
    """
    claim_window_close_offset_blocks: _builtins.int
    """claim_window_close_offset_blocks is the number of blocks after the claim window
    open height, at which the claim window closes.
    """
    proof_window_open_offset_blocks: _builtins.int
    """proof_window_open_offset_blocks is the number of blocks after the claim window
    close height, at which the proof window opens.
    """
    proof_window_close_offset_blocks: _builtins.int
    """proof_window_close_offset_blocks is the number of blocks after the proof window
    open height, at which the proof window closes.
    """
    supplier_unbonding_period_sessions: _builtins.int
    """supplier_unbonding_period_sessions is the number of sessions that a supplier must wait after
    unstaking before their staked assets are moved to their account balance.
    Onchain business logic requires, and ensures, that the corresponding block count of the unbonding
    period will exceed the end of any active claim & proof lifecycles.
    """
    application_unbonding_period_sessions: _builtins.int
    """application_unbonding_period_sessions is the number of sessions that an application must wait after
    unstaking before their staked assets are moved to their account balance.
    Onchain business logic requires, and ensures, that the corresponding block count of the
    application unbonding period will exceed the end of its corresponding proof window close height.
    """
    compute_units_to_tokens_multiplier: _builtins.int
    """The amount of tokens that a compute unit should translate to when settling a session.
    It is denominated in fractional uPOKT (1/compute_unit_cost_granularity)
    DEV_NOTE: This used to be under x/tokenomics but has been moved here to avoid cyclic dependencies.
    """
    gateway_unbonding_period_sessions: _builtins.int
    """gateway_unbonding_period_sessions is the number of sessions that a gateway must wait after
    unstaking before their staked assets are moved to its account balance.
    """
    compute_unit_cost_granularity: _builtins.int
    """compute_unit_cost_granularity is the fraction of the base unit (uPOKT) used
    to represent the smallest price of a single compute unit.
    compute_unit_cost_granularity defines the smallest fraction of uPOKT that can represent
    the cost of a single compute unit.

    It acts as a denominator in the formula:

      compute_unit_cost_in_uPOKT = compute_units_to_tokens_multiplier / compute_unit_cost_granularity

    This enables high-precision pricing of compute units using integer math.
    For example:

    +-------------------------------+---------------------------------------------+
    | compute_unit_cost_granularity | compute_units_to_tokens_multiplier unit     |
    +-------------------------------+---------------------------------------------+
    | 1                             | uPOKT                                       |
    | 1_000                         | nPOKT (nanoPOKT, 1e-3 uPOKT)                |
    | 1_000_000                     | pPOKT (picoPOKT, 1e-6 uPOKT)                |
    +-------------------------------+---------------------------------------------+

    ⚠️ Note: This value is a configurable global network parameter (not a constant).
    It must be a power of 10, allowing precise denomination shifts without affecting
    ongoing sessions. This prevents sessions from settling using parameters that
    were not in effect during their creation.
    """
    def __init__(
        self,
        *,
        num_blocks_per_session: _builtins.int = ...,
        grace_period_end_offset_blocks: _builtins.int = ...,
        claim_window_open_offset_blocks: _builtins.int = ...,
        claim_window_close_offset_blocks: _builtins.int = ...,
        proof_window_open_offset_blocks: _builtins.int = ...,
        proof_window_close_offset_blocks: _builtins.int = ...,
        supplier_unbonding_period_sessions: _builtins.int = ...,
        application_unbonding_period_sessions: _builtins.int = ...,
        compute_units_to_tokens_multiplier: _builtins.int = ...,
        gateway_unbonding_period_sessions: _builtins.int = ...,
        compute_unit_cost_granularity: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application_unbonding_period_sessions", b"application_unbonding_period_sessions", "claim_window_close_offset_blocks", b"claim_window_close_offset_blocks", "claim_window_open_offset_blocks", b"claim_window_open_offset_blocks", "compute_unit_cost_granularity", b"compute_unit_cost_granularity", "compute_units_to_tokens_multiplier", b"compute_units_to_tokens_multiplier", "gateway_unbonding_period_sessions", b"gateway_unbonding_period_sessions", "grace_period_end_offset_blocks", b"grace_period_end_offset_blocks", "num_blocks_per_session", b"num_blocks_per_session", "proof_window_close_offset_blocks", b"proof_window_close_offset_blocks", "proof_window_open_offset_blocks", b"proof_window_open_offset_blocks", "supplier_unbonding_period_sessions", b"supplier_unbonding_period_sessions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Params: _TypeAlias = Params  # noqa: Y015

@_typing.final
class ParamsUpdate(_message.Message):
    """ParamsUpdate stores a snapshot of shared parameters
    along with the height at which they became effective.
    This enables historical parameter lookups for session calculations.
    """

    DESCRIPTOR: _descriptor.Descriptor

    EFFECTIVE_HEIGHT_FIELD_NUMBER: _builtins.int
    PARAMS_FIELD_NUMBER: _builtins.int
    effective_height: _builtins.int
    """effective_height is the block height at which these params became effective.
    Parameters are activated at session boundaries, not immediately upon governance change.
    """
    @_builtins.property
    def params(self) -> Global___Params:
        """params is the snapshot of shared params that were effective starting at effective_height."""

    def __init__(
        self,
        *,
        effective_height: _builtins.int = ...,
        params: Global___Params | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["effective_height", b"effective_height", "params", b"params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ParamsUpdate: _TypeAlias = ParamsUpdate  # noqa: Y015
