"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
NOTE that the `shared` package is not a Cosmos module,
but rather a manually created package to resolve circular type dependencies.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _RPCType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RPCTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_RPCType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    UNKNOWN_RPC: _RPCType.ValueType  # 0
    """Undefined RPC type"""
    GRPC: _RPCType.ValueType  # 1
    """gRPC"""
    WEBSOCKET: _RPCType.ValueType  # 2
    """WebSocket"""
    JSON_RPC: _RPCType.ValueType  # 3
    """JSON-RPC"""
    REST: _RPCType.ValueType  # 4
    """REST"""
    COMET_BFT: _RPCType.ValueType  # 5
    """CometBFT (REST + JSON-RPC)"""

class RPCType(_RPCType, metaclass=_RPCTypeEnumTypeWrapper):
    """Enum to define RPC types"""

UNKNOWN_RPC: RPCType.ValueType  # 0
"""Undefined RPC type"""
GRPC: RPCType.ValueType  # 1
"""gRPC"""
WEBSOCKET: RPCType.ValueType  # 2
"""WebSocket"""
JSON_RPC: RPCType.ValueType  # 3
"""JSON-RPC"""
REST: RPCType.ValueType  # 4
"""REST"""
COMET_BFT: RPCType.ValueType  # 5
"""CometBFT (REST + JSON-RPC)"""
Global___RPCType: _TypeAlias = RPCType  # noqa: Y015

class _ConfigOptions:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ConfigOptionsEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ConfigOptions.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    UNKNOWN_CONFIG: _ConfigOptions.ValueType  # 0
    """Undefined config option"""
    TIMEOUT: _ConfigOptions.ValueType  # 1
    """Timeout setting"""

class ConfigOptions(_ConfigOptions, metaclass=_ConfigOptionsEnumTypeWrapper):
    """Enum to define configuration options
    TODO_RESEARCH: Should these be configs, SLAs or something else? There will be more discussion once we get closer to implementing onchain QoS.
    """

UNKNOWN_CONFIG: ConfigOptions.ValueType  # 0
"""Undefined config option"""
TIMEOUT: ConfigOptions.ValueType  # 1
"""Timeout setting"""
Global___ConfigOptions: _TypeAlias = ConfigOptions  # noqa: Y015

@_typing.final
class Service(_message.Message):
    """Service message to encapsulate unique and semantic identifiers for a service on the network

    Next free index: 6
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    COMPUTE_UNITS_PER_RELAY_FIELD_NUMBER: _builtins.int
    OWNER_ADDRESS_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """For example, what if we want to request a session for a certain service but with some additional configs that identify it?
    Unique identifier for the service
    """
    name: _builtins.str
    """TODO_POST_MAINNET: Rename service.name to service.description
    (Optional) Human readable description of the service
    """
    compute_units_per_relay: _builtins.int
    """The cost of a single relay for this service in terms of compute units.
    Must be used alongside the global 'compute_units_to_tokens_multiplier' to calculate the cost of a relay for this service.
    cost_per_relay_for_specific_service = compute_units_per_relay_for_specific_service * compute_units_to_tokens_multiplier_global_value
    Compute units required per relay for this service
    """
    owner_address: _builtins.str
    """The owner address that created the service.
    It is the address that receives rewards based on the Service's onchain usage
    It is the only address that can update the service configuration (e.g. compute_units_per_relay),
    or make other updates to it.
    The Bech32 address of the service owner / creator
    """
    @_builtins.property
    def metadata(self) -> Global___Metadata:
        """Optional metadata containing an experimental API specification for the service.
        When exposed via JSON, this field is base64 encoded and MUST be <= 256 KiB when decoded.
        """

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        compute_units_per_relay: _builtins.int = ...,
        owner_address: _builtins.str = ...,
        metadata: Global___Metadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["metadata", b"metadata"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["compute_units_per_relay", b"compute_units_per_relay", "id", b"id", "metadata", b"metadata", "name", b"name", "owner_address", b"owner_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Service: _TypeAlias = Service  # noqa: Y015

@_typing.final
class ApplicationServiceConfig(_message.Message):
    """ApplicationServiceConfig holds the service configuration the application stakes for"""

    DESCRIPTOR: _descriptor.Descriptor

    SERVICE_ID_FIELD_NUMBER: _builtins.int
    service_id: _builtins.str
    """The Service ID for which the application is configured"""
    def __init__(
        self,
        *,
        service_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["service_id", b"service_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ApplicationServiceConfig: _TypeAlias = ApplicationServiceConfig  # noqa: Y015

@_typing.final
class SupplierServiceConfig(_message.Message):
    """SupplierServiceConfig holds the service configuration the supplier stakes for"""

    DESCRIPTOR: _descriptor.Descriptor

    SERVICE_ID_FIELD_NUMBER: _builtins.int
    ENDPOINTS_FIELD_NUMBER: _builtins.int
    REV_SHARE_FIELD_NUMBER: _builtins.int
    service_id: _builtins.str
    """The Service ID for which the supplier is configured"""
    @_builtins.property
    def endpoints(self) -> _containers.RepeatedCompositeFieldContainer[Global___SupplierEndpoint]:
        """List of endpoints for the service"""

    @_builtins.property
    def rev_share(self) -> _containers.RepeatedCompositeFieldContainer[Global___ServiceRevenueShare]:
        """List of revenue share configurations for the service"""

    def __init__(
        self,
        *,
        service_id: _builtins.str = ...,
        endpoints: _abc.Iterable[Global___SupplierEndpoint] | None = ...,
        rev_share: _abc.Iterable[Global___ServiceRevenueShare] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["endpoints", b"endpoints", "rev_share", b"rev_share", "service_id", b"service_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SupplierServiceConfig: _TypeAlias = SupplierServiceConfig  # noqa: Y015

@_typing.final
class SupplierEndpoint(_message.Message):
    """SupplierEndpoint message to hold service configuration details"""

    DESCRIPTOR: _descriptor.Descriptor

    URL_FIELD_NUMBER: _builtins.int
    RPC_TYPE_FIELD_NUMBER: _builtins.int
    CONFIGS_FIELD_NUMBER: _builtins.int
    url: _builtins.str
    """URL of the endpoint"""
    rpc_type: Global___RPCType.ValueType
    """Type of RPC exposed on the url above"""
    @_builtins.property
    def configs(self) -> _containers.RepeatedCompositeFieldContainer[Global___ConfigOption]:
        """Additional configuration options for the endpoint"""

    def __init__(
        self,
        *,
        url: _builtins.str = ...,
        rpc_type: Global___RPCType.ValueType = ...,
        configs: _abc.Iterable[Global___ConfigOption] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["configs", b"configs", "rpc_type", b"rpc_type", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SupplierEndpoint: _TypeAlias = SupplierEndpoint  # noqa: Y015

@_typing.final
class ServiceRevenueShare(_message.Message):
    """ServiceRevenueShare message to hold revenue share configuration details"""

    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    REV_SHARE_PERCENTAGE_FIELD_NUMBER: _builtins.int
    address: _builtins.str
    """The Bech32 address of the revenue share recipient"""
    rev_share_percentage: _builtins.int
    """The percentage of revenue share the recipient will receive"""
    def __init__(
        self,
        *,
        address: _builtins.str = ...,
        rev_share_percentage: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "rev_share_percentage", b"rev_share_percentage"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ServiceRevenueShare: _TypeAlias = ServiceRevenueShare  # noqa: Y015

@_typing.final
class ConfigOption(_message.Message):
    """Key-value wrapper for config options, as proto maps can't be keyed by enums"""

    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: Global___ConfigOptions.ValueType
    """Config option key"""
    value: _builtins.str
    """Config option value"""
    def __init__(
        self,
        *,
        key: Global___ConfigOptions.ValueType = ...,
        value: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConfigOption: _TypeAlias = ConfigOption  # noqa: Y015

@_typing.final
class Metadata(_message.Message):
    """Metadata message to hold additional metadata for a service.
    The raw bytes are stored on-chain and will be base64 encoded in JSON representations.

    Next free index: 2
    """

    DESCRIPTOR: _descriptor.Descriptor

    EXPERIMENTAL_API_SPECS_FIELD_NUMBER: _builtins.int
    experimental_api_specs: _builtins.bytes
    """EXPERIMENTAL: Serialized API spec limited to 256 KiB when decoded.
    TODO_FUTURE: support dedicated openapi_ / openrpc_ fields once formats stabilize.
    """
    def __init__(
        self,
        *,
        experimental_api_specs: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["experimental_api_specs", b"experimental_api_specs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Metadata: _TypeAlias = Metadata  # noqa: Y015
