"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from poktroll_clients.proto.cosmos.base.v1beta1 import coin_pb2 as _coin_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from poktroll_clients.proto.pocket.shared import service_pb2 as _service_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Supplier(_message.Message):
    """Supplier represents an actor in Pocket Network that provides RPC services"""

    DESCRIPTOR: _descriptor.Descriptor

    OWNER_ADDRESS_FIELD_NUMBER: _builtins.int
    OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    STAKE_FIELD_NUMBER: _builtins.int
    SERVICES_FIELD_NUMBER: _builtins.int
    UNSTAKE_SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    SERVICE_CONFIG_HISTORY_FIELD_NUMBER: _builtins.int
    owner_address: _builtins.str
    """Owner address that controls the staked funds and receives rewards by default
    Cannot be updated by the operator
    """
    operator_address: _builtins.str
    """Operator address managing the offchain server
    Immutable for supplier's lifespan - requires unstake/re-stake to change.
    Can update supplier configs except for owner address.
    """
    unstake_session_end_height: _builtins.int
    """Session end height when supplier initiated unstaking (0 if not unstaking)"""
    @_builtins.property
    def stake(self) -> _coin_pb2.Coin:
        """Total amount of staked uPOKT"""

    @_builtins.property
    def services(self) -> _containers.RepeatedCompositeFieldContainer[_service_pb2.SupplierServiceConfig]:
        """List of service configurations supported by this supplier"""

    @_builtins.property
    def service_config_history(self) -> _containers.RepeatedCompositeFieldContainer[Global___ServiceConfigUpdate]:
        """List of historical service configuration updates, tracking the suppliers
        services update and corresponding activation heights.
        """

    def __init__(
        self,
        *,
        owner_address: _builtins.str = ...,
        operator_address: _builtins.str = ...,
        stake: _coin_pb2.Coin | None = ...,
        services: _abc.Iterable[_service_pb2.SupplierServiceConfig] | None = ...,
        unstake_session_end_height: _builtins.int = ...,
        service_config_history: _abc.Iterable[Global___ServiceConfigUpdate] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stake", b"stake"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["operator_address", b"operator_address", "owner_address", b"owner_address", "service_config_history", b"service_config_history", "services", b"services", "stake", b"stake", "unstake_session_end_height", b"unstake_session_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Supplier: _TypeAlias = Supplier  # noqa: Y015

@_typing.final
class ServiceConfigUpdate(_message.Message):
    """ServiceConfigUpdate tracks a change in a supplier's service configurations
    at a specific block height, enabling tracking of configuration changes over time.
    This record helps maintain a complete history of service configs and their availability periods.
    """

    DESCRIPTOR: _descriptor.Descriptor

    OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    SERVICE_FIELD_NUMBER: _builtins.int
    ACTIVATION_HEIGHT_FIELD_NUMBER: _builtins.int
    DEACTIVATION_HEIGHT_FIELD_NUMBER: _builtins.int
    operator_address: _builtins.str
    """Operator address of the supplier corresponding to the service configuration change"""
    activation_height: _builtins.int
    """Block height at which this service configuration became active in the network"""
    deactivation_height: _builtins.int
    """Block height at which this service configuration was deactivated (0 if still active)
    For service configs scheduled for deactivation:
    - This field stores the block height when deactivation will occur
    - After deactivation, the config remains in history only as needed for claim settlement
    - Once no longer required for settlement, the config is automatically removed by
      the EndBlockerPruneSupplierServiceConfigHistory process
    """
    @_builtins.property
    def service(self) -> _service_pb2.SupplierServiceConfig:
        """The specific service configuration that was added, modified or scheduled for removal"""

    def __init__(
        self,
        *,
        operator_address: _builtins.str = ...,
        service: _service_pb2.SupplierServiceConfig | None = ...,
        activation_height: _builtins.int = ...,
        deactivation_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["service", b"service"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activation_height", b"activation_height", "deactivation_height", b"deactivation_height", "operator_address", b"operator_address", "service", b"service"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ServiceConfigUpdate: _TypeAlias = ServiceConfigUpdate  # noqa: Y015
