"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Coin(_message.Message):
    """Coin defines a token with a denomination and an amount.

    NOTE: The amount field is an Int which implements the custom method
    signatures required by gogoproto.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DENOM_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    denom: _builtins.str
    amount: _builtins.str
    def __init__(
        self,
        *,
        denom: _builtins.str = ...,
        amount: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "denom", b"denom"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Coin: _TypeAlias = Coin  # noqa: Y015

@_typing.final
class DecCoin(_message.Message):
    """DecCoin defines a token with a denomination and a decimal amount.

    NOTE: The amount field is an Dec which implements the custom method
    signatures required by gogoproto.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DENOM_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    denom: _builtins.str
    amount: _builtins.str
    def __init__(
        self,
        *,
        denom: _builtins.str = ...,
        amount: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "denom", b"denom"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DecCoin: _TypeAlias = DecCoin  # noqa: Y015

@_typing.final
class IntProto(_message.Message):
    """IntProto defines a Protobuf wrapper around an Int object.
    Deprecated: Prefer to use math.Int directly. It supports binary Marshal and Unmarshal.
    """

    DESCRIPTOR: _descriptor.Descriptor

    INT_FIELD_NUMBER: _builtins.int
    int: _builtins.str
    def __init__(
        self,
        *,
        int: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["int", b"int"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___IntProto: _TypeAlias = IntProto  # noqa: Y015

@_typing.final
class DecProto(_message.Message):
    """DecProto defines a Protobuf wrapper around a Dec object.
    Deprecated: Prefer to use math.LegacyDec directly. It supports binary Marshal and Unmarshal.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DEC_FIELD_NUMBER: _builtins.int
    dec: _builtins.str
    def __init__(
        self,
        *,
        dec: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dec", b"dec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DecProto: _TypeAlias = DecProto  # noqa: Y015
