"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Module(_message.Message):
    """Module is the config object for the module."""

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """authority defines the custom module authority.
    If not set, defaults to the governance module.
    """
    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authority", b"authority"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Module: _TypeAlias = Module  # noqa: Y015
