"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from poktroll_clients.proto.pocket.application import types_pb2 as _types_pb2
from poktroll_clients.proto.pocket.migration import morse_onchain_pb2 as _morse_onchain_pb2
from poktroll_clients.proto.pocket.shared import supplier_pb2 as _supplier_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class EventImportMorseClaimableAccounts(_message.Message):
    """EventImportMorseClaimableAccounts
    - Emitted when MorseClaimableAccounts are created on-chain
    - Represents import event for Morse claimable accounts
    """

    DESCRIPTOR: _descriptor.Descriptor

    CREATED_AT_HEIGHT_FIELD_NUMBER: _builtins.int
    MORSE_ACCOUNT_STATE_HASH_FIELD_NUMBER: _builtins.int
    NUM_ACCOUNTS_FIELD_NUMBER: _builtins.int
    created_at_height: _builtins.int
    """Shannon height at which MorseAccountState was created on-chain"""
    morse_account_state_hash: _builtins.bytes
    """On-chain computed sha256 hash of the MorseAccountState
    - Contains all imported MorseClaimableAccounts
    """
    num_accounts: _builtins.int
    """Number of claimable accounts (EOAs) imported from Morse state export
    - Account balances include consolidated application and supplier actor stakes
    """
    def __init__(
        self,
        *,
        created_at_height: _builtins.int = ...,
        morse_account_state_hash: _builtins.bytes = ...,
        num_accounts: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_at_height", b"created_at_height", "morse_account_state_hash", b"morse_account_state_hash", "num_accounts", b"num_accounts"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventImportMorseClaimableAccounts: _TypeAlias = EventImportMorseClaimableAccounts  # noqa: Y015

@_typing.final
class EventMorseAccountClaimed(_message.Message):
    """EventMorseAccountClaimed
    - Emitted when a MorseAccount is claimed on-chain
    Next index: 6
    """

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    SHANNON_DEST_ADDRESS_FIELD_NUMBER: _builtins.int
    MORSE_SRC_ADDRESS_FIELD_NUMBER: _builtins.int
    CLAIMED_BALANCE_FIELD_NUMBER: _builtins.int
    session_end_height: _builtins.int
    """Shannon session end height in which the claim was committed"""
    shannon_dest_address: _builtins.str
    """bech32-encoded Shannon address to mint claimed balance"""
    morse_src_address: _builtins.str
    """Hex-encoded Morse account address whose balance was claimed"""
    claimed_balance: _builtins.str
    """Unstaked balance claimed from Morse"""
    def __init__(
        self,
        *,
        session_end_height: _builtins.int = ...,
        shannon_dest_address: _builtins.str = ...,
        morse_src_address: _builtins.str = ...,
        claimed_balance: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["claimed_balance", b"claimed_balance", "morse_src_address", b"morse_src_address", "session_end_height", b"session_end_height", "shannon_dest_address", b"shannon_dest_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventMorseAccountClaimed: _TypeAlias = EventMorseAccountClaimed  # noqa: Y015

@_typing.final
class EventMorseApplicationClaimed(_message.Message):
    """EventMorseApplicationClaimed
    - Emitted when a MorseAccount is claimed on-chain as a staked application
    Next index: 8
    """

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    MORSE_SRC_ADDRESS_FIELD_NUMBER: _builtins.int
    APPLICATION_FIELD_NUMBER: _builtins.int
    CLAIMED_BALANCE_FIELD_NUMBER: _builtins.int
    CLAIMED_APPLICATION_STAKE_FIELD_NUMBER: _builtins.int
    session_end_height: _builtins.int
    """Shannon session end height in which the claim was committed"""
    morse_src_address: _builtins.str
    """Hex-encoded Morse account address whose balance was claimed"""
    claimed_balance: _builtins.str
    """Unstaked balance claimed from Morse"""
    claimed_application_stake: _builtins.str
    """Application stake claimed as a result of the claim
    - Equivalent to Morse application staked amount
    """
    @_builtins.property
    def application(self) -> _types_pb2.Application:
        """Application staked as a result of the claim
        - Mirrors Morse application stake
        """

    def __init__(
        self,
        *,
        session_end_height: _builtins.int = ...,
        morse_src_address: _builtins.str = ...,
        application: _types_pb2.Application | None = ...,
        claimed_balance: _builtins.str = ...,
        claimed_application_stake: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["application", b"application"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application", b"application", "claimed_application_stake", b"claimed_application_stake", "claimed_balance", b"claimed_balance", "morse_src_address", b"morse_src_address", "session_end_height", b"session_end_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventMorseApplicationClaimed: _TypeAlias = EventMorseApplicationClaimed  # noqa: Y015

@_typing.final
class EventMorseSupplierClaimed(_message.Message):
    """EventMorseSupplierClaimed
    - Emitted when a MorseAccount is claimed on-chain as a staked Supplier
    Next index: 11
    """

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    CLAIMED_BALANCE_FIELD_NUMBER: _builtins.int
    MORSE_NODE_ADDRESS_FIELD_NUMBER: _builtins.int
    MORSE_OUTPUT_ADDRESS_FIELD_NUMBER: _builtins.int
    CLAIM_SIGNER_TYPE_FIELD_NUMBER: _builtins.int
    CLAIMED_SUPPLIER_STAKE_FIELD_NUMBER: _builtins.int
    SUPPLIER_FIELD_NUMBER: _builtins.int
    session_end_height: _builtins.int
    """Shannon session end height in which the claim was committed"""
    claimed_balance: _builtins.str
    """Unstaked balance claimed from Morse"""
    morse_node_address: _builtins.str
    """The hex-encoded address of the Morse non-custodial (i.e. operator) account.
    - Unstaked balance was migrated 1:1
    - Stake was migrated 1:1 from morse_node_address to shannon_operator_address
    - Morse non-custodial (i.e. operator) address.
    If morse_output_address was not set, this is the custodial address.
    - See 'pocket nodes --help' for more information. Note that this refers to the Morse CLI.
    E.g.: 00f9900606fa3d5c9179fc0c8513078a53a2073e
    """
    morse_output_address: _builtins.str
    """ONLY applicable to Morse node/supplier accounts.
    Hex-encoded address of the Morse output account/wallet associated with the Morse node/supplier.
    - E.g.: 00f9900606fa3d5c9179fc0c8513078a53a2073e
    - Morse custodial (i.e. owner) address, which owned the staked tokens of the operator.
      See 'pocket nodes --help' for more information. Note that this refers to the Morse CLI.
    """
    claim_signer_type: _morse_onchain_pb2.MorseSupplierClaimSignerType.ValueType
    """The type of supplier claim signer, indicating which actor executed the claim
    and whether it was a custodial or non-custodial claim.
    - MORSE_SUPPLIER_CLAIM_SIGNER_TYPE_NON_CUSTODIAL_SIGNED_BY_ADDR
    - MORSE_SUPPLIER_CLAIM_SIGNER_TYPE_CUSTODIAL_SIGNED_BY_OPERATOR
    - MORSE_SUPPLIER_CLAIM_SIGNER_TYPE_CUSTODIAL_SIGNED_BY_OWNER
    """
    claimed_supplier_stake: _builtins.str
    """Supplier stake claimed as a result of the claim
    - Equivalent to Morse supplier staked amount
    """
    @_builtins.property
    def supplier(self) -> _supplier_pb2.Supplier:
        """Supplier staked as a result of the claim
        - Mirrors Morse supplier stake
        """

    def __init__(
        self,
        *,
        session_end_height: _builtins.int = ...,
        claimed_balance: _builtins.str = ...,
        morse_node_address: _builtins.str = ...,
        morse_output_address: _builtins.str = ...,
        claim_signer_type: _morse_onchain_pb2.MorseSupplierClaimSignerType.ValueType = ...,
        claimed_supplier_stake: _builtins.str = ...,
        supplier: _supplier_pb2.Supplier | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["supplier", b"supplier"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["claim_signer_type", b"claim_signer_type", "claimed_balance", b"claimed_balance", "claimed_supplier_stake", b"claimed_supplier_stake", "morse_node_address", b"morse_node_address", "morse_output_address", b"morse_output_address", "session_end_height", b"session_end_height", "supplier", b"supplier"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventMorseSupplierClaimed: _TypeAlias = EventMorseSupplierClaimed  # noqa: Y015

@_typing.final
class EventMorseAccountRecovered(_message.Message):
    """EventMorseAccountRecovered
    - Emitted when a Morse account is recovered on-chain
    Next index: 6
    """

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    RECOVERED_BALANCE_FIELD_NUMBER: _builtins.int
    SHANNON_DEST_ADDRESS_FIELD_NUMBER: _builtins.int
    MORSE_SRC_ADDRESS_FIELD_NUMBER: _builtins.int
    session_end_height: _builtins.int
    """The session end height (on Shannon) in which the recovery was committed (i.e. claimed)."""
    recovered_balance: _builtins.str
    """The total balance which was recovered:
    - Includes both unstaked and staked balances (consolidated)
    - Auto-liquidates both unstaked and staked balances at once
    """
    shannon_dest_address: _builtins.str
    """The bech32-encoded address of the Shannon account to which the recovered balance was minted."""
    morse_src_address: _builtins.str
    """The hex-encoded address of the Morse account whose balance and stakes have been recovered.
    This address MUST be in the recovery allow list and could be of types such as:
    - Unreachable/Locked EOA, Supplier or Application address
    - Module account
    - Invalid address (too short, too long, or non-hexadecimal format)
    """
    def __init__(
        self,
        *,
        session_end_height: _builtins.int = ...,
        recovered_balance: _builtins.str = ...,
        shannon_dest_address: _builtins.str = ...,
        morse_src_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["morse_src_address", b"morse_src_address", "recovered_balance", b"recovered_balance", "session_end_height", b"session_end_height", "shannon_dest_address", b"shannon_dest_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventMorseAccountRecovered: _TypeAlias = EventMorseAccountRecovered  # noqa: Y015

@_typing.final
class EventMorseAccountRecoveredAdmin(_message.Message):
    """EventMorseAccountRecoveredAdmin
    - Emitted when a Morse account is recovered using admin bypass (without allowlist check)
    - This event includes an admin flag to distinguish from regular recoveries for audit purposes
    Next index: 6
    """

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_END_HEIGHT_FIELD_NUMBER: _builtins.int
    RECOVERED_BALANCE_FIELD_NUMBER: _builtins.int
    SHANNON_DEST_ADDRESS_FIELD_NUMBER: _builtins.int
    MORSE_SRC_ADDRESS_FIELD_NUMBER: _builtins.int
    IS_ADMIN_RECOVERY_FIELD_NUMBER: _builtins.int
    session_end_height: _builtins.int
    """The session end height (on Shannon) in which the recovery was committed."""
    recovered_balance: _builtins.str
    """The total balance which was recovered (both unstaked and staked balances)."""
    shannon_dest_address: _builtins.str
    """The bech32-encoded address of the Shannon account to which the recovered balance was minted."""
    morse_src_address: _builtins.str
    """The hex-encoded address of the Morse account whose balance and stakes have been recovered.
    NOTE: This address was NOT checked against the allowlist - admin recovery bypasses allowlist validation.
    """
    is_admin_recovery: _builtins.bool
    """Flag to indicate this was an admin recovery (always true for this event type).
    Useful for filtering/monitoring admin recoveries vs regular recoveries.
    """
    def __init__(
        self,
        *,
        session_end_height: _builtins.int = ...,
        recovered_balance: _builtins.str = ...,
        shannon_dest_address: _builtins.str = ...,
        morse_src_address: _builtins.str = ...,
        is_admin_recovery: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["is_admin_recovery", b"is_admin_recovery", "morse_src_address", b"morse_src_address", "recovered_balance", b"recovered_balance", "session_end_height", b"session_end_height", "shannon_dest_address", b"shannon_dest_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EventMorseAccountRecoveredAdmin: _TypeAlias = EventMorseAccountRecoveredAdmin  # noqa: Y015
