"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Types in this file are ONLY present to facilitate the verifiability of the
migration state from Morse to Shannon.

These types reproduce a 1:1 de/serialization for the corresponding Morse data structures
but are not completely identical to their Morse counterparts, not all of which are defined
as protobuf types in the Morse codebase.

Morse leverages pb.Any types, as well as the gogoproto.casttype option in several places.
All usages of pb.Any have been replaced with equivalent protobuf types
(i.e. an interstitial type with `type` and/or `value` field(s)).
All usages of gogoproto.casttype which previously referenced Morse data structures have been removed.
A few specific fields have retained this option where the type is changed to the underlying
external lib type that the Morse type was wrapping (e.g. address and public key fields).

These types are used by the migration subcommand to transform
the Morse state export into the Shannon state import like so:
 $ pocketd tx migration collect-morse-accounts ...

CRITICAL: These types are offchain and ARE NOT persisted onchain (Shannon) at any point.
"""

from collections import abc as _abc
from poktroll_clients.proto.cosmos.base.v1beta1 import coin_pb2 as _coin_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MorseStateExport(_message.Message):
    """MorseStateExport is the data structure that is serialized and output when running:
     $ pocket utils export-genesis-for-reset ...

    Ref: https://editor.swagger.io/?url=https://raw.githubusercontent.com/pokt-network/pocket-core/staging/doc/specs/rpc-spec.yaml#operations-query-post_query_state
    """

    DESCRIPTOR: _descriptor.Descriptor

    APP_HASH_FIELD_NUMBER: _builtins.int
    APP_STATE_FIELD_NUMBER: _builtins.int
    app_hash: _builtins.str
    """app_hash is the Morse tendermint state hash."""
    @_builtins.property
    def app_state(self) -> Global___MorseTendermintAppState:
        """app_state is the entire Morse tendermint application state."""

    def __init__(
        self,
        *,
        app_hash: _builtins.str = ...,
        app_state: Global___MorseTendermintAppState | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["app_state", b"app_state"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_hash", b"app_hash", "app_state", b"app_state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MorseStateExport: _TypeAlias = MorseStateExport  # noqa: Y015

@_typing.final
class MorseTendermintAppState(_message.Message):
    """MorseTendermintAppState is the tendermint application state for the Morse tendermint
    application; not to be confused with the pokt protocol actor.
    It is constructed in Morse via `PocketCoreApp#ExportAppState()`.

    See: https://github.com/pokt-network/pocket-core/blob/5fa61920aa9d45ca6bf9e01e863134e242c95fa7/app/pocket.go#L142
    """

    DESCRIPTOR: _descriptor.Descriptor

    APPLICATION_FIELD_NUMBER: _builtins.int
    AUTH_FIELD_NUMBER: _builtins.int
    POS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def application(self) -> Global___MorseApplications: ...
    @_builtins.property
    def auth(self) -> Global___MorseAuth: ...
    @_builtins.property
    def pos(self) -> Global___MorsePos: ...
    def __init__(
        self,
        *,
        application: Global___MorseApplications | None = ...,
        auth: Global___MorseAuth | None = ...,
        pos: Global___MorsePos | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["application", b"application", "auth", b"auth", "pos", b"pos"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application", b"application", "auth", b"auth", "pos", b"pos"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MorseTendermintAppState: _TypeAlias = MorseTendermintAppState  # noqa: Y015

@_typing.final
class MorseApplications(_message.Message):
    """A wrapper around the list of MorseApplications, necessary in order to conform to the Morse genesis structure.
    It encapsulates the minimum information required to import Morse applications.

    See: https://github.com/pokt-network/pocket-core/blob/staging/x/apps/types/genesis.go#L4
    """

    DESCRIPTOR: _descriptor.Descriptor

    APPLICATIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def applications(self) -> _containers.RepeatedCompositeFieldContainer[Global___MorseApplication]: ...
    def __init__(
        self,
        *,
        applications: _abc.Iterable[Global___MorseApplication] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["applications", b"applications"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MorseApplications: _TypeAlias = MorseApplications  # noqa: Y015

@_typing.final
class MorseAuth(_message.Message):
    """A wrapper around a list of MorseAuthAccount.
    It encapsulates the minimum information required to import Morse accounts.

    See: https://github.com/pokt-network/pocket-core/blob/staging/x/auth/types/genesis.go#L9
    """

    DESCRIPTOR: _descriptor.Descriptor

    ACCOUNTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def accounts(self) -> _containers.RepeatedCompositeFieldContainer[Global___MorseAuthAccount]: ...
    def __init__(
        self,
        *,
        accounts: _abc.Iterable[Global___MorseAuthAccount] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accounts", b"accounts"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MorseAuth: _TypeAlias = MorseAuth  # noqa: Y015

@_typing.final
class MorseAuthAccount(_message.Message):
    """MorseAuthAccount:
    * Wraps MorseAuthAccount information to conform to Morse genesis structure
    * Can represent EITHER an externally owned account OR a module account
    """

    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    type: _builtins.str
    value: _builtins.bytes
    """value is a EITHER a JSON-encoded MorseAccount or a MorseModuleAccount."""
    def __init__(
        self,
        *,
        type: _builtins.str = ...,
        value: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["type", b"type", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MorseAuthAccount: _TypeAlias = MorseAuthAccount  # noqa: Y015

@_typing.final
class MorsePos(_message.Message):
    """A wrapper around the list of Morse suppliers (aka "validators", "nodes", of "servicers").
    It is necessary to conform to the Morse genesis structure.

    See: https://github.com/pokt-network/pocket-core/blob/staging/x/nodes/types/genesis.go#L8
    """

    DESCRIPTOR: _descriptor.Descriptor

    VALIDATORS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def validators(self) -> _containers.RepeatedCompositeFieldContainer[Global___MorseValidator]: ...
    def __init__(
        self,
        *,
        validators: _abc.Iterable[Global___MorseValidator] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["validators", b"validators"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MorsePos: _TypeAlias = MorsePos  # noqa: Y015

@_typing.final
class MorseApplication(_message.Message):
    """MorseApplication is a subset of the Morse ProtoApplication type.
    It encapsulates the minimum information required to import Morse applications.

    See: https://github.com/pokt-network/pocket-core/blob/staging/proto/x/apps/apps.proto#L16
    Next free index: 9
    """

    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    PUBLIC_KEY_FIELD_NUMBER: _builtins.int
    JAILED_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    STAKED_TOKENS_FIELD_NUMBER: _builtins.int
    UNSTAKING_TIME_FIELD_NUMBER: _builtins.int
    address: _builtins.bytes
    """Address is a binary representation of the address corresponding
    to a Morse application's ed25519 public key.
    """
    public_key: _builtins.bytes
    """PublicKey is the binary representation of a Morse application's ed25519 public key."""
    jailed: _builtins.bool
    """TODO_MAINNET_MIGRATION(@Olshansk):  Should status and/or jailed be considered during the migration, and if so, how?"""
    status: _builtins.int
    staked_tokens: _builtins.str
    """The string representation of the BigInt amount of upokt."""
    @_builtins.property
    def unstaking_time(self) -> _timestamp_pb2.Timestamp:
        """The ISO 8601 UTC timestamp after which the Morse node/supplier unbonding period will have elapsed.
        It reflects the "unbonding completion time" of the Morse node/supplier, but is called "unstaking time" to comply with necessary Morse data structures.
        """

    def __init__(
        self,
        *,
        address: _builtins.bytes = ...,
        public_key: _builtins.bytes = ...,
        jailed: _builtins.bool = ...,
        status: _builtins.int = ...,
        staked_tokens: _builtins.str = ...,
        unstaking_time: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["unstaking_time", b"unstaking_time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "jailed", b"jailed", "public_key", b"public_key", "staked_tokens", b"staked_tokens", "status", b"status", "unstaking_time", b"unstaking_time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MorseApplication: _TypeAlias = MorseApplication  # noqa: Y015

@_typing.final
class MorseValidator(_message.Message):
    """MorseValidator is a subset of the Morse ProtoValidator type.
    It encapsulates the minimum information required to import Morse suppliers (aka "servicers" or "validators").

    See: https://github.com/pokt-network/pocket-core/blob/staging/proto/x/pos/types.proto#L16
    Next free index: 10
    """

    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    PUBLIC_KEY_FIELD_NUMBER: _builtins.int
    JAILED_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    STAKED_TOKENS_FIELD_NUMBER: _builtins.int
    UNSTAKING_TIME_FIELD_NUMBER: _builtins.int
    OUTPUT_ADDRESS_FIELD_NUMBER: _builtins.int
    address: _builtins.bytes
    """Morse non-custodial (i.e. operator) address. If output_address is not set, this is the custodial address.
    Binary representation of the Morse address corresponding to a Morse node's ed25519 public key.
    See 'pocket nodes --help' for more information. Note that this refers to the Morse CLI.
    """
    public_key: _builtins.bytes
    """Binary representation of a Morse node's ed25519 public key."""
    jailed: _builtins.bool
    """TODO_MAINNET_MIGRATION(@Olshansk):  Should status and/or jailed be considered during the migration, and if so, how?"""
    status: _builtins.int
    staked_tokens: _builtins.str
    """The string representation of the BigInt amount of upokt."""
    output_address: _builtins.bytes
    """Morse custodial (i.e. owner) address, which owns the staked tokens of the operator.
    Binary representation of the Morse address corresponding to a Morse account's ed25519 public key.
    See 'pocket nodes --help' for more information. Note that this refers to the Morse CLI.
    """
    @_builtins.property
    def unstaking_time(self) -> _timestamp_pb2.Timestamp:
        """The ISO 8601 UTC timestamp after which the Morse node/supplier unbonding period will have elapsed.
        It reflects the "unbonding completion time" of the Morse node/supplier, but is called "unstaking time" to comply with necessary Morse data structures.
        """

    def __init__(
        self,
        *,
        address: _builtins.bytes = ...,
        public_key: _builtins.bytes = ...,
        jailed: _builtins.bool = ...,
        status: _builtins.int = ...,
        staked_tokens: _builtins.str = ...,
        unstaking_time: _timestamp_pb2.Timestamp | None = ...,
        output_address: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["unstaking_time", b"unstaking_time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "jailed", b"jailed", "output_address", b"output_address", "public_key", b"public_key", "staked_tokens", b"staked_tokens", "status", b"status", "unstaking_time", b"unstaking_time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MorseValidator: _TypeAlias = MorseValidator  # noqa: Y015

@_typing.final
class MorseAccount(_message.Message):
    """MorseAccount is an analog of the Morse ProtoBaseAccount type.
    It encapsulates the minimum information required to import accounts.

    See: https://github.com/pokt-network/pocket-core/blob/staging/proto/x/auth/auth.proto#L14.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    PUB_KEY_FIELD_NUMBER: _builtins.int
    COINS_FIELD_NUMBER: _builtins.int
    address: _builtins.bytes
    """A hex-encoded representation of the address corresponding to a Morse application's ed25519 public key."""
    @_builtins.property
    def pub_key(self) -> Global___MorsePublicKey:
        """The ed25519 public key of the account."""

    @_builtins.property
    def coins(self) -> _containers.RepeatedCompositeFieldContainer[_coin_pb2.Coin]:
        """The account balance; this does not include any actor stakes."""

    def __init__(
        self,
        *,
        address: _builtins.bytes = ...,
        pub_key: Global___MorsePublicKey | None = ...,
        coins: _abc.Iterable[_coin_pb2.Coin] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pub_key", b"pub_key"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "coins", b"coins", "pub_key", b"pub_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MorseAccount: _TypeAlias = MorseAccount  # noqa: Y015

@_typing.final
class MorsePublicKey(_message.Message):
    """MorsePublicKey is required to conform to the encoding of the Morse state export.
    NB: All Morse account public keys will be ed25519 keys by definition.
    """

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.bytes
    def __init__(
        self,
        *,
        value: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MorsePublicKey: _TypeAlias = MorsePublicKey  # noqa: Y015

@_typing.final
class MorseModuleAccount(_message.Message):
    """MorseModuleAccount is the module account type for Morse, it wraps a MorseAccount
    and has a unique name, which is used instead of the address.
    """

    DESCRIPTOR: _descriptor.Descriptor

    BASE_ACCOUNT_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    @_builtins.property
    def base_account(self) -> Global___MorseAccount:
        """DEV_NOTE: the JSON tag is intentionally cased contrary to convention to match the real-world Morse state export."""

    def __init__(
        self,
        *,
        base_account: Global___MorseAccount | None = ...,
        name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["base_account", b"base_account"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["base_account", b"base_account", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MorseModuleAccount: _TypeAlias = MorseModuleAccount  # noqa: Y015
