"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from poktroll_clients.proto.cosmos.base.v1beta1 import coin_pb2 as _coin_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _MorseSupplierClaimSignerType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _MorseSupplierClaimSignerTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_MorseSupplierClaimSignerType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    MORSE_SUPPLIER_CLAIM_SIGNER_TYPE_UNSPECIFIED: _MorseSupplierClaimSignerType.ValueType  # 0
    """Unspecified signer type"""
    MORSE_SUPPLIER_CLAIM_SIGNER_TYPE_CUSTODIAL_SIGNED_BY_NODE_ADDR: _MorseSupplierClaimSignerType.ValueType  # 1
    """signer === addr === operator === owner
    Custodial signer type
    - The Morse node address is NOT EMPTY (i.e. operator)
    - The Morse output address is EMPTY (i.e. owner)
    - Implies that the operator and owner are THE SAME offchain identity
    """
    MORSE_SUPPLIER_CLAIM_SIGNER_TYPE_NON_CUSTODIAL_SIGNED_BY_NODE_ADDR: _MorseSupplierClaimSignerType.ValueType  # 2
    """signer === operator === addr && owner !== operator
    Non-custodial signer type
    - The Morse node address is NOT EMPTY (i.e. operator)
    - The Morse output address is NOT EMPTY (i.e. owner)
    - Implies that the operator and owner are MOST LIKELY DIFFERENT offchain identities
    - The operator is the one signing the supplier claim
    """
    MORSE_SUPPLIER_CLAIM_SIGNER_TYPE_NON_CUSTODIAL_SIGNED_BY_OWNER: _MorseSupplierClaimSignerType.ValueType  # 3
    """signer === owner && owner !== addr
    Owner non-custodial signer type
    - The Morse node address is EMPTY (i.e. operator)
    - The Morse output address is NOT EMPTY (i.e. owner)
    - Implies that the operator and owner are MOST LIKELY different offchain identities
    - The owner is the one signing the supplier claim
    """

class MorseSupplierClaimSignerType(_MorseSupplierClaimSignerType, metaclass=_MorseSupplierClaimSignerTypeEnumTypeWrapper):
    """MorseSupplierClaimSignerType
    - Enum for Morse supplier claim signer type
    """

MORSE_SUPPLIER_CLAIM_SIGNER_TYPE_UNSPECIFIED: MorseSupplierClaimSignerType.ValueType  # 0
"""Unspecified signer type"""
MORSE_SUPPLIER_CLAIM_SIGNER_TYPE_CUSTODIAL_SIGNED_BY_NODE_ADDR: MorseSupplierClaimSignerType.ValueType  # 1
"""signer === addr === operator === owner
Custodial signer type
- The Morse node address is NOT EMPTY (i.e. operator)
- The Morse output address is EMPTY (i.e. owner)
- Implies that the operator and owner are THE SAME offchain identity
"""
MORSE_SUPPLIER_CLAIM_SIGNER_TYPE_NON_CUSTODIAL_SIGNED_BY_NODE_ADDR: MorseSupplierClaimSignerType.ValueType  # 2
"""signer === operator === addr && owner !== operator
Non-custodial signer type
- The Morse node address is NOT EMPTY (i.e. operator)
- The Morse output address is NOT EMPTY (i.e. owner)
- Implies that the operator and owner are MOST LIKELY DIFFERENT offchain identities
- The operator is the one signing the supplier claim
"""
MORSE_SUPPLIER_CLAIM_SIGNER_TYPE_NON_CUSTODIAL_SIGNED_BY_OWNER: MorseSupplierClaimSignerType.ValueType  # 3
"""signer === owner && owner !== addr
Owner non-custodial signer type
- The Morse node address is EMPTY (i.e. operator)
- The Morse output address is NOT EMPTY (i.e. owner)
- Implies that the operator and owner are MOST LIKELY different offchain identities
- The owner is the one signing the supplier claim
"""
Global___MorseSupplierClaimSignerType: _TypeAlias = MorseSupplierClaimSignerType  # noqa: Y015

@_typing.final
class MorseAccountState(_message.Message):
    """MorseAccountState
    - Onchain representation of all account state to be migrated from Morse
    - NEVER persisted onchain
    - Dependency of the MsgImportMorseClaimableAccount handler
    - Main purpose: exposes #GetHash() for verifying integrity of all MorseClaimableAccounts
    """

    DESCRIPTOR: _descriptor.Descriptor

    ACCOUNTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def accounts(self) -> _containers.RepeatedCompositeFieldContainer[Global___MorseClaimableAccount]: ...
    def __init__(
        self,
        *,
        accounts: _abc.Iterable[Global___MorseClaimableAccount] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accounts", b"accounts"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MorseAccountState: _TypeAlias = MorseAccountState  # noqa: Y015

@_typing.final
class MorseClaimableAccount(_message.Message):
    """MorseClaimableAccount
    - Onchain (persisted) representation of a Morse account claimable as part of Morse -> Shannon migration
    - Created during MorseAccountState import (see: MsgImportMorseClaimableAccount)
    - Created ONLY ONCE and NEVER deleted (per morse_src_address per network / re-genesis),
      unless the allow_morse_account_import_overwrite migration param is enabled
    - Updated ONLY ONCE, when claimed (per morse_src_address per network / re-genesis)
    Next free index: 11
    """

    DESCRIPTOR: _descriptor.Descriptor

    SHANNON_DEST_ADDRESS_FIELD_NUMBER: _builtins.int
    MORSE_SRC_ADDRESS_FIELD_NUMBER: _builtins.int
    UNSTAKED_BALANCE_FIELD_NUMBER: _builtins.int
    SUPPLIER_STAKE_FIELD_NUMBER: _builtins.int
    APPLICATION_STAKE_FIELD_NUMBER: _builtins.int
    CLAIMED_AT_HEIGHT_FIELD_NUMBER: _builtins.int
    MORSE_OUTPUT_ADDRESS_FIELD_NUMBER: _builtins.int
    UNSTAKING_TIME_FIELD_NUMBER: _builtins.int
    shannon_dest_address: _builtins.str
    """bech32-encoded address of the Shannon account to mint claimed balance
    Intended to remain empty until the account is claimed
    """
    morse_src_address: _builtins.str
    """Hex-encoded address of the Morse account whose balance will be claimed.
    If this MorseClaimableAccount represents a Morse node/supplier:
      - Morse non-custodial (i.e. operator) address.
      - If morse_output_address is not set, this is the custodial address.
      - See 'pocket nodes --help' for more information. Note that this refers to the Morse CLI.
    """
    claimed_at_height: _builtins.int
    """Shannon height at which the account was claimed
    Intended to remain empty until the account is claimed
    """
    morse_output_address: _builtins.str
    """ONLY applicable to Morse node/supplier accounts.
    Hex-encoded address of the Morse output account/wallet associated with the Morse node/supplier.
    - E.g.: 00f9900606fa3d5c9179fc0c8513078a53a2073e
    - Morse custodial (i.e. owner) address, which owns the staked tokens of the operator.
      See 'pocket nodes --help' for more information. Note that this refers to the Morse CLI.
    """
    @_builtins.property
    def unstaked_balance(self) -> _coin_pb2.Coin:
        """Unstaked upokt tokens (account balance) available for claiming"""

    @_builtins.property
    def supplier_stake(self) -> _coin_pb2.Coin:
        """Staked tokens for supplier actor corresponding to this account address
        DEV_NOTE: Context for Morse:
        - Supplier = Servicer or Node (not a full node) in Morse
        - All Validators are Servicers; not all Servicers are Validators
        - Top 100 staked Servicers are validators (automatic)
        - Only accounts for servicer stake balance transition
        TODO_MAINNET(@Olshansk): Develop strategy for bootstrapping validators in Shannon with cosmos ecosystem
        """

    @_builtins.property
    def application_stake(self) -> _coin_pb2.Coin:
        """Staked tokens for application actor corresponding to this account address"""

    @_builtins.property
    def unstaking_time(self) -> _timestamp_pb2.Timestamp:
        """The ISO 8601 UTC timestamp after which the Morse node/supplier unbonding period will have elapsed.
        It reflects the "unbonding completion time" of the Morse node/supplier, but is called "unstaking time" to comply with necessary Morse data structures.
        """

    def __init__(
        self,
        *,
        shannon_dest_address: _builtins.str = ...,
        morse_src_address: _builtins.str = ...,
        unstaked_balance: _coin_pb2.Coin | None = ...,
        supplier_stake: _coin_pb2.Coin | None = ...,
        application_stake: _coin_pb2.Coin | None = ...,
        claimed_at_height: _builtins.int = ...,
        morse_output_address: _builtins.str = ...,
        unstaking_time: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["application_stake", b"application_stake", "supplier_stake", b"supplier_stake", "unstaked_balance", b"unstaked_balance", "unstaking_time", b"unstaking_time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["application_stake", b"application_stake", "claimed_at_height", b"claimed_at_height", "morse_output_address", b"morse_output_address", "morse_src_address", b"morse_src_address", "shannon_dest_address", b"shannon_dest_address", "supplier_stake", b"supplier_stake", "unstaked_balance", b"unstaked_balance", "unstaking_time", b"unstaking_time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MorseClaimableAccount: _TypeAlias = MorseClaimableAccount  # noqa: Y015
