"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Params(_message.Message):
    """Params defines the parameters for the module.
    Next free index: 4
    """

    DESCRIPTOR: _descriptor.Descriptor

    WAIVE_MORSE_CLAIM_GAS_FEES_FIELD_NUMBER: _builtins.int
    ALLOW_MORSE_ACCOUNT_IMPORT_OVERWRITE_FIELD_NUMBER: _builtins.int
    MORSE_ACCOUNT_CLAIMING_ENABLED_FIELD_NUMBER: _builtins.int
    waive_morse_claim_gas_fees: _builtins.bool
    """waive_morse_claim_gas_fees is a feature flag used to enable/disable the waiving of gas fees for txs that:
    - Contain exactly one secp256k1 signer
    - Contain at least one Morse account/actor claim messages
    - Do not contain any other messages other than Morse account/actor claim messages
    """
    allow_morse_account_import_overwrite: _builtins.bool
    """allow_morse_account_import_overwrite is a feature flag which is used to enable/disable
    the re-importing of Morse claimable accounts by the authority.
    Such a re-import will:
    - Ignore (i.e. leave) ALL claimed destination Shannon accounts/actors
    - Delete ALL existing onchain MorseClaimableAccounts
    - Import the new set of MorseClaimableAccounts from the provided MsgImportMorseClaimableAccounts
    This is useful for testing purposes, but should be disabled in production.
    """
    morse_account_claiming_enabled: _builtins.bool
    """morse_account_claiming_enabled is a feature flag which is used to enable/disable the processing of Morse account/actor claim messages
    (i.e. `MsgClaimMorseAccount`, `MorseClaimApplication`, and `MorseClaimSupplier`).
    """
    def __init__(
        self,
        *,
        waive_morse_claim_gas_fees: _builtins.bool = ...,
        allow_morse_account_import_overwrite: _builtins.bool = ...,
        morse_account_claiming_enabled: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_morse_account_import_overwrite", b"allow_morse_account_import_overwrite", "morse_account_claiming_enabled", b"morse_account_claiming_enabled", "waive_morse_claim_gas_fees", b"waive_morse_claim_gas_fees"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Params: _TypeAlias = Params  # noqa: Y015
