"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from poktroll_clients.proto.cosmos.base.query.v1beta1 import pagination_pb2 as _pagination_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from poktroll_clients.proto.pocket.migration import morse_onchain_pb2 as _morse_onchain_pb2
from poktroll_clients.proto.pocket.migration import params_pb2 as _params_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class QueryParamsRequest(_message.Message):
    """QueryParamsRequest is request type for the Query/Params RPC method."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___QueryParamsRequest: _TypeAlias = QueryParamsRequest  # noqa: Y015

@_typing.final
class QueryParamsResponse(_message.Message):
    """QueryParamsResponse is response type for the Query/Params RPC method."""

    DESCRIPTOR: _descriptor.Descriptor

    PARAMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def params(self) -> _params_pb2.Params:
        """params holds all the parameters of this module."""

    def __init__(
        self,
        *,
        params: _params_pb2.Params | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryParamsResponse: _TypeAlias = QueryParamsResponse  # noqa: Y015

@_typing.final
class QueryMorseClaimableAccountRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    address: _builtins.str
    def __init__(
        self,
        *,
        address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryMorseClaimableAccountRequest: _TypeAlias = QueryMorseClaimableAccountRequest  # noqa: Y015

@_typing.final
class QueryMorseClaimableAccountResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MORSECLAIMABLEACCOUNT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def morseClaimableAccount(self) -> _morse_onchain_pb2.MorseClaimableAccount: ...
    def __init__(
        self,
        *,
        morseClaimableAccount: _morse_onchain_pb2.MorseClaimableAccount | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["morseClaimableAccount", b"morseClaimableAccount"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["morseClaimableAccount", b"morseClaimableAccount"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryMorseClaimableAccountResponse: _TypeAlias = QueryMorseClaimableAccountResponse  # noqa: Y015

@_typing.final
class QueryAllMorseClaimableAccountRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pagination(self) -> _pagination_pb2.PageRequest: ...
    def __init__(
        self,
        *,
        pagination: _pagination_pb2.PageRequest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryAllMorseClaimableAccountRequest: _TypeAlias = QueryAllMorseClaimableAccountRequest  # noqa: Y015

@_typing.final
class QueryAllMorseClaimableAccountResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MORSECLAIMABLEACCOUNT_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def morseClaimableAccount(self) -> _containers.RepeatedCompositeFieldContainer[_morse_onchain_pb2.MorseClaimableAccount]: ...
    @_builtins.property
    def pagination(self) -> _pagination_pb2.PageResponse: ...
    def __init__(
        self,
        *,
        morseClaimableAccount: _abc.Iterable[_morse_onchain_pb2.MorseClaimableAccount] | None = ...,
        pagination: _pagination_pb2.PageResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["morseClaimableAccount", b"morseClaimableAccount", "pagination", b"pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryAllMorseClaimableAccountResponse: _TypeAlias = QueryAllMorseClaimableAccountResponse  # noqa: Y015
