"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from poktroll_clients.proto.pocket.migration import morse_onchain_pb2 as _morse_onchain_pb2
from poktroll_clients.proto.pocket.migration import params_pb2 as _params_pb2
from poktroll_clients.proto.pocket.shared import service_pb2 as _service_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MsgUpdateParams(_message.Message):
    """MsgUpdateParams is the Msg/UpdateParams request type.

    - Used for updating the migration module parameters via governance
    - All parameters must be supplied
    Next free index: 3
    """

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    PARAMS_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """authority is the address that controls the module (defaults to x/gov unless overwritten)."""
    @_builtins.property
    def params(self) -> _params_pb2.Params:
        """Module parameters to update
        NOTE: All parameters must be supplied
        """

    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        params: _params_pb2.Params | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["params", b"params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authority", b"authority", "params", b"params"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgUpdateParams: _TypeAlias = MsgUpdateParams  # noqa: Y015

@_typing.final
class MsgUpdateParamsResponse(_message.Message):
    """MsgUpdateParamsResponse defines the response structure for executing a MsgUpdateParams message.

    - Empty response on success
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgUpdateParamsResponse: _TypeAlias = MsgUpdateParamsResponse  # noqa: Y015

@_typing.final
class MsgImportMorseClaimableAccounts(_message.Message):
    """MsgImportMorseClaimableAccounts is used to:

    - Create the on-chain MorseClaimableAccounts ONLY AND EXACTLY ONCE (per network / re-genesis)
    - Import Morse account state derived from Morse state export
    Next free index: 4
    """

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    MORSE_ACCOUNT_STATE_FIELD_NUMBER: _builtins.int
    MORSE_ACCOUNT_STATE_HASH_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """authority is the address that controls the module (defaults to x/gov unless overwritten)."""
    morse_account_state_hash: _builtins.bytes
    """Validates the morse_account_state sha256 hash:
    - Transaction fails if hash doesn't match on-chain computation
    - Off-chain social consensus should be reached before verification

    Verification (high-level):
      $ pocketd tx migration collect-morse-accounts $<(pocket util export-genesis-for-reset)

    Additional docs:
      - pocket util export-genesis-for-migration --help
      - pocketd tx migration collect-morse-accounts --help
    """
    @_builtins.property
    def morse_account_state(self) -> _morse_onchain_pb2.MorseAccountState:
        """Account state derived from Morse state export and `pocketd tx migration collect-morse-accounts`"""

    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        morse_account_state: _morse_onchain_pb2.MorseAccountState | None = ...,
        morse_account_state_hash: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["morse_account_state", b"morse_account_state"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authority", b"authority", "morse_account_state", b"morse_account_state", "morse_account_state_hash", b"morse_account_state_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgImportMorseClaimableAccounts: _TypeAlias = MsgImportMorseClaimableAccounts  # noqa: Y015

@_typing.final
class MsgImportMorseClaimableAccountsResponse(_message.Message):
    """MsgImportMorseClaimableAccountsResponse is returned from MsgImportMorseClaimableAccounts.

    - Indicates the canonical hash of the imported MorseAccountState
    - Reports the number of claimable accounts imported
    Next free index: 3
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgImportMorseClaimableAccountsResponse: _TypeAlias = MsgImportMorseClaimableAccountsResponse  # noqa: Y015

@_typing.final
class MsgClaimMorseAccount(_message.Message):
    """MsgClaimMorseAccount is used to:

    - Execute a claim (one-time minting of tokens on Shannon)
    - Claim the balance of a given Morse account per on-chain MorseClaimableAccounts
    - Mint claimed balance to the given Shannon account

    NOTE:
    - A transaction can contain ONE OR MORE Morse account/actor claim messages AND has EXACTLY ONE signer.
    - The Shannon account specified must be the message signer
    - Authz grants MAY be used to delegate claiming authority to other Shannon accounts
    """

    DESCRIPTOR: _descriptor.Descriptor

    SHANNON_SIGNING_ADDRESS_FIELD_NUMBER: _builtins.int
    SHANNON_DEST_ADDRESS_FIELD_NUMBER: _builtins.int
    MORSE_PUBLIC_KEY_FIELD_NUMBER: _builtins.int
    MORSE_SIGNATURE_FIELD_NUMBER: _builtins.int
    shannon_signing_address: _builtins.str
    """The bech32-encoded address of the Shannon account which is signing for this message.
    This account is liable for any fees incurred by violating the constraints of Morse
    account/actor claim message fee waiving.
    """
    shannon_dest_address: _builtins.str
    """The bech32-encoded address of the Shannon account to which the claimed balance will be minted."""
    morse_public_key: _builtins.bytes
    """The ed25519 public key of the morse account with morse_src_address."""
    morse_signature: _builtins.bytes
    """The hex-encoded signature, by the Morse account, of this message (where this field is nil).
    I.e.: morse_signature = private_key.sign(marshal(MsgClaimMorseAccount{morse_signature: nil, ...}))
    """
    def __init__(
        self,
        *,
        shannon_signing_address: _builtins.str = ...,
        shannon_dest_address: _builtins.str = ...,
        morse_public_key: _builtins.bytes = ...,
        morse_signature: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["morse_public_key", b"morse_public_key", "morse_signature", b"morse_signature", "shannon_dest_address", b"shannon_dest_address", "shannon_signing_address", b"shannon_signing_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgClaimMorseAccount: _TypeAlias = MsgClaimMorseAccount  # noqa: Y015

@_typing.final
class MsgClaimMorseAccountResponse(_message.Message):
    """MsgClaimMorseAccountResponse is returned from MsgClaimMorseAccount.

    - Indicates the morse_src_address of the claimed account
    - Reports the claimed balance and commit height
    Next free index: 4
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgClaimMorseAccountResponse: _TypeAlias = MsgClaimMorseAccountResponse  # noqa: Y015

@_typing.final
class MsgClaimMorseApplication(_message.Message):
    """MsgClaimMorseApplication is used to:

    - Execute a claim (one-time minting of tokens on Shannon) of total tokens owned by a Morse account
    - Mint claimed tokens to the given Shannon account
    - Stake that Shannon account as an application for the given service_config and same stake amount
    Next free index: 7
    """

    DESCRIPTOR: _descriptor.Descriptor

    SHANNON_SIGNING_ADDRESS_FIELD_NUMBER: _builtins.int
    SHANNON_DEST_ADDRESS_FIELD_NUMBER: _builtins.int
    MORSE_PUBLIC_KEY_FIELD_NUMBER: _builtins.int
    MORSE_SIGNATURE_FIELD_NUMBER: _builtins.int
    SERVICE_CONFIG_FIELD_NUMBER: _builtins.int
    shannon_signing_address: _builtins.str
    """The bech32-encoded address of the Shannon account which is signing for this message.
    This account is liable for any fees incurred by violating the constraints of Morse
    account/actor claim message fee waiving; the tx contains ONE OR MORE Morse account/actor
    claim messages AND has EXACTLY ONE signer.
    """
    shannon_dest_address: _builtins.str
    """The bech32-encoded address of the Shannon account to which the claimed tokens
    will be minted and from which the application will be staked.
    """
    morse_public_key: _builtins.bytes
    """The ed25519 public key of the morse account with morse_src_address."""
    morse_signature: _builtins.bytes
    """The hex-encoded signature, by the Morse account, of this message (where this field is nil).
    I.e.: morse_signature = private_key.sign(marshal(MsgClaimMorseAccount{morse_signature: nil, ...}))
    """
    @_builtins.property
    def service_config(self) -> _service_pb2.ApplicationServiceConfig:
        """The services this application is staked to request service for.
        NOTE: This is not a repeated field, as in MsgStakeApplication,
        because an application can only be staked for one service.
        """

    def __init__(
        self,
        *,
        shannon_signing_address: _builtins.str = ...,
        shannon_dest_address: _builtins.str = ...,
        morse_public_key: _builtins.bytes = ...,
        morse_signature: _builtins.bytes = ...,
        service_config: _service_pb2.ApplicationServiceConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["service_config", b"service_config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["morse_public_key", b"morse_public_key", "morse_signature", b"morse_signature", "service_config", b"service_config", "shannon_dest_address", b"shannon_dest_address", "shannon_signing_address", b"shannon_signing_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgClaimMorseApplication: _TypeAlias = MsgClaimMorseApplication  # noqa: Y015

@_typing.final
class MsgClaimMorseApplicationResponse(_message.Message):
    """MsgClaimMorseApplicationResponse is returned from MsgClaimMorseApplication.

    - Indicates the morse_src_address of the claimed account
    - Reports the unstaked balance claimed, application stake, and commit height
    - Returns the staked application
    Next free index: 6
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgClaimMorseApplicationResponse: _TypeAlias = MsgClaimMorseApplicationResponse  # noqa: Y015

@_typing.final
class MsgClaimMorseSupplier(_message.Message):
    """MsgClaimMorseSupplier is used to:

    - Execute a one-time minting of tokens on Shannon based on tokens owned by the given Morse account
    - Use the on-chain MorseClaimableAccounts for verification
    - Credit the minted tokens to the balance of the given Shannon account
    - Automatically stake that Shannon account as a supplier

    NOTE: The supplier module's staking fee parameter (at the time of claiming) is deducted from the claimed balance
    Next free index: 9
    """

    DESCRIPTOR: _descriptor.Descriptor

    SHANNON_SIGNING_ADDRESS_FIELD_NUMBER: _builtins.int
    SHANNON_OWNER_ADDRESS_FIELD_NUMBER: _builtins.int
    SHANNON_OPERATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    MORSE_NODE_ADDRESS_FIELD_NUMBER: _builtins.int
    MORSE_PUBLIC_KEY_FIELD_NUMBER: _builtins.int
    MORSE_SIGNATURE_FIELD_NUMBER: _builtins.int
    SIGNER_IS_OUTPUT_ADDRESS_FIELD_NUMBER: _builtins.int
    SERVICES_FIELD_NUMBER: _builtins.int
    shannon_signing_address: _builtins.str
    """The bech32-encoded address of the Shannon account which is signing for this message.
    This account is liable for any fees incurred by violating the constraints of Morse
    account/actor claim message fee waiving; the tx contains ONE OR MORE Morse account/actor
    claim messages AND has EXACTLY ONE signer.
    """
    shannon_owner_address: _builtins.str
    """The bech32-encoded address of the Shannon account to which the claimed tokens
    will be minted and which become the supplier owner.
    See: https://dev.poktroll.com/operate/configs/supplier_staking_config#staking-types.
    """
    shannon_operator_address: _builtins.str
    """The bech32-encoded address of the Shannon account to which will become the supplier operator.
    If empty, the shannon_owner_address will be used.
    See: https://dev.poktroll.com/operate/configs/supplier_staking_config#staking-types.
    """
    morse_node_address: _builtins.str
    """The hex-encoded address of the Morse non-custodial (i.e. operator) account.
    - Unstaked balance will be migrated 1:1
    - Stake will be migrated 1:1 from morse_node_address to shannon_operator_address
    - Morse non-custodial (i.e. operator) address.
    If morse_output_address is not set, this is the custodial address.
    - See 'pocket nodes --help' for more information. Note that this refers to the Morse CLI.
    E.g.: 00f9900606fa3d5c9179fc0c8513078a53a2073e
    """
    morse_public_key: _builtins.bytes
    """The ed25519 public key of EITHER the Morse node/supplier operator OR owner account.
    - MUST correspond to the private key which was used to produce the morse_signature.
    - MUST correspond to ONE OF THE FOLLOWING:
      - morse_node_address
      - morse_output_address
    """
    morse_signature: _builtins.bytes
    """The hex-encoded signature, of this message (where this field is nil).
    I.e.: morse_signature = private_key.sign(marshal(MsgClaimMorseSupplier{morse_signature: nil, ...}))
    - MUST match morse_public_key.
    - MUST be signed by ONE OF THE FOLLOWING:
      - Morse node account (i.e. operator); if signer_is_output_address is false
      - Morse output account (i.e. owner); if signer_is_output_address is true
    """
    signer_is_output_address: _builtins.bool
    """Set to true if the private key corresponding to the morse_output_address is producing the morse_signature.
    For non-custodial claiming:
    - This MUST be true.
    - The morse_public_key MUST correspond to morse_output_address.
    - The morse_signature MUST correspond to morse_output_address.
    """
    @_builtins.property
    def services(self) -> _containers.RepeatedCompositeFieldContainer[_service_pb2.SupplierServiceConfig]:
        """The services this supplier is staked to provide service for."""

    def __init__(
        self,
        *,
        shannon_signing_address: _builtins.str = ...,
        shannon_owner_address: _builtins.str = ...,
        shannon_operator_address: _builtins.str = ...,
        morse_node_address: _builtins.str = ...,
        morse_public_key: _builtins.bytes = ...,
        morse_signature: _builtins.bytes = ...,
        signer_is_output_address: _builtins.bool = ...,
        services: _abc.Iterable[_service_pb2.SupplierServiceConfig] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["morse_node_address", b"morse_node_address", "morse_public_key", b"morse_public_key", "morse_signature", b"morse_signature", "services", b"services", "shannon_operator_address", b"shannon_operator_address", "shannon_owner_address", b"shannon_owner_address", "shannon_signing_address", b"shannon_signing_address", "signer_is_output_address", b"signer_is_output_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgClaimMorseSupplier: _TypeAlias = MsgClaimMorseSupplier  # noqa: Y015

@_typing.final
class MsgClaimMorseSupplierResponse(_message.Message):
    """MsgClaimMorseSupplierResponse is returned from MsgClaimMorseSupplier.

    - Indicates the morse_operator_address of the claimed account
    - Reports the unstaked balance claimed, session end height, and staked supplier
    - Includes claim signer type and signer address
    Next free index: 10
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgClaimMorseSupplierResponse: _TypeAlias = MsgClaimMorseSupplierResponse  # noqa: Y015

@_typing.final
class MsgRecoverMorseAccount(_message.Message):
    """MsgRecoverMorseAccount is used to:

    - Execute a one-time minting of tokens on Shannon based on tokens owned by the given Morse account
    - Credit the minted tokens to the balance of the given Shannon account
    - Migrate unclaimable staked and liquid Morse tokens as liquid Shannon tokens

    - MAY ONLY be executed by the authority
    - ONLY intended for use on accounts with invalid addresses and/or known lost private keys
    Next free index: 4
    """

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    SHANNON_DEST_ADDRESS_FIELD_NUMBER: _builtins.int
    MORSE_SRC_ADDRESS_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """The bech32-encoded address of the migration module authority account ("gov" module address by default).
    ONLY the authority, or its delegates, MAY recover Morse recoverable accounts.
    """
    shannon_dest_address: _builtins.str
    """The bech32-encoded address of the Shannon account to which the Morse account's stake(s) and/or
    balance(s) will be minted (recovered) as liquid Shannon tokens.
    """
    morse_src_address: _builtins.str
    """EITHER:
    - The hex-encoded address of the recoverable Morse account whose stake(s) and/or balance(s) will be recovered.
      This address MAY be invalid but NEVER empty.
      E.g.: 00f9900606fa3d5c9179fc0c8513078a53a2073e
    - The name of a Morse module account whose balance will be recovered.
      E.g. "dao" or "fee-collector"
    """
    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        shannon_dest_address: _builtins.str = ...,
        morse_src_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authority", b"authority", "morse_src_address", b"morse_src_address", "shannon_dest_address", b"shannon_dest_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgRecoverMorseAccount: _TypeAlias = MsgRecoverMorseAccount  # noqa: Y015

@_typing.final
class MsgRecoverMorseAccountResponse(_message.Message):
    """MsgRecoverMorseAccountResponse is returned from MsgRecoverMorseAccount.

    - Indicates the morse_src_address of the recovered account
    - Reports the sum of any actor stakes and unstaked balance recovered
    - Reports the session end height in which the recovery was committed
    - Returns the destination Shannon address
    Next free index: 5
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgRecoverMorseAccountResponse: _TypeAlias = MsgRecoverMorseAccountResponse  # noqa: Y015

@_typing.final
class MsgAdminRecoverMorseAccount(_message.Message):
    """MsgAdminRecoverMorseAccount allows the authority to recover Morse accounts
    WITHOUT checking the allowlist. This enables faster recovery for legitimate
    requests that have been validated off-chain.

    SECURITY: This message can ONLY be called by the module authority.
    SAFETY: Still checks that the account exists and hasn't been claimed already.
    USE CASE: When the allowlist is outdated and the upgrade cycle is too slow.

    Key differences from MsgRecoverMorseAccount:
    - SKIPS allowlist validation (IsMorseAddressRecoverable check)
    - KEEPS all other safety checks (exists, not claimed, authority)
    - Emits a distinct event for audit trail
    Next free index: 4
    """

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    SHANNON_DEST_ADDRESS_FIELD_NUMBER: _builtins.int
    MORSE_SRC_ADDRESS_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    """The bech32-encoded address of the migration module authority account.
    ONLY the authority MAY call this admin recovery function.
    """
    shannon_dest_address: _builtins.str
    """The bech32-encoded address of the Shannon account to receive recovered tokens."""
    morse_src_address: _builtins.str
    """The hex-encoded address of the Morse account to recover.
    NOTE: This address is NOT checked against the allowlist.
    The authority is trusted to validate recovery requests off-chain.
    """
    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
        shannon_dest_address: _builtins.str = ...,
        morse_src_address: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authority", b"authority", "morse_src_address", b"morse_src_address", "shannon_dest_address", b"shannon_dest_address"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MsgAdminRecoverMorseAccount: _TypeAlias = MsgAdminRecoverMorseAccount  # noqa: Y015

@_typing.final
class MsgAdminRecoverMorseAccountResponse(_message.Message):
    """MsgAdminRecoverMorseAccountResponse is returned from MsgAdminRecoverMorseAccount.
    Next free index: 1
    Empty response - check events for recovery details
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MsgAdminRecoverMorseAccountResponse: _TypeAlias = MsgAdminRecoverMorseAccountResponse  # noqa: Y015
